### ISSUE TITLE
[Improvement] Bad request may not response JSON content

### ISSUE THREAD

**Issue by mchades** [apache/gravitino#1061]
### What would you like to be improved?

When handling an illegal JSON request from the client, the server response content type using text.

400 Bad Request response example:

```
Unrecognized field "distributions" (class com.datastrato.gravitino.dto.requests.TableCreateRequest$TableCreateRequestBuilder), not marked as ignorable (7 known properties: "properties", "distribution", "partitioning", "name", "columns", "comment", "sortOrders"])
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 35, column: 21] (through reference chain: com.datastrato.gravitino.dto.requests.TableCreateRequest$TableCreateRequestBuilder["distributions"])
```

### How should we improve?

The response should be format as:
```json
{
  "code": 1003,
  "type": "BadRequestException",
  "message": "Malformed request",
  "stack": ["..."]
}
```

**Comment by mchades** [comment]
> @mchades Are you still working on this issue ?

no, feel free to start if you're interested.

**Comment by featherchen** [comment]
Sure, I will take a look on it.

**Comment by featherchen** [comment]
@mchades  Hi, I have a few questions. If using Exception Mapper to conver the exception to illegalArgument exception, 1) which exception should we deal with ? In the original statement, the exception is UnrecognizedPropertyException, however this is a subclass of JsonMappingException. So, maybe we could try to convert JsonMappingException instead to handle other potential error ? 2) I am not sure that the error code should be `1003` or `1001`? Based on [ErrorConstant](https://github.com/datastrato/gravitino/blob/main/common/src/main/java/com/datastrato/gravitino/dto/responses/ErrorConstants.java#L8) `1003` is used for `not found`, and `1001` for `illegal arguments`, both seems to make sense ? 3) I didn't find BadRequestException is defined in ErrorResponse class, therefore, if we want to convert the exceptions to this type of Exception, we might need to add it in ErrorResponse.java ?

**Comment by mchades** [comment]
> I have a few questions. If using Exception Mapper to conver the exception to `IllegalArgument` (or `BadRequestException`) exception,
> 
> 1. which exception should we deal with? In the original statement, the exception is `UnrecognizedPropertyException`, however this is a subclass of `JsonMappingException`. So, maybe we could try to convert `JsonMappingException` instead to handle other potential error ?

yes, We can only handle exception `JsonMappingException`

> 2. I am not sure that the error code should be `1003` or `1001`? Based on [ErrorConstant](https://github.com/datastrato/gravitino/blob/main/common/src/main/java/com/datastrato/gravitino/dto/responses/ErrorConstants.java#L8), `1003` is used for `not found`, and `1001` is for `illegal arguments`, both seems to make sense ?

we should use `1001` as the error code, sorry for the wrong example in the issue describtion.

> 3. I didn't find `BadRequestException` type of response is defined in [ErrorResponse class](https://github.com/datastrato/gravitino/blob/e34c8253cd57e9e5a846136e087801acffba61fa/common/src/main/java/com/datastrato/gravitino/dto/responses/ErrorResponse.java#L23), therefore, if we want to convert the exceptions to this type of Exception, we might need to add such response in `ErrorResponse.java` ?

We can use `IllegalArgumentException`, the example in the description is just something I wrote quickly. What we are focusing on is its format, not its content.
