### ISSUE TITLE
[Improvement] DropXxx response should include failed message

### ISSUE THREAD

**Issue by mchades** [apache/gravitino#1062]
### What would you like to be improved?

The current `DropXxxx` response body only includes `code` and boolean `dropped`. As a result, the user is unable to determine the reason for the failure of the drop operation.

### How should we improve?

Add a fail reason to the response body when the drop operation failing

**Comment by charliecheng630** [comment]
@mchades I'm interested in this issue. Should I start tracking this issue from DropResponse.java?

**Comment by mchades** [comment]
> @mchades I'm interested in this issue. Should I start tracking code from DropResponse.java?

As [discussed there](https://github.com/datastrato/gravitino/issues/2392#issuecomment-1970630846), we need to come to a consensus on a couple of issues before we can address this, do you have any thoughts on that? @charliecheng630

**Comment by diqiu50** [comment]
If the drop is successful, return true; otherwise, throw an exception, except when `ignore_no_exist` = true.

**Comment by mchades** [comment]
> If the drop is successful, return true; otherwise, throw an exception, except when ignore_no_exist = true.

This issue concerns the behavior of DELETE response in RESTful APIs, which is determined by the conclusions of #2434. So let's discuss in #2434 @diqiu50

**Comment by charliecheng630** [comment]
I would like to work on this.

**Comment by charliecheng630** [comment]
@mchades 
After the revisit, when exceptions occur, the DropResponse already includes the failed message. This issue seems to have been gradually resolved. Are there any other areas that still need adjustments?

**Comment by mchades** [comment]
> @mchades After the revisit, when exceptions occur, the DropResponse already includes the failed message. This issue seems to have been gradually resolved. Are there any other areas that still need adjustments?

yeah, you're right. 

Since the behavior of 'drop' has been clarified now(#3222), it will only return false when the target object does not exist. 

So, this issue does not exist anymore. I will close this issue. Thank you for your feedback!
