### ISSUE TITLE
[Improvement] Gravitino should throw a exception when deserialization unknown fields.

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#1115]
### What would you like to be improved?

 I pass `IfExist` not `IfExists` to `DeleteColumn` request , Gravitino server eat it silently and construct DeleteColumn with `IfExists` = false unexpected.

**Comment by SteNicholas** [comment]
@FANNG1, `TableUpdateRequest` is annotationed with `@JsonIgnoreProperties(ignoreUnknown = true)` which means that ignores any unrecognized properties during deserialization. Therefore, which's the purpose of this issue?

**Comment by FANNG1** [comment]
I prefer to remove `@JsonIgnoreProperties(ignoreUnknown = true)`,  because user may pass a wrong filed name, this may leading unexpected result. @jerryshao what's your advise?

**Comment by SteNicholas** [comment]
@FANNG1, if the advise of @jerryshao is also removing `@JsonIgnoreProperties(ignoreUnknown = true)`, I will take this issue to remove this annotation.

**Comment by FANNG1** [comment]
sure, feel free to assign to your self

**Comment by jerryshao** [comment]
> @FANNG1, if the advise of @jerryshao is also removing `@JsonIgnoreProperties(ignoreUnknown = true)`, I will take this issue to remove this annotation.

I agree that we should check the validity of the JSON field, instead of ignoring it, also not just for this request but for all the other requests.

But instead, I was thinking of protocol compatibility. If we add a field unknown to the current version of Gravitino, do we need to make it work or fail? So if we only guarantee backward compatibility, adding a strict check is OK, if we guarantee forward compatibility, then a strict check may not work.

**Comment by FANNG1** [comment]
I wondered if there are any ways to both keep `forward compatibility` and resolve this issue :(

**Comment by SteNicholas** [comment]
@jerryshao, @FANNG1, IMO, we should guarantee forward and backward compatibility, instead of keeping one of compatibility. Therefore it's unnecessary to have a strict check here.

**Comment by jerryshao** [comment]
> @jerryshao, @FANNG1, IMO, we should guarantee forward and backward compatibility, instead of keeping one of compatibility. Therefore it's unnecessary to have a strict check here.

So there's nothing we need to fix now @SteNicholas @FANNG1 ?

**Comment by SteNicholas** [comment]
@jerryshao, IMO, there is nothing to do for this issue. Please close this issue.

**Comment by jerryshao** [comment]
I would leave this issue open, the case above in the issue description does need a better solution, currently we don't have a better solution for it.
