### ISSUE TITLE
[EPIC] Add file type catalog support for Gravitino

### ISSUE THREAD

**Issue by jerryshao** [apache/gravitino#1241]
### Describe the proposal

Gravitino currently only supports relational type catalog, with the increased requirements of managing datasets in object store or file systems, we should add the file type catalog support in Gravitino.stores

### Task list

- [x] #1284 
- [x] #1244
- [x] #1520
- [x] #1526 
- [x] #1527 
- [x] #1667 
- [x] #1489 
- [x] #1616
- [x] #1713
- [x] #1724 
- [x] #1838 
- [x] #2041 
- [x] #2059 
- [x] #2287 
- [x] #2292
- [x] #2307 
- [x] #2367 
- [x] #2695

**Comment by coolderli** [comment]
@jerryshao Hi, I'd like to continue to work on these issues:
- Add Java client support for fileset
- Add E2E integration test for fileset

Are you working on them? Will this affect the release of version 0.4？

 The last issue `Add Python Arrow FileSystem implementation for fileset.` may be beyond my current ability range. So I want to finish the above two issues first.

**Comment by jerryshao** [comment]
@coolderli I don't work on this, these two will not be in 0.4.0, it will target to 0.5.0. You can go ahead if you'd like to.
