### ISSUE TITLE
[EPIC] Good first issues

### ISSUE THREAD

**Issue by qqqttt123** [apache/gravitino#1335]
### Describe the proposal

These issues are a great way to get started with a project. Any contribution is important for the Gravitino community. If the issues have been assigned to others, but there isn't any progress for more than 3 months. You can ask maintainers (https://github.com/datastrato/gravitino/blob/main/MAINTAINERS.md) to assign it to you, too.
The steps of contribution is as follows: 
https://github.com/datastrato/gravitino/blob/main/CONTRIBUTING.md

#### Simple Tasks:
If you're not familiar about the code of Gravitino and want to realize this project by some tasks. These issues are suitable for you.
- [x] #1361 
- [x] #1367
- [x] #1390

#### Code Style Improvements:
If you're not familiar about Gravitino but you have some experience about Java. These issues are suitable for you.
- [x] #1220
- [x] #1267
- [x] #1357
- [ ] https://github.com/datastrato/gravitino/issues/592

#### CI and Build Improvements:
If you're not familiar about Gravitino but have some experience about Github Actions or Gradle. These issues are suitable for you.
- [x] #1282
- [x] #1268
- [x] #768
- [ ] https://github.com/datastrato/gravitino/issues/1377

#### Document Improvements:
If you don't have much experience about Java and Gravitino but want to contribute to this project. You can try to improve the documents of this project.
- [x] #1346

**Comment by juliajobczyk** [comment]
Can I be assigned to improve the documents please?

**Comment by jerryshao** [comment]
Close as duplicated.
