### ISSUE TITLE
[FEATURE] Implement a JDBC catalog of SQLITE

### ISSUE THREAD

**Issue by qqqttt123** [apache/gravitino#1336]
### Describe the feature

 Implement a JDBC catalog of SQLITE

### Motivation

It will be convenient for some tests.

### Describe the solution

We can refer to other JDBC implements.

**Comment by brandboat** [comment]
Hi, I'm interested in this issue. May I take over this ? Many thanks~

**Comment by xunliu** [comment]
hi @brandboat , Thank you for your interest in this issue.
Of course, Please help Gravitino implement it.

**Comment by Adityamalik123** [comment]
@xunliu Could this issue be assigned to me if no one is currently working on it? Thank you!

**Comment by mchades** [comment]
I'm going to close this issue as SQLITE has already been used in the JDBC test:
https://github.com/apache/gravitino/blob/6b3312a017cbe3282578ad454caf1cb65fa6eb02/catalogs/catalog-jdbc-common/src/test/java/org/apache/gravitino/catalog/jdbc/operation/TestJdbcTableOperations.java#L114
