### ISSUE TITLE
[Improvement] Add copyright check for new files

### ISSUE THREAD

**Issue by qqqttt123** [apache/gravitino#1377]
### What would you like to be improved?

We should add a check script to check the copyright of new files.

### How should we improve?

We can add a ci task to check  every new file whether has the copyright `2024`. For every new file, we can use git to get them.

**Comment by hiirrxnn** [comment]
Can i work on this? Please tell me what is to be done here.

**Comment by mchades** [comment]
Close since we have the rat plugin in Gradle
