### ISSUE TITLE
[Improvement] Get Gavitino working on Windows with WSL

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#1414]
### What would you like to be improved?

Get Gavitino working on Windows with the Windows Subsystem for Linux.

### How should we improve?

It should be possible to get Gavitino working on Windows with the Windows Subsystem for Linux. Try this out, see what issues exist, and document how to get to working on Windows.

**Comment by evalaiyc98** [comment]
I use Windows 11 and Windows Subsystem for Linux (WSL 2). I think I can help to solve this issue.

**Comment by justinmclean** [comment]
Does anyone want to try and test this? I think some progress has been made but I don't have a windows machine to test this on.

**Comment by jerryshao** [comment]
It is already fixed by @jtao1 .
