### ISSUE TITLE
[Bug report] Using Visual Studio Code on a checkout of Gravitino fails to compile in the IDE

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#1479]
### Describe what's wrong

The trino-connector project will fail to compile when gravitino is opened as a Java project in Visual Studio Code. JDK 17 was installed.

### Error message and/or stacktrace

![image](https://github.com/datastrato/gravitino/assets/144504/db4d94ed-d64f-49c0-a459-d6c8f6591d5f)

### How to reproduce

The latest version, a clone of the main branch.

### Additional context

You can build via the command line successfully with `.\gradlew build -x test`.

**Comment by jerryshao** [comment]
I'm going to close this as it is too old, we can reopen it when we have such issue.
