### ISSUE TITLE
[Improvement] Change java package name?

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#1506]
### What would you like to be improved?

Currently, the package name is "com.datastrato.gravitino" Should we change this to "com.gravitino" or something else? Note we may be asked to do this when we donate the code to the ASF perhaps to "org.apache.gravitino"? The ASF generally disallows company names in packages but will allow if it's hard to change. (Apache Flex is a good example of this.)

### How should we improve?

Consider what to do.

**Comment by jerryshao** [comment]
Fixed.
