### ISSUE TITLE
[Improvement] The github README build and integration test badge doesn't reflect the correct status

### ISSUE THREAD

**Issue by jerryshao** [apache/gravitino#1617]
### What would you like to be improved?

The current build and integration test badge doesn't reflect the build/IT result of **merged commits**, instead, it just reflects the current status of CI (including the CI status of unmerged PR).

It is misleading, we need to fix it.

**Comment by hiirrxnn** [comment]
I would like to work on this.

**Comment by jerryshao** [comment]
> I would like to work on this.

Thanks, please go ahead.

**Comment by hiirrxnn** [comment]
When I go to actions and try to create a new badge for IT and build , it produces same link as the one already in the README.md file , please guide me regarding what to do now.

**Comment by jerryshao** [comment]
Sorry, I don't know how to handle it for now. Probably need some googling.

**Comment by hiirrxnn** [comment]
Could you tell me the CI/CD provider or build system we're using for our project (e.g., Jenkins, Travis CI, CircleCI, GitLab CI/CD, etc.).
