### ISSUE TITLE
[Improvement] Google Summer of Code contributor guidance

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#1697]
### What would you like to be improved?

Please provide a brief CV, a little about yourself, and (if possible) a sample of code that you have written yourself.

In your application please include answers to the following questions:
	•	What interests you about our project?
	•	What interests you about open source software?
	•	As mentors how can we get the best out of you?
	•	Are you studying or working on anything, while working on our project?

Once you’ve selected a project assignment from the ideas page, please include a well-defined, weekly schedule with clear milestones and deliverables around it. Alternatively, if you want to propose your own idea then please include an outline, goals, and a well-defined weekly schedule with clear milestones and deliverables.

Applications missing information will not be considered.

**Comment by jerryshao** [comment]
I'm going to close this as it is not valid any more.
