### ISSUE TITLE
[Bug report]Download driver when encounter the error 'Cannot load JDBC driver', but it still fail to list schema under the catalog as the same error until rename the catalog.

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#1812]
### Version

main branch

### Describe what's wrong

create a postgres catalog before download the driver,
then download the driver to the catalogs/jdbc-postgresql/libs directory,
fail to list schema 

### Error message and/or stacktrace

{
    "code": 1002,
    "type": "RuntimeException",
    "message": "Failed to operate object operation [LIST] under [pg1], reason [Cannot load JDBC driver class 'org.postgresql.Driver']",
    "stack": [
        "java.lang.RuntimeException: com.datastrato.gravitino.exceptions.GravitinoRuntimeException: Cannot load JDBC driver class 'org.postgresql.Driver'",
        "\tat com.datastrato.gravitino.catalog.CatalogOperationDispatcher.doWithCatalog(CatalogOperationDispatcher.java:752)",
        "\tat com.datastrato.gravitino.catalog.CatalogOperationDispatcher.listSchemas(CatalogOperationDispatcher.java:103)",
        "\tat com.datastrato.gravitino.server.web.rest.SchemaOperations.lambda$listSchemas$0(SchemaOperations.java:68)",
        "\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:712)",
        "\tat java.base/javax.security.auth.Subject.doAs(Subject.java:439)",
        "\tat com.datastrato.gravitino.utils.PrincipalUtils.doAs(PrincipalUtils.java:25)",
        "\tat com.datastrato.gravitino.server.web.Utils.doAs(Utils.java:121)",
        "\tat com.datastrato.gravitino.server.web.rest.SchemaOperations.listSchemas(SchemaOperations.java:64)",
        "\tat jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)",
        "\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)",
        "\tat org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0

### How to reproduce

create a postgres catalog before download the driver,
list the schema under the catalog, encounter the error "Cannot load JDBC driver",
then download the driver to the catalogs/jdbc-postgresql/libs directory,
list schema of the pg catalog again.

### Additional context

The error can be workaround if I rename the catalog

**Comment by jerryshao** [comment]
@Clearvive can you please take a look.

**Comment by jerryshao** [comment]
Yeah, seems like a general problem that current catalog doesn't support restart or reinitialize after changing something, we can defer this to the next version to figure out an overall solution.

**Comment by yuqi1129** [comment]
A simple solution is to modify the catalog after downloading the driver-jar and let the class loader reload the driver class. No other solution good enough has been found.

**Comment by yuqi1129** [comment]
No good solution is found to resolve this problem, close it temporarily and reopen it if any progress has been achieved.
