### ISSUE TITLE
[Improvement] in `GravitinoMetaLake.java` subclass has equals method but parent does not

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#1903]
### What would you like to be improved?

Class should have an equals method.

### How should we improve?

Add equals method.

**Comment by Goldencode20** [comment]
I am happy to try this! I have not worked on an Open Source project before but I think I understand everything I need to do.

**Comment by Goldencode20** [comment]
Just to make sure I understand, do I add the equals method from MetalakeDTO to GravitinoMetaLake?

**Comment by LindaSummer** [comment]
Hi @justinmclean ,

This issue seems to be inactive in past 4 months.
Can this be assigned to me?

Best Regards,
Edward

**Comment by justinmclean** [comment]
Sure, you might want to read the comments in https://github.com/apache/gravitino/pull/4448
