### ISSUE TITLE
[Improvement] In `HadoopCatalogOperations.java` field `entity` is not used

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#1908]
### What would you like to be improved?

The field `entity` is not used, also it hidden by this:
```java
      SchemaEntity entity =
          store.update(
              ident,
              SchemaEntity.class,
              Entity.EntityType.SCHEMA,
              schemaEntity -> updateSchemaEntity(ident, schemaEntity, changes));
```
Is this a possible bug?

### How should we improve?

Either use it or remove it.

**Comment by Akshayp02** [comment]
Removing the `entity` variable and its related calls should make the code cleaner and easier to understand. and I was thinking about to remove the `entity` but issue is that if i try to access schemaEntity directly within the catch block, but schemaEntity is defined within the lambda expression passed to the store.update() method. Therefore, it's not accessible in the catch block or outside of the lambda expression.


so I've probably solution is to access the properties of the updated schema entity `schemaEntity` within the catch block, might consider an alternative approach, such as saving the updated schema entity to a local variable before the try-catch block

**Comment by poojatalele** [comment]
I would like to work on this, kindly assign

**Comment by poojatalele** [comment]
SchemaEntity schemaEntity = new SchemaEntity();
try {
    schemaEntity = store.update(
        ident,
        SchemaEntity.class,
        Entity.EntityType.SCHEMA,
        entity -> updateSchemaEntity(ident, entity, changes)
    );
} catch (Exception e) {
    System.out.println("Error updating schema entity: " + schemaEntity);
    e.printStackTrace();
}

I am thinking to make this changes..kindly review this once.

**Comment by justinmclean** [comment]
@poojatalele do you still want to work on this?

**Comment by justinmclean** [comment]
Actually looks like this has been fixed so closing.
