### ISSUE TITLE
[Bug report] Gravitino UI misleading repeated error message

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#2110]
### Version

main branch

### Describe what's wrong

When Gravitino is running you get a reapeat misleading error message.
<img width="1512" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/6607ff25-ad49-463a-bcd2-82f2ad651fa8">

I would not say:
"Please check if your network connection is normal! The network is abnormal"

I would say something like:
"Unable to connect to Gravitino. Please check if Gravitino is running."

### Error message and/or stacktrace

See image above

### How to reproduce

Start up the Gravitino UI without Gravitino running.

**Comment by jerryshao** [comment]
@LauraXia123 please help to check this.

**Comment by LauraXia123** [comment]
I'll fix this issue.
