### ISSUE TITLE
[Improvement] Improper String Formatting in `TrinoITContainer.java`

### ISSUE THREAD

**Issue by M-Faheem-Khan** [apache/gravitino#2174]
### What would you like to be improved?

Use proper string formatting here as the the error thrown would not properly format the `serviceName` variable into the string. 

```JAVA
throw new ContainerLaunchException("The container for the {} service is not started: " + serviceName);      
```

### How should we improve?

Use `String.format` to format the exception message.

```JAVA
throw new ContainerLaunchException("The container for the %s service is not started.", serviceName));
```

**Comment by justinmclean** [comment]
This may have been fixed in #1746. If not, note the preference for printf style strings.

**Comment by M-Faheem-Khan** [comment]
Updated example code with `printf` style! I've checked the changes and it seems the the fix was not applied.

**Comment by justinmclean** [comment]
Thanks for checking, and thank you for your contribution.
