### ISSUE TITLE
[Improvement] HTTPClient.java has no unit tests/coverage

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#2182]
### What would you like to be improved?

HTTPClient.java has no unit tests/coverage

### How should we improve?

Write unit tests to provide code coverage.

**Comment by ajayl83** [comment]
@justinmclean i am picking up this!

**Comment by zzzk1** [comment]
@justinmclean can i pick up this issue thx?

**Comment by mrkartik00** [comment]
where to provide the test code

**Comment by justinmclean** [comment]
@zzzk1 how are you going with this issue?

**Comment by zzzk1** [comment]
> @zzzk1 how are you going with this issue?

Sorry for the late reply. It looks like HTTPClient.java already has a test case. I am trying to improve the test coverage.

**Comment by chenyuan99** [comment]
@justinmclean agree, it already got coverage in https://github.com/apache/gravitino/blob/6990036d5637e4a70690cad2f198466ac3612d1b/clients/client-java/src/test/java/org/apache/gravitino/client/TestHTTPClient.java

**Comment by justinmclean** [comment]
OK I think we can close this issue.
