### ISSUE TITLE
[Improvement] HiveTableOperations.java has no unit tests/coverage

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#2183]
### What would you like to be improved?

HiveTableOperations.java has no unit tests/coverage

### How should we improve?

Write unit tests to provide code coverage

**Comment by LindaSummer** [comment]
Hi @justinmclean ,

I want to work on this issue.
Can it be assigned to me? 😊

Best Regards,
Edward

**Comment by justinmclean** [comment]
This was raised some time ago, so it might have been done, you might want to check that first.

**Comment by LindaSummer** [comment]
Hi @justinmclean ,

  Sorry for delay update.
  I have checked this issue and find that `HiveTableOperations` unit tests have been added.
  Maybe this issue can be closed.

Best Regards,
Edward

**Comment by justinmclean** [comment]
Thanks for checking that feel free to pick another issue or work on or to improve our test coverage in other places.
