### ISSUE TITLE
[Improvement] IcebergMetricsManager.java has no unit tests/coverage

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#2184]
### What would you like to be improved?

IcebergMetricsManager.java has no unit tests/coverage

### How should we improve?

Write unit tests to provide coverage.

**Comment by yaoderek** [comment]
Hi @justinmclean 

I want to work on this issue.
Could this task be assigned to me?

Derek

**Comment by mchades** [comment]
@justinmclean How did you discover this issue? I think this should be done by the CI tool? @yuqi1129 Any progress on enabling Jacoco?

**Comment by justinmclean** [comment]
I looked at the code coverage. The issue is quite old, and Jacoco was working on them.

**Comment by yuqi1129** [comment]
> @justinmclean How did you discover this issue? I think this should be done by the CI tool? @yuqi1129 Any progress on enabling Jacoco?

No, it has been suspended for several months. Let me double-check if I have time.
