### ISSUE TITLE
[Improvement] HiveCatalogOperations.java has no unit tests/code coverage

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#2185]
### What would you like to be improved?

HiveCatalogOperations.java has no unit tests/code coverage

### How should we improve?

Write unit tests to improve code coverage.

**Comment by ajayl83** [comment]
@justinmclean i am picking up this one

**Comment by mchades** [comment]
How did you discover this issue? I noticed that the code coverage report bot on GitHub is no longer working. 

Can you please help to address this issue first?

**Comment by justinmclean** [comment]
I just looked at the code coverage report locally.

**Comment by ajayl83** [comment]
@justinmclean i need bit help on this one, specially testing the private methods... i need to understand specially how does the hadoopConf is created.
<img width="1280" alt="Screenshot 2024-03-17 at 15 51 24" src="https://github.com/datastrato/gravitino/assets/10277318/d4f89a96-9b1c-4d04-8053-2f184de84f71">

**Comment by ajayl83** [comment]
@justinmclean can you help me with this? how can i mock or add correct hadoopconf for the test?

**Comment by ajayl83** [comment]
@justinmclean no need to mock, there is existing test which can be extended with correct conf properties to test the private methods.

**Comment by mchades** [comment]
Can we fix the code coverage report bot on GitHub first?

**Comment by TungYuChiang** [comment]
Hi, I noticed this Issue was previously assigned but seems inactive now. 
Please let me know if it has already been resolved or if it’s still open.
If the issue still exists, would it be possible for me to take over and work on it?

**Comment by justinmclean** [comment]
I've not looked to see if it has been fixed or not, but as it has been open for a long time this may have been fixed. if you want to take a look, that would be great.

**Comment by mchades** [comment]
I'm going to close this issue since `org.apache.gravitino.catalog.hive.TestHiveCatalogOperations` already exists

**Comment by TungYuChiang** [comment]
ok~ thank you~
