### ISSUE TITLE
[Subtask] Doris docker runtime environment

### ISSUE THREAD

**Issue by zhoukangcn** [apache/gravitino#2221]
### Describe the subtask

The official Docker image of Apache Doris and the CI environment Docker image of the Apache Kyuubi community do not seem to be suitable for Gravatino

Consider building an all-in-one Docker image for Doris for CI purposes.

### Parent issue

#1339

**Comment by justinmclean** [comment]
Hi @zhoukangcn thanks for raising the issue. Do you want to work on this?

**Comment by zhoukangcn** [comment]
@justinmclean Yes, I will complete this task in the next few days.
