### ISSUE TITLE
[EPIC] User system 

### ISSUE THREAD

**Issue by qqqttt123** [apache/gravitino#2232]
### Describe the proposal

For Gravitino, we should propose a user system to accomplish the need of permission and security. I will propose a draft pull request to provide a global view. Then, I will submit following pull requests to merge to the master branch.

### Task list

- [x] #2234 
- [x] #2235 
- [x] #2236 
- [x] #2237 
- [x] #2238 
- [x] #2239 
- [x] #2240 
- [x] #2241 
- [ ] #2242 
- [ ] #2243 
- [ ] #2244 
- [ ] #2245 
- [x] #2246 
- [x] #2247 
- [x] #2248 
- [x] #2249 
- [x] #2250
- [x] #2499
- [x] #2759

**Comment by coolderli** [comment]
@qqqttt123 Is there some design doc about this? I want to learn about this. Thanks.

**Comment by qqqttt123** [comment]
> @qqqttt123 Is there some design doc about this? I want to learn about this. Thanks.

https://docs.google.com/document/d/1JRqyEHiNluk5zzCldSm84LPv3XBZ7dX7FJ6owL4i-7U/edit#heading=h.f9bvay8754au
