### ISSUE TITLE
[FEATURE] Support catalog rebooting after altered

### ISSUE THREAD

**Issue by jerryshao** [apache/gravitino#2267]
### Describe the feature

Currently, when we update some of the catalog parameters, Gravitino just updates the parameters without doing others. So the new parameters cannot take effect. A simple scenario is that: 

When we create a MySQL catalog with wrong jdbc URL, it doesn't work even after we alter the catalog with new parameter. What currently we can do is to delete the old catalog, and create a new one with the correct parameter.

This is very inconvenient. 

### Describe the solution

We should support rebooting the catalog when the catalog is altered. Since this is a pretty large work, we should have a concrete design before doing.

**Comment by yuqi1129** [comment]
Gravitino supports this functionality and this can be addressed by #4262
