### ISSUE TITLE
[Bug report]list metalakes/catalogs costs more than 20s in multi-thread testing scenario.

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#2383]
### Version

main branch

### Describe what's wrong

<img width="800" alt="截屏2024-02-28 14 11 54" src="https://github.com/datastrato/gravitino/assets/154112360/24018cb1-f7c4-46a1-a295-1a97ca60a3cb">
<img width="1082" alt="截屏2024-02-28 14 05 42" src="https://github.com/datastrato/gravitino/assets/154112360/486bfea9-e7c4-4ff9-9607-93a195a2d8b2">

### Error message and/or stacktrace

N/A

### How to reproduce

There's 100 metalakes, 100 catalogs,10000 schemas, 100000 tables in the test environment
set 10 threads  concurrently list metalake ,catalog, schemas, tables

**Comment by jerryshao** [comment]
@yuqi1129 please take a look.

**Comment by danhuawang** [comment]
updated
<img width="1180" alt="image" src="https://github.com/datastrato/gravitino/assets/154112360/1a8d39a4-db09-4695-8870-ccf2a317bdc3">

**Comment by coolderli** [comment]
@danhuawang Can you have a test for the Fileset operation? Thanks.

**Comment by yuqi1129** [comment]
It has been fixed
