### ISSUE TITLE
[Bug report] Gravitino-trino-connector don't work with Trino-435 worker

### ISSUE THREAD

**Issue by theoryxu** [apache/gravitino#2428]
### Version

main branch

### Describe what's wrong

When the node is a worker rather than a coordinator, there are some error and the node can't start.

<img width="955" alt="image" src="https://github.com/datastrato/gravitino/assets/6671568/b6ea7fc7-0835-4623-b083-26199e04f00a">

### Error message and/or stacktrace

![image](https://github.com/datastrato/gravitino/assets/6671568/b115c92e-0839-46d4-aa58-d586339f4d05)

### How to reproduce

0.4.0

### Additional context

related to https://github.com/datastrato/gravitino/issues/2376

**Comment by theoryxu** [comment]
@diqiu50  Hi, will this issue also be fixed in 0.5.0?

**Comment by diqiu50** [comment]
Yes

**Comment by diqiu50** [comment]
It fix now
