### ISSUE TITLE
[Improvement] Remove directory `spark-warehouse` when exectue `gradle clean` in moudle `catalog-lakehouse-iceberg`

### ISSUE THREAD

**Issue by yuqi1129** [apache/gravitino#2508]
### What would you like to be improved?

`spark-warehouse` is a temporary directory produced by the test, we need to remove it when do the clean task.

![image](https://github.com/datastrato/gravitino/assets/15794564/ea38a664-45ee-494d-8bcd-74f71fc63674)

You can generate `spark-warehouse`  by `gradle :catalogs:catalog-lakehouse-iceberg:test`

 ### How should we improve?

_No response_

**Comment by jwhitt3r** [comment]
Happy to take a look at this.

**Comment by yijhenlin** [comment]
Hi, I would like to solve this issue.

**Comment by yijhenlin** [comment]
Hi, there leave another empty directory `server/src/main/resources/` after execute gradle clean.
should I remove it too? 
```
$ git clean -d -n
Would remove server/src/main/resources/
```
