### ISSUE TITLE
[Bug report]When column data type is double and default value is 0.00 in mysql db, but the default value is 0.0 in gravitino

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#2538]
### Version

main branch

### Describe what's wrong

1. create a table in mysql db 
```
CREATE TABLE t1 (
  i     INT DEFAULT -1,
  c     VARCHAR(10) DEFAULT 'abc',
  price DOUBLE(16,2) DEFAULT 0.00 ,
  f     FLOAT       DEFAULT (RAND() * RAND()),
  d     DATE        DEFAULT (CURRENT_DATE + INTERVAL 1 YEAR),
  b     BINARY(16)  DEFAULT (UUID_TO_BIN(UUID()))
);
```
2. get  the table through gravitino api
3.  the default value of column "price" is changed to 0.0   in gravitino  api response
```
            {
                "name": "price",
                "type": "double",
                "nullable": true,
                "autoIncrement": false,
                "defaultValue": {
                    "type": "literal",
                    "dataType": "double",
                    "value": "0.0"
                }
            }
```

### Error message and/or stacktrace

N/A

### How to reproduce

1. Create table with the following request
```
{
  "name": "t1",
  "comment": "This is my mysql table1",
  "columns": [
    {
      "name": "id",
      "type": "integer",
      "comment": "id column comment",
      "nullable": false,
      "autoIncrement": false,
      "defaultValue": {
        "type": "literal",
        "dataType": "integer",
        "value": "-1"
      }

    },
    {
      "name": "name",
      "type": "varchar(500)",
      "comment": "name column comment",
      "nullable": true,
      "autoIncrement": false,
      "defaultValue": {
        "type": "literal",
        "dataType": "varchar(500)",
        "value": "abc123"
      }
    },
    {
      "name": "price",
      "type": "double",
      "comment": "price column comment",
      "nullable": true,
      "autoIncrement": false,
      "defaultValue": {
        "type": "literal",
        "dataType": "double",
        "value": "0.00"
      }
    }
  ],
  "indexes": [
    {
      "indexType": "primary_key",
      "name": "PRIMARY",
      "fieldNames": [["id"]]
    }
  ]
}
```
2. check the "price" column's default value in response

**Comment by mchades** [comment]
Gravitino's type system does not support specifying precision for double, and specifying precision for double is not considered a standard or common practice. Moreover, it is not recommended in [MySQL](https://dev.mysql.com/doc/refman/8.0/en/floating-point-types.html) either：

> As of MySQL 8.0.17, the nonstandard FLOAT(M,D) and DOUBLE(M,D) syntax is deprecated and you should expect support for it to be removed in a future version of MySQL.

Therefore, I suggest modifying the test to check for decimal precision instead of double.  @jerryshao @xunliu What's your opinion?

**Comment by jerryshao** [comment]
Sure, @danhuawang let's update the test case.

**Comment by danhuawang** [comment]
OK. I will update the test case to check for decimal precision.
