### ISSUE TITLE
[Bug report] Cannot compile under docker bash

### ISSUE THREAD

**Issue by liujinhui1994** [apache/gravitino#2625]
### Version

main branch

### Describe what's wrong

./gradlew clean build -PjdkVersion=11 -x test
Cannot compile under docker bash。

### Error message and/or stacktrace

/gradle/wrapper/gradle-wrapper,jarcontent,com/gradle/gradle/v8.2-bin.zipcurl: (3)URL using bad/illegal format or missing URLError: Could not find or load main class org.gradle.wrapper,GradleWrapperMain

### How to reproduce

master or 0.4.0

**Comment by jerryshao** [comment]
Close as cannot be reproduced.
