### ISSUE TITLE
[EPIC] Container management improvement for integration tests

### ISSUE THREAD

**Issue by unknowntpo** [apache/gravitino#2765]
### Describe the proposal

Currently, the integration tests of Gravitino uses many containers, and we want to use ContainerSuit to manage them, but there are some points that we can improve.

Current design of ContainerSuit has implemented singleton, which means no matter how many tests we are running, same kind of container (e.g. Hive) will be run at most once.

Here’s a bug, [ContainerSuite.java](https://github.com/datastrato/gravitino/blob/main/integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/ContainerSuite.java#L58) implemented a singleton, but `startHiveContainer` , `startTrinoContainer` doesn’t determine whether container has already started or not, so this might cause multiple invokation of methods like `startTrinoContainer` unpredicable, these methods needs to be singleton, too, and when other test case invoke these singleton method, then needs to wait until this method is done.

Another problem is, their are some test cases that haven’t been placed in ContainerSuit, e.g. MysqlContainer in [AuditCatalogMysqlIT.java](https://github.com/datastrato/gravitino/issues/AuditCatalogMysqlIT.java), we need to put them back to `ContainerSuit`.

And these modification might cause a problem, because they are connected to same database concurrently, they needs to be separated to different database which name is the method name of test case. To avoid wrongly hard coded method name, we may need to get class name from Class, and extract this behavior into a method.

thanks @xunliu for pointing out these problems.

### Task list

- [x] #2807
- [x] #2793 
- [x] #2832 
- [x] #3066

**Comment by mchades** [comment]
> make methods in ContainerSuit singleton.

Do you have time to start this first recently?

**Comment by mchades** [comment]
I suspect that the failure of the Hive container to start in CI is related to it being started multiple times, so I prioritized fixing this issue by #2794 

You can move on to other fixes when you have time.

BTW, I think there is another CI improvement that can be considered, which is to upload the process logs in the container (such as Hive, HDFS, etc.) after a CI failure.

**Comment by unknowntpo** [comment]
> > make methods in ContainerSuit singleton.
> 
> Do you have time to start this first recently?

@mchades  sorry for late reply, I saw you and @jerryshao has merged a related commit https://github.com/datastrato/gravitino/pull/2794
,  did it fix this issue ?

**Comment by mchades** [comment]
Close this issue because it seems that all related subtasks have been completed.
