### ISSUE TITLE
[Improvement] Test all combinations of Backend Integration Test at once

### ISSUE THREAD

**Issue by unknowntpo** [apache/gravitino#2926]
### What would you like to be improved?

Currently, we run backend integration tests with these (testMode, backend) combinations:

- embedded, jdbcBackend
- embedded, kvBackend
- deploy, jdbcBackend
- deploy, kvBackend

But this will cause CI pipeline to run 12 times because we also have to test 3 Java versions (8, 11, 17),
which is a big waste of time.

And even more, at local test with IDE like Intellij, we can only run tests with default config: `embedded, kvBackend`.
For those who doesn't familiar with Integration test configurations, they will find their code failed at CI with config like `deploy, jdbcBackend` and can't reproduce locally.

### How should we improve?

Continue from the discussion at [here](https://github.com/datastrato/gravitino/pull/2813#discussion_r1563971097) in #2813 .

we could modify startIntegrationTest method to:

```
@ParameterizedTest
    @CsvSource({
        "embedded, jdbcBackend",
        "embedded, kvBackend",
        "deploy, jdbcBackend",
        "deploy, kvBackend"
    })
    void startIntegrationTest(String testMode, String backend) {
```

But I found that `@BeforeAll` seems to be executed only one time.

So my question is: Is it a way to parameterize beforeAll ?

After I googled it and found this comments, but I don't know it works or not.

https://github.com/junit-team/junit5/issues/3157#issuecomment-1435009129

c.c. @yuqi1129, @mchades

**Comment by mchades** [comment]
I will close this issue since the kvBackend is deprecated now.  You can open a new issue if necessary
