### ISSUE TITLE
[Improvement] Configs.java interface has no interface definitions just constants

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#3029]
### What would you like to be improved?

Configs.java interface has no interface definitions just constants.

### How should we improve?

Use a final class with a private constructor instead.

**Comment by lw-yang** [comment]
I'll be adding some new configurations recently,  I would like to refactor it together

**Comment by shaofengshi** [comment]
Assign to lw-yang so that won't be conflict with other guys.

**Comment by justinmclean** [comment]
@lw-yang do you still want to work on this?

**Comment by lw-yang** [comment]
Yes, i will complete it this week.

**Comment by lw-yang** [comment]
It has been resolved by https://github.com/apache/gravitino/pull/3404

**Comment by justinmclean** [comment]
Closing as it has been done
