### ISSUE TITLE
[Bug report] Rename mysql table through api, if new name included uppercase, api response NoSuchTableException.

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#3047]
### Version

main branch

### Describe what's wrong

<img width="1078" alt="image" src="https://github.com/datastrato/gravitino/assets/154112360/f17fff23-a112-4636-8cff-0fd61ad5cebd">

### Error message and/or stacktrace

N/A

### How to reproduce

1.Rename mysql table through api
2.New name included uppercase
3.API response NoSuchTableException ,but actually table name had been renamed to new name (convert to lower-case).

**Comment by jerryshao** [comment]
@mchades please check this issue.

**Comment by danhuawang** [comment]
mysql configuration:
docker run -p 3306:3306 --name mysql --detach -e MYSQL_ROOT_PASSWORD="mysql" -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=mydb -d mysql/mysql-server:latest --lower_case_table_names=1 --init-connect='GRANT CREATE USER ON *.* TO 'root'@'%';FLUSH PRIVILEGES;'

**Comment by danhuawang** [comment]
> Why are you set `lower_case_table_names=1`?
> 
> The process of renaming a table is to first alter and then load. Currently, **jdbc-mysql-catalog assumes that the underlying MySQL is case-sensitive in table name**, but your MySQL service is configured with `lower_case_table_names=1`. This results in using uppercase names during loading, causing an error indicating that the table does not exist, when in fact the table has been successfully modified to lowercase.
> 
> In most cases, [MySQL document](https://dev.mysql.com/doc/refman/8.3/en/identifier-case-sensitivity.html) recommends using the default configuration(0 on Unix, 1 on Windows, 2 on macOS):
> 
> > If you are using MySQL on only one platform, you do not normally have to use a [lower_case_table_names](https://dev.mysql.com/doc/refman/8.3/en/server-system-variables.html#sysvar_lower_case_table_names) setting other than the default.
> 
> Although [MySQL document](https://dev.mysql.com/doc/refman/8.3/en/identifier-case-sensitivity.html) says:
> 
> > [lower_case_table_names](https://dev.mysql.com/doc/refman/8.3/en/server-system-variables.html#sysvar_lower_case_table_names) can only be configured when initializing the server. Changing the [lower_case_table_names](https://dev.mysql.com/doc/refman/8.3/en/server-system-variables.html#sysvar_lower_case_table_names) setting after the server is initialized is prohibited.
> 
> and we can make case-sensitivity a configurable option for the catalog to solve this problem, it will make the code more complex and is not necessary in most cases. Therefore, I suggest setting `lower_case_table_names` to `0` in your tests and do the code changes when encountered in a production environment. WDYT? @danhuawang @jerryshao

Sure. I will apply changes on testing and create an issue to track [Improvement] Add --lower_case_table_names=0 parameter for mysql db instance in testing environment. #147

Reopen it if it is required in a production environment
