### ISSUE TITLE
[Subtask] Supports partition management in Doris catalog

### ISSUE THREAD

**Issue by zhoukangcn** [apache/gravitino#3064]
### Describe the subtask

Supports partition management in Doris catalog

### Parent issue

#1575

**Comment by yuqi1129** [comment]
@zhoukangcn 
Do you have time to work on this?

**Comment by mchades** [comment]
@xiaozcy Please leave a message here so I can assign this issue to you.

**Comment by xiaozcy** [comment]
@mchades Done.
