### ISSUE TITLE
[Improvement] Add missing @deprecated Javadoc tag in GravitinoClientBase.java

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#3084]
### What would you like to be improved?

The deprecated tag can be used to explain why it was deprecated.

### How should we improve?

Add @deprecated tag and description as to why it was deprecated.

**Comment by justinmclean** [comment]
@jtao1 do you still want to work on this?

**Comment by jtao1** [comment]
Sorry, I forgot I was assigned to this issue. I have unassigned myself for now
