### ISSUE TITLE
[Bug report] spark connector create hive table from RDD failed for partition schema check

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#3114]
### Version

main branch

### Describe what's wrong

spark connector create hive table from dataframe failed for partition schema check, because `favorite_color` is not the last column in dataframe.

### Error message and/or stacktrace

```
java.lang.IllegalArgumentException: Failed to operate table(s) [users_partitioned_bucketed] operation [CREATE] under schema [default], reason [The partition field must be placed at the end of the columns in order]
java.lang.IllegalArgumentException: The partition field must be placed at the end of the columns in order
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
	at com.datastrato.gravitino.catalog.hive.HiveCatalogOperations.validatePartitionForCreate(HiveCatalogOperations.java:569)
	at com.datastrato.gravitino.catalog.hive.HiveCatalogOperations.createTable(HiveCatalogOperations.java:676)
	at com.datastrato.gravitino.catalog.TableOperationDispatcher.lambda$createTable$7(TableOperationDispatcher.java:160)

```

### How to reproduce

```scala
val usersDF = spark.read.load("examples/src/main/resources/users.parquet")
usersDF.write.partitionBy("favorite_color").bucketBy(42, "name").saveAsTable("users_partitioned_bucketed")
```
please refer https://spark.apache.org/docs/3.1.1/sql-data-sources-load-save-functions.html

**Comment by jerryshao** [comment]
How does Spark itself handle this problem?

**Comment by FANNG1** [comment]
For normal Hive table, Spark add extra `Project` plan after the data query plan to reorder columns.  I just see the result and have not found where added the `Project` plan.  For datasourceV2, no extra plan is added, maybe because Iceberg like systems doesn't need to recorder columns.

**Comment by FANNG1** [comment]
close it as not strong requirement in real enviroment.
