### ISSUE TITLE
[Bug report] The link of `Iceberg table properties` in lakehouse-iceberg-catalog doc is no longer working

### ISSUE THREAD

**Issue by lw-yang** [apache/gravitino#3185]
### Version

main branch

### Describe what's wrong

The link of `Iceberg table properties` in lakehouse-iceberg-catalog doc is no longer working

the doc https://iceberg.apache.org/docs/1.3.1/configuration/ in iceberg is not support

### Error message and/or stacktrace

![image](https://github.com/datastrato/gravitino/assets/23456873/ffb75d34-b9b4-4816-8cbf-3bf321379374)

### How to reproduce

visit https://iceberg.apache.org/docs/1.3.1/configuration/

![image](https://github.com/datastrato/gravitino/assets/23456873/49634920-b035-4315-a16c-177e9f3af78e)

**Comment by lw-yang** [comment]
@jerryshao should we use the iceberg latest version doc to avoid this?

**Comment by FANNG1** [comment]
> @jerryshao should we use the iceberg latest version doc to avoid this?

I think we could use the latest version URL, @lw-yang do you like to fix it?

**Comment by lw-yang** [comment]
@FANNG1 yeah, i would like to fix it
