### ISSUE TITLE
[Improvement] Support clean user,group and role in `RelationalGarbageCollector`

### ISSUE THREAD

**Issue by lw-yang** [apache/gravitino#3188]
### What would you like to be improved?

support clean user,group and role in `RelationalGarbageCollector`

**Comment by jerryshao** [comment]
@lw-yang can you please work on this when you have time? Thanks a lot.

**Comment by lw-yang** [comment]
@jerryshao Sure, it's on my schedule,  I will make sure to complete it by next week, thanks for the heads up
