### ISSUE TITLE
[Bug report] Can rename metalake when in simple name mode (which is default for playground)

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#3245]
### Version

main branch

### Describe what's wrong

You can rename the metalake and no error is given, even though the metalake name is specified in the configuration.

### Error message and/or stacktrace

Once renamed you get endless errors:
playground-trino       | 2024-05-02T06:26:33.045Z	INFO	gravitino-connector-schedule-0	stdout	2024-05-02 06:26:33 WARN  CatalogConnectorManager:116 - Metalake metalake_demo does not exist.

### How to reproduce

Start the playground and rename the mekalake.

**Comment by shaofengshi** [comment]
If change metalake name in the Gravitino server side, the trino side doesn't get that, it still uses the original name to connect with Gravitino, then the "Metalake does not exit" error be reported. I think this is expected.

To make it work, user need to update the metalake name in trino side, which is "/etc/trino/catalog/gravitino.properties" in the trino container, and then restart Trino to make it effective.

**Comment by justinmclean** [comment]
The UI makes it easy to change the name, editing should be disabled if using simple names. The playground doesn't include the Trino admin tools needed to restart Trino.

**Comment by jerqi** [comment]
You need to restart the Trino if you rename the metalake,  so this isn't an issue. We should close it.
