### ISSUE TITLE
[Improvement] Add a github action to support merge cherry-picked PR automatically

### ISSUE THREAD

**Issue by jerryshao** [apache/gravitino#3274]
### What would you like to be improved?

Currently, each cherry-picked PR should be approved and merged manually. This is not convenient as most of the review/check are already done in the original PR. We should simply merge it automatically after the CI is passed.

### How should we improve?

We should add a github action to merge the cherry-picked PR automatically.

**Comment by justinmclean** [comment]
Note this may not be allowed in ASF repos as only humans can commit

**Comment by mchades** [comment]
Is this still necessary?

**Comment by jerryshao** [comment]
It's not needed, I'm going to close it.
