### ISSUE TITLE
[Bug report] Hive catalog values are hidden

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#3280]
### Version

main branch

### Describe what's wrong

Hive catalog values are hidden:
<img width="394" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/6f4a4127-5deb-4a37-8d8c-73cb59ccd74f">

### Error message and/or stacktrace

N/A

### How to reproduce

Click view icon for a Hive catalog

**Comment by jerryshao** [comment]
What is the problem here? @justinmclean

**Comment by justinmclean** [comment]
You can't see the value of "gravitino.bypass.have.metastore.client.capability.check" or "metastore.uris"

**Comment by jerryshao** [comment]
I see.

@mchades please help to identify the issue here.

**Comment by justinmclean** [comment]
I guess that "gravitino.bypass.have.metastore.client.capability.check" is too long and hides the values. One solution would be to truncate keys to 20  to 30 characters (with the full key displaying on rollover)

**Comment by ch3yne** [comment]
> I guess that "gravitino.bypass.have.metastore.client.capability.check" is too long and hides the values. One solution would be to truncate keys to 20 to 30 characters (with the full key displaying on rollover)

<img width="384" alt="image" src="https://github.com/datastrato/gravitino/assets/17310559/03426d9e-bb16-435f-b873-298633cf2668">

Because the length is too long, you need to scroll to see the values ​​at the end.

**Comment by mchades** [comment]
Should we support automatic line breaks in UI properties display since this scrollbar may be too hidden?

**Comment by jerryshao** [comment]
@ch3yne Can you please think about how to improve this?

**Comment by ch3yne** [comment]
I think ellipses can be used to replace keys or values that exceed the visual area.
