### ISSUE TITLE
[Bug report] Apache Kafka topics are displayed in semi-random order

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#3281]
### Version

main branch

### Describe what's wrong

Topics are not ordered
<img width="281" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/ede1421d-1b42-416e-b35c-ea1d99191f20">
<img width="274" alt="image" src="https://github.com/datastrato/gravitino/assets/144504/d322a25a-5b3b-4458-be05-03b1d64dff94">

### Error message and/or stacktrace

N/A

### How to reproduce

Create a number of topics and see how they are ordered

**Comment by ch3yne** [comment]
This ordered list was obtained from the API. @mchades Please help to pay attention this issue.

**Comment by mchades** [comment]
It's the same question with #2623 ?

**Comment by mchades** [comment]
I will close this as it is a duplicate of #2623
