### ISSUE TITLE
[FEATURE] Add S3 support for Fileset Hadoop catalog

### ISSUE THREAD

**Issue by jerryshao** [apache/gravitino#3379]
### Describe the feature

Fileset is a new concept brought in 0.5.0 to manage the non-tabular data, the current implementation uses HCFS to manage the physical data. With HCFS, the Hadoop catalog should support different underlying storage, but currently we only verified local file system and HDFS.

In this issue, we should also support S3, to make the fileset hadoop catalog work with S3 object store.

### Motivation

The reason to support S3 is that it is vastly used on the public cloud, we should add this support anyway.

**Comment by zhoukangcn** [comment]
I think we can change this feature to `Support Object Store provided by Cloud Service`, so we can add subtask to support Azure Blob and Aliyun OSS

**Comment by jerryshao** [comment]
@xiaozcy can you please leave a message here, so I can assign the issue to you.

**Comment by xiaozcy** [comment]
> @xiaozcy can you please leave a message here, so I can assign the issue to you.

Sure.
