### ISSUE TITLE
[Bug report] Multiple issues encountered while running Gravitino on Win11

### ISSUE THREAD

**Issue by LanceHsun** [apache/gravitino#3443]
### Version

main branch

### Describe what's wrong

main branch

### Describe what's wrong
During the build process of the Gravitino project on Win11 system, the following issues were encountered:

1. **OpenAPI Validation Error**: The task `docs:lintOpenAPI` fails, reporting multiple OpenAPI documentation validation errors.
2. **Prettier Missing Issue**: The `prettier:fix` script was not recognized, requiring the addition of a `package.json` file and installation of Prettier.
3. **Apache Rat Unapproved Licenses**: Apache Rat audit failed, detecting 54 unapproved licenses.

### Error message and/or stacktrace

1. FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':docs:lintOpenAPI'.
> Process 'command 'F:\intern\datastrato\gravitino\docs\.gradle\nodejs\node-v20.9.0-win-x64\npx.cmd'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 8m 5s
176 actionable tasks: 165 executed, 5 from cache, 6 up-to-date

2. FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':web:prettierCheck'.
> Process 'command 'F:\intern\datastrato\gravitino\web\.gradle\pnpm\pnpm-v9.x\pnpm.cmd'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 9m 19s
222 actionable tasks: 107 executed, 60 from cache, 55 up-to-date

3. FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rat'.
> A failure occurred while executing org.nosphere.apache.rat.RatWork
   > Apache Rat audit failure - 54 unapproved licenses
        See file:///F:/intern/datastrato/gravitino/build/reports/rat/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 9m 33s
219 actionable tasks: 89 executed, 75 from cache, 55 up-to-date

### How to reproduce

1. Clone the Gravitino project repository.
2. Navigate to the project root directory.
3. Run ./gradlew clean build -x test and observe the docs:lintOpenAPI task failure with validation errors.
4. Run ./gradlew clean build -x test -x docs:lintOpenAPI and observe the Prettier missing issue.
5. After fixing the Prettier issue, run ./gradlew clean build -x test -x docs:lintOpenAPI and observe the Apache Rat unapproved licenses issue.

**Comment by jerryshao** [comment]
Hi @LanceHsun Thanks a lot for your reporting, I think currently we don't support Windows platform, it might have several issues using Windows platform to build. It would be nice if you can make it work on Window platform.

**Comment by jerryshao** [comment]
Hi @LanceHsun I think building/running on Windows WSL is generally OK now, right? I'm going to close this issue.
