### ISSUE TITLE
[Improvement] revisit all the purgeXXX implementations to have a consistent behavior

### ISSUE THREAD

**Issue by mchades** [apache/gravitino#3685]
### What would you like to be improved?

we should revisit all the `purgeTable` and `purgePartition` implementations to make sure that:

1. return True if the target was purged, false if the target does not exist
2. thrown `UnsupportedOperationException` If target purging is not supported

### How should we improve?

see above

**Comment by zivali** [comment]
@mchades May I take a look into this one? I think we can refer to purgeTable in RelationalCatalog as the desired behavior
https://github.com/datastrato/gravitino/blob/main/clients/client-java/src/main/java/com/datastrato/gravitino/client/RelationalCatalog.java#L221-L243

**Comment by mchades** [comment]
> @mchades May I take a look into this one? I think we can refer to purgeTable in RelationalCatalog as the desired behavior https://github.com/datastrato/gravitino/blob/main/clients/client-java/src/main/java/com/datastrato/gravitino/client/RelationalCatalog.java#L221-L243

The behavior of `purgeTable` in `RelationalCatalog` is:

- thrown UnsupportedOperationException If target purging is not supported
- return true if the table is purged successfully, false otherwise

One issue with this behavior is that if return false, the client will not be able to obtain the specific reason for failure. 

Can you refer to the behavior of dropTable and then think about the behavior of purge? @zivali

**Comment by zivali** [comment]
Got it. Thank you for the clarification! :) 
- false should be returned only if the target does not exist (NoSuchTableException, NoSuchSchemaException or NoSuchEntityException) 
- UnsupportedOperationException if catalog doesn't support
- All other exceptions should be thrown

Also, I didn't find detail implementations of `purgePartition` in the code. Is it still work in progress?

**Comment by mchades** [comment]
> Got it. Thank you for the clarification! :)
> 
> * false should be returned only if the target does not exist (NoSuchTableException, NoSuchSchemaException or NoSuchEntityException)
> * UnsupportedOperationException if catalog doesn't support
> * All other exceptions should be thrown

This proposal LGTM 

> Also, I didn't find detail implementations of `purgePartition` in the code. Is it still work in progress?

It's not started yet. Currently, we have already supported partition operations in the Hive catalog, but we have not yet implemented purge partition. If you are interested, you can start researching it first.
