### ISSUE TITLE
[Subtask] Update Python client to align with the Java client API

### ISSUE THREAD

**Issue by shaofengshi** [apache/gravitino#3732]
### Describe the subtask

After the refactoring work in Java client is done (https://github.com/datastrato/gravitino/issues/3626), the Python client should also get updated to align with the Java API.

### Parent issue

#3626

**Comment by shaofengshi** [comment]
@LanceHsun Lance, would you like to take this?

**Comment by LanceHsun** [comment]
> @LanceHsun Lance, would you like to take this?

Hi Shaofeng, yes, I have already assigned it to me. Thank you!

**Comment by shaofengshi** [comment]
Reopen this as there are other on-going tasks being made by Lance and Tim.
