### ISSUE TITLE
[Subtask] support partition event for event listener

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#3737]
### Describe the subtask

Generate partition events when do partition operations. please refer to other event implement like #2891,  
1. create a `PartitionEventDispatcher` in `GravitinoEnv`, which hacks partition operation and generate event to event listener. the system will auto inject  `PartitionEventDispatcher` to `PartitionOperations`
2. create corresponding event like `addPartitionEvent` `getPartitionEvent`
3. add test , please refer to `TestCatalogEvent` 

### Parent issue

#2233

**Comment by kiratkumar47** [comment]
Could you please assign this to me?

**Comment by FANNG1** [comment]
> Could you please assign this to me?

sure, thanks for taking this.

**Comment by FANNG1** [comment]
@kalencaya , is there any progress ?

**Comment by kiratkumar47** [comment]
Hi @FANNG1,

I started working on it, but due to some personal reasons, I can't continue. Sorry for the late reply.

**Comment by FANNG1** [comment]
> Hi @FANNG1,
> 
> I started working on it, but due to some personal reasons, I can't continue. Sorry for the late reply.

The feature is supposed to be released in 0.6 in about next two weeks, do you have enough time to do this?

**Comment by kiratkumar47** [comment]
> > Hi @FANNG1,
> > I started working on it, but due to some personal reasons, I can't continue. Sorry for the late reply.
> 
> The feature is supposed to be released in 0.6 in about next two weeks, do you have enough time to do this?

I won't be able to complete this in 2 weeks.

**Comment by FANNG1** [comment]
@kiratkumar47 do you mind other developers to do this issue, mainly for the time

**Comment by kiratkumar47** [comment]
> @kiratkumar47 do you mind other developers to do this issue, mainly for the time

@FANNG1 Sure.

**Comment by FANNG1** [comment]
welcome other guys to taking this

**Comment by ian910297** [comment]
@FANNG1 May I take this?

**Comment by FANNG1** [comment]
> @FANNG1 May I take this?

This feature is supposed to be released in next week, I'm not sure whether there are enough time for you.

**Comment by ian910297** [comment]
Hi @FANNG1,

Thank you for reminding me about this deadline.

I need 1 day to assess if I can meet the deadline. I'll have a version by tomorrow night (2024/07/07 night GMT+8) with a PR.
Review my progress then. I'll let you know if I can't make it.

**Comment by FANNG1** [comment]
> Hi @FANNG1,
> 
> Thank you for reminding me about this deadline.
> 
> I need 1 day to assess if I can meet the deadline. I'll have a version by tomorrow night (2024/07/07 night GMT+8) with a PR. Review my progress then. I'll let you know if I can't make it.

ok, please go ahead

**Comment by ian910297** [comment]
Hi @FANNG1 ,
Not yet complete enough to submit a PR, [this commit](https://github.com/ian910297/gravitino/commit/1118d5bb6f05de155f30bb15678b9cdbf5176283) is my current progress.

Done:
1. Based on the Catalog Event and PartitionDispatcher, I have initially implemented the PartitionEventListener, and the build passes.

Todo:
1. Add test method
2. Verify functionailty
* Is there a need to use namespace in event? Currently, **I haven't utilized namespaces in Add/Get/Drop Events** the same way they are used in Catalog Event. Instead, I'm simply referencing the parameters of the **PartitionDispatcher** abstract method to populate the values.
* For the **listPartitionEvent**, I'm unsure whether to provide different parameters for **listPartitions** and **listPartitionNames**

**Comment by FANNG1** [comment]
> Is there a need to use namespace in event? Currently, I haven't utilized namespaces in Add/Get/Drop Events the same way they are used in Catalog Event. Instead, I'm simply referencing the parameters of the PartitionDispatcher abstract method to populate the values.

Sorry, I couldn't get your point, maybe you could propose a draft PR, we could discuss on the PR.

> For the listPartitionEvent, I'm unsure whether to provide different parameters for listPartitions and listPartitionNames.

We should provide `ListPartitionEvent` and `ListPartitionNames` event, seems no need to provide extra different parameters. We don't save it in the event because there may be millions of partitions.

**Comment by ian910297** [comment]
@FANNG1 Already created a draft PR
