### ISSUE TITLE
[Improvement] Support OAuth2 auth in PyGVFS

### ISSUE THREAD

**Issue by xloya** [apache/gravitino#3758]
### What would you like to be improved?

Support OAuth2 authentication in PyGVFS so that it can interact with the Gravitino server. This is supported in Java GVFS and we should also support it in PyGVFS.

**Comment by jerryshao** [comment]
It should already be supported, right? @xloya

**Comment by xloya** [comment]
> It should already be supported, right? @xloya

Nope, we only support the Python client through Oauth2 authentication to access the server: #4011. Supporting for Oauth2 authentication in PyGVFS still requires some codes.

**Comment by jerryshao** [comment]
I see, thanks.
