### ISSUE TITLE
[Subtask] Fix missing-timeout Pylint rule for client-python

### ISSUE THREAD

**Issue by noidname01** [apache/gravitino#3765]
### Describe the subtask

* Define a reasonable timeout for `request.get` to prevent program from hanging indefinitely

### Parent issue

#3560

**Comment by adheeshsharma19** [comment]
Hi, can I work on this ?
Also, which file under client-python requires timeout to be added.

**Comment by noidname01** [comment]
@adheeshsharma19 Sure, you're welcome.😊
It's in `tests/integration/integration_test_env.py`, actually you can remove `missing-timeout` from disable section in `pylintrc` and run `./gradlew clients:client-python:pylint`, it should log where the problem is.

**Comment by adheeshsharma19** [comment]
Thanks

**Comment by adheeshsharma19** [comment]
Have raised a PR :https://github.com/datastrato/gravitino/pull/3810

**Comment by liuchunhao** [comment]
Hi, I'd like to work this. Could you assign it to me ? Thank you.

**Comment by xunliu** [comment]
@liuchunhao Yes, I assign it to you.
