### ISSUE TITLE
[Improvement] A test case is needed  to test the 'list-all-tables '  hive catalog property.

### ISSUE THREAD

**Issue by mygrsun** [apache/gravitino#3783]
### What would you like to be improved?

In the https://github.com/datastrato/gravitino/pull/3703 pr，lack of the test case corresponding to  the 'list-all-tables '  hive catalog property.

### How should we improve?

It's recommended to add a test in CatalogHiveIT

**Comment by LiuQhahah** [comment]
Hi @mygrsun 
The issue seems to have been solved.
please close it.
thanks

**Comment by chenyuan99** [comment]
I dont think it is reolved, could you assign it to me?

**Comment by chenyuan99** [comment]
Thanks!
