### ISSUE TITLE
[Improvement] doc: add Trino worker configuration example in Trino installation doc

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#3790]
### What would you like to be improved?

provide worker config file example, because "catalog.store=file" cannot be added to worker node config.properties like the coordinator node
```
coordinator=false
http-server.http.port=8080
query.max-memory=4GB
query.max-memory-per-node=1GB
discovery.uri=http://trino:8080
catalog.management=dynamic
```

### How should we improve?

add worker config file example:
```
coordinator=false
http-server.http.port=8080
query.max-memory=4GB
query.max-memory-per-node=1GB
discovery.uri=http://trino:8080
catalog.management=dynamic
```

**Comment by diqiu50** [comment]
The docs are already updated. Now we don't need config `catalog.store=file` on the config files. "catalog.store=file" does not configure by worker, that's a Trino bug, it fix in the other versions. 

@danhuawang We can close the issue.

**Comment by danhuawang** [comment]
> The docs are already updated. Now we don't need config `catalog.store=file` on the config files. "catalog.store=file" does not configure by worker, that's a Trino bug, it fix in the other versions.

Sure. I closed it.
