### ISSUE TITLE
[Bug report] Validate methods of request in client-python are not correct

### ISSUE THREAD

**Issue by featherchen** [apache/gravitino#3818]
### Version

main branch

### Describe what's wrong

In client-python/gravitino/dto/requests, the Validate methods in each class are designed to ensure attributes are not None. However, in some classes, attributes are allowed to be None, which is incorrect.

Additionally, the Validate methods have been implemented in two ways: using assert and raise. Although they are functionally equivalent, unifying the implementation to use a single approach will improve code quality and consistency.

### Error message and/or stacktrace

![Screenshot from 2024-06-07 16-07-46](https://github.com/datastrato/gravitino/assets/57944334/9a85c88d-50f8-4835-9d97-5a7b44ecb057)

raise approach
![Screenshot from 2024-06-07 16-11-41](https://github.com/datastrato/gravitino/assets/57944334/ee5ec91a-7c4a-4389-90d4-5329fdbad3b3)

### How to reproduce

main branch

**Comment by jerryshao** [comment]
@jingjia88 can you please leave a message here, so I can assign the issue to you.

**Comment by jingjia88** [comment]
@jerryshao Sure~ Thanks!
