### ISSUE TITLE
[Bug report] Chrome failed to start during MetalakePageTest on WSL2

### ISSUE THREAD

**Issue by LanceHsun** [apache/gravitino#3927]
### Version

main branch

### Describe what's wrong

During the execution of the MetalakePageTest on the WSL2 environment, the Chrome browser failed to start, resulting in the test failing. The error message indicates that Chrome exited abnormally and the DevToolsActivePort file does not exist. This issue prevents the integration tests from running successfully on WSL2.

### Error message and/or stacktrace

org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/lance/gravitino/integration-test/build/chrome/chrome-linux/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-67Q22DQ', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.153.1-microsoft-standard-WSL2', java.version: '1.8.0_412'
Driver info: driver.version: ChromeDriver
remote stacktrace: #0 0x55ceec001869 <unknown>
#1 0x55ceebf9c383 <unknown>
#2 0x55ceebd7eca3 <unknown>
#3 0x55ceebda2286 <unknown>
#4 0x55ceebd9d7cd <unknown>
#5 0x55ceebdd711d <unknown>
#6 0x55ceebdd1963 <unknown>
#7 0x55ceebda7e36 <unknown>
#8 0x55ceebda8fd5 <unknown>
#9 0x55ceebfc9f90 <unknown>
#10 0x55ceebfdbd80 <unknown>
#11 0x55ceebfdba8c <unknown>
#12 0x55ceebfdc302 <unknown>
#13 0x55ceebfcb2db <unknown>
#14 0x55ceebfdc586 <unknown>
#15 0x55ceebfbd663 <unknown>
#16 0x55ceebff3968 <unknown>
#17 0x55ceebff3af3 <unknown>
#18 0x55ceec00dcee <unknown>
#19 0x7fb55f6ebac3 <unknown>
#20 0x7fb55f77d850 <unknown>
![Screenshot 2024-06-20 175721](https://github.com/datastrato/gravitino/assets/103924768/2546af1f-5830-4b13-bfb2-7467fe749c96)

### How to reproduce

1. Ensure you are running the latest code from the main branch.
2. Set up a WSL2 environment with the necessary dependencies.
3. Run the integration tests using the following command:
   ./gradlew :integration-test:test --tests "com.datastrato.gravitino.integration.test.web.ui.MetalakePageTest"
4. Observe the error during the initialization of the Chrome browser.

### Additional context

The issue seems to be related to the Chrome browser's compatibility with the WSL2 environment. It is necessary to investigate whether this is a configuration issue or if additional steps are needed to ensure compatibility.

**Comment by jerryshao** [comment]
Hi @LanceHsun I'm going to close this, as we currently doesn't fully support Windows, and it is hard for us to reproduce.
