### ISSUE TITLE
[Bug report] jdbc-postgresql/00006_datatype.sql under catalog pg failed.

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#3930]
### Version

main branch

### Describe what's wrong

pg:jdbc-postgresql/00006_datatype.sql, FAIL, 0.035, Execute sql in the tester jdbc-postgresql/00006_datatype.sql under catalog pg failed.

### Error message and/or stacktrace

pg:jdbc-postgresql/00006_datatype.sql, FAIL, 0.035, Execute sql in the tester jdbc-postgresql/00006_datatype.sql under catalog pg failed.
Sql:
CREATE SCHEMA gt_postgresql.gt_db1;
Expect:
CREATE SCHEMA
Actual:
Query 20240620_195037_00306_sm8tb failed: line 1:1: Schema 'gt_postgresql.gt_db1' already exists
LINE 1: CREATE SCHEMA gt_postgresql.gt_db1
        ^

### How to reproduce

https://github.com/datastrato/gravitino-test/actions/workflows/test-on-eks.yml

**Comment by diqiu50** [comment]
This error is caused by the previous step's error of the #3929.

**Comment by diqiu50** [comment]
@danhuawang Please close the issue after you check.

**Comment by danhuawang** [comment]
> @danhuawang Please close the issue after you check.

Already fixed. Closed.
