### ISSUE TITLE
[Subtask] Design Audit Log framework

### ISSUE THREAD

**Issue by hanwxx** [apache/gravitino#3973]
### What would you like to be improved?

Based on the metadata change message, in our company has following consumption scenarios:
1. Data governance:  based on job lineage, metadata change messages will be sent to affected job owners, so they can decide whether to adjust jobs
2. Metadata search:  After processing, the medata data will be imported into ES to provide complex search capabilities.
3. Audit scenario: the change operation is stored persistently for audit.

### How should we improve?
So i want to add a audit listenr, listening to the change event, then send the message to the external MQ ( like RocketMQ）
_No response_

**Comment by FANNG1** [comment]
seems reasonable to add a event consumer to deliver events to message queues,  Besides this,  could  event system satisfy your requirement?

**Comment by hanwxx** [comment]
Get it，event system can meet the requirement

**Comment by hanwxx** [comment]
This is design document. Please review it
https://docs.google.com/document/d/1qyphXC9xLsg2mcKhHLxqbCudUqeEpCZDKvQo-ztY0HE/edit?usp=sharing
