### ISSUE TITLE
[Improvement] Refactor Error Handling in client-python

### ISSUE THREAD

**Issue by noidname01** [apache/gravitino#4012]
### What would you like to be improved?

* Currently, the error handling structure is hard for custom error handling, like `OAuth2TokenProvider` might have different type of errors in one error status code.

### How should we improve?

* Based on `client-java`, define error handling structure and add missing unittests.

**Comment by rich7420** [comment]
Hi @noidname01 , Can you please provide more details about this issue?

**Comment by noidname01** [comment]
@rich7420, there is `ErrorHandler` and `ErrorHandlers` in `client-java`, I think `client-python` should also have these error handlers. We can pass these error handler when we call API(ex. get, post, etc) in `http_client.py`. 
I think you can create this framework, then we can open other PRs to implement each error handler.

**Comment by noidname01** [comment]
@rich7420 @ian910297 I'm going to solve this issue, I think you can help me to review the code after I raise PR and you guys can keep working based on this.
