### ISSUE TITLE
[Improvement] Version manange for H2 database like MySQL

### ISSUE THREAD

**Issue by yuqi1129** [apache/gravitino#4022]
### What would you like to be improved?

DDL and table definition have used version management in the MySQL database, H2 database should also add it. 

<img width="649" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/d6bae8e3-822d-4e19-97d6-2eb6b4030197">

### How should we improve?

Change file `schema-h2.sql` to `schema-0.6.0-mysql.sql` and other necessary changes.

**Comment by lw-yang** [comment]
@yuqi1129 We will support the h2 database in version 0.6.0. I think we only needs to change the file `schema-h2.sql` to `schema-0.6.0-mysql.sql`, and there's no need for other upgrade operations.

**Comment by yuqi1129** [comment]
I recall that you used the procedure to insert some data to MySQL. Is it not necessary for the H2 database?

**Comment by lw-yang** [comment]
@yuqi1129 We use procedure to initialize data in MySQL because there is already some existing metalakes in MySQL. 
However, h2 only started supporting in version 0.6.0, there is no existing metalake in the database, so there is no need for initialization.

**Comment by yuqi1129** [comment]
OK, please go ahead.

**Comment by yuqi1129** [comment]
@lw-yang 
Please refer to Apache Hive's handling of schema upgrades for derby. 
https://github.com/apache/hive/tree/branch-3/metastore/scripts/upgrade/derby
