### ISSUE TITLE
[Improvement] Git ignore file `version.ini` 

### ISSUE THREAD

**Issue by yuqi1129** [apache/gravitino#4023]
### What would you like to be improved?

After we run test locally, there will be some files that have not been cleaned up , such as 
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        clients/client-python/version.ini
        data/

```

we better put them into `.gitignore` and neglect them

### How should we improve?

Add the following to `.gitignore`
```
clients/client-python/version.ini
data
```

**Comment by justinmclean** [comment]
fixed by #3953
