### ISSUE TITLE
Update the package name to use `org.apache.gravitino`

### ISSUE THREAD

**Issue by jerryshao** [apache/gravitino#4036]

**Comment by rich7420** [comment]
I’m interested in working on this issue. Can you please provide more details about this issue?

**Comment by jerryshao** [comment]
The current package name is "com.datastrato.gravitino.xxx", we need to change to "org.apache.gravitino.xxx" in everywhere, like java/python code, scripts, documents.

**Comment by jerryshao** [comment]
You can go ahead, after the PR is merged, I will assign the issue to you.

**Comment by rich7420** [comment]
No problem. thank you for your feeback.

**Comment by rich7420** [comment]
@jerryshao  hello , after I changed all the "com.datastrato.gravitino.xxx" to "org.apache.gravitino.xxx" , it came out when I ran `./gradlew build` . What can I improve this?
![Snipaste_2024-07-03_22-23-55](https://github.com/apache/gravitino/assets/101171023/92a137f2-f112-4897-b59a-3583c5ffd2bc)

**Comment by jerryshao** [comment]
I think you should grep all the file contents as well as the file name to see if it is modified. You must miss something, for example like service loader file.

**Comment by yuqi1129** [comment]
@rich7420 
If the issue still persists, please push your branch to Github and we will help to check it.

**Comment by rich7420** [comment]
@yuqi1129 Ok! Thank you for your feedback.
