### ISSUE TITLE
[Bug report] list-table api is very slow when table quantity is very large

### ISSUE THREAD

**Issue by mygrsun** [apache/gravitino#4089]
### Version

main branch

### Describe what's wrong

Through my test,I found that list-table will takes 300s when a schema has 5000 tables .
I analysis the code and add some logs ，then found is the reason for calling the  getTableObjectsByName interface.
listtable use the getTableObjectsByName .this metatore interface is very slow.
<img width="877" alt="image" src="https://github.com/apache/gravitino/assets/4070282/3cb36f3e-3438-4713-aaa3-435ea38a3780">

### Error message and/or stacktrace

I add some logs at 3 positions.
<img width="890" alt="image" src="https://github.com/apache/gravitino/assets/4070282/e5aa4ae4-4659-47d5-9024-8f74afc5d535">

the result is:

<img width="1154" alt="image" src="https://github.com/apache/gravitino/assets/4070282/bdbe35f0-95e0-4b4d-b04a-32b7465d868b">

### How to reproduce

add 5000 tables to one schema

**Comment by mchades** [comment]
Can you provide the direct query time for HMS without Gravitino?

**Comment by mygrsun** [comment]
> Can you provide the direct query time for HMS without Gravitino?

we have tested id。 when I excute "show tables" in hive
 beeline and sprark .it is very fast.
I gusess hiveserver2 don't use this getTableObjectsByName  interface .because 'show tables' just return table names.

**Comment by mchades** [comment]
`time1` and `time2` do not seem to appear in the picture?

**Comment by mygrsun** [comment]
> `time1` and `time2` do not seem to appear in the picture?

sorry, i will send you a new one

**Comment by mygrsun** [comment]
> `time1` and `time2` do not seem to appear in the picture?

<img width="1301" alt="image" src="https://github.com/apache/gravitino/assets/4070282/d498e0cd-609f-4511-ba9d-f339140616ea">

**Comment by mygrsun** [comment]
<img width="1081" alt="image" src="https://github.com/apache/gravitino/assets/4070282/e73d8f80-a88e-40cd-8e42-0aafe1d27343">

I have tryed the listTableNamesByFilter inteface to filter iceberg table。It is a feasible approach.
 but I did not pay attention to filter the manager and external table，I dont know the point of filtering  manager and external table.

so, please check this way.
if it is acceptable ,I can submit a pr.

**Comment by mchades** [comment]
> <img alt="image" width="1081" src="https://private-user-images.githubusercontent.com/4070282/346411226-e73d8f80-a88e-40cd-8e42-0aafe1d27343.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MDg0NDgsIm5iZiI6MTcyMDQwODE0OCwicGF0aCI6Ii80MDcwMjgyLzM0NjQxMTIyNi1lNzNkOGY4MC1hODhlLTQwY2QtOGU0Mi0wYWFmZTFkMjczNDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDhUMDMwOTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjE1NGEwZmRhNjE1OWQ4ZWZmNmQ5ZGNiNGNhMDliMDM4Mjk2MmY5NmQ1NzdkMzNlMWIyNGYyNzY3MTJkMGNhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xvWkcpBttbXJuY1NFOnObZ0P6NZM30g5RyfRNsIik2k">
> I have tryed the listTableNamesByFilter inteface to filter iceberg table。It is a feasible approach. but I did not pay attention to filter the manager and external table，I dont know the point of filtering manager and external table.
> 
> so, please check this way. if it is acceptable ,I can submit a pr.

Great! I think we can work on this way. WDYT? @jerryshao @FANNG1

**Comment by FANNG1** [comment]
> Great! I think we can work on this way. WDYT? @jerryshao @FANNG1

I think it's ok, because this method seems extensible and not only works for filter Iceberg tables.

**Comment by mchades** [comment]
Hi @mygrsun , is there any progress? Can I assign this issue to you?
