### ISSUE TITLE
[Improvement] Replace all assert in client-python

### ISSUE THREAD

**Issue by noidname01** [apache/gravitino#4100]
### What would you like to be improved?

* Currently, `assert` is widely used in `client-python`, which throws `AssertionError`
* Because of #4012 , the exception we used in `client-python` can be unified, and all `assert` can be replaced with defined exception.

### How should we improve?

* Replace all `assert` with defined exception.

**Comment by shaofengshi** [comment]
+1 good suggestion

**Comment by jerryshao** [comment]
@jingjia88 can you please leave a message here, so I can assign the issue to you.

**Comment by jingjia88** [comment]
@jerryshao Sure～Thanks!
