### ISSUE TITLE
Support for other JDBC backends

### ISSUE THREAD

**Issue by chanjaljayaram** [apache/gravitino#4101]
### What would you like to be improved?

Support for other JDBC bakends.

### How should we improve?

Support for other JDBC bakends like Postgres and Oracle would be great as MySQL is not approved by our security.

**Comment by justinmclean** [comment]
I assume you mean MySQL is not approved by your security?

**Comment by chanjaljayaram** [comment]
Yes, that is correct.

**Comment by yuqi1129** [comment]
@chanjaljayaram 
Thank you for your feedback. We will discuss the necessity and the corresponding plan for PG or Oracle.

**Comment by jerryshao** [comment]
Yeah, definitely we need to support PG and Oracle, @chanjaljayaram do you want to take a try?

**Comment by chanjaljayaram** [comment]
Sorry I’ve got no Java experience. :)

**Comment by yuqi1129** [comment]
Would anyone like to give it a try, I believe the main task will be handling the SQL dialect difference between MySQL or PG, or introducing a new ORM framework like `jdo` and `jDBI` since they both support JDBC protocol.
