### ISSUE TITLE
[Improvement] Support clear up entry comment

### ISSUE THREAD

**Issue by bknbkn** [apache/gravitino#4112]
### What would you like to be improved?

While using fileset, users sometimes want to clear the existing comments, but now they cannot pass the validation because **newComment** cannot be empty. Is it possible to delete the validation?

### How should we improve?

Delete the validation of newComment in fileset, maybe it can also be applied to metalake or table

**Comment by bknbkn** [comment]
@jerryshao what do you think about it

**Comment by jerryshao** [comment]
I think it is not proper to use `newComment` to achieve this, maybe we can have a new `Change` to support this?

**Comment by bknbkn** [comment]
Ok, maybe we can add new change  ```removeComment```

**Comment by coolderli** [comment]
> Ok, maybe we can add new change `removeComment`

@bknbkn It's a little strange. Why did the user remove the comment? Do we need to restrict the frontend to not allow comments to be empty？

**Comment by bknbkn** [comment]
@coolderli Because user can create a fileset without comment now, when they added a comment to fileset, It should be allowed to retract the comment and return to original created status
