### ISSUE TITLE
[Bug report] MySQL catalog and Iceberg catalog: create table with Decimal(0,0) column type or add this column type didn't pop error as expected

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#4115]
### Version

main branch

### Describe what's wrong

in Mysql catalog, when create a table with Decimal(0,0) type column, it turn out to be created as decimal(10,0) column type
in Iceberg catalog, when create a table with Decimal(0,0) type column, table created.
in Postgres catalog and Hive catalog,  create a table with Decimal(0,0) type column isn't allowed
<img width="1334" alt="image" src="https://github.com/apache/gravitino/assets/154112360/a8355271-913c-4f69-af1d-6e90ec8c6ba8">
<img width="1325" alt="image" src="https://github.com/apache/gravitino/assets/154112360/01b333a0-e4e0-4f00-ad1c-98ec6d8d13d3">

### Error message and/or stacktrace

N/A

### How to reproduce

1. create Mysql catalog, create Iceberg catalog
2. create table with Decimal(0,0) column type 
request body
```
{
  "name": "test3",
  "comment": "test",
  "columns": [
    {
      "name": "id",
      "type": "integer",
      "comment": "integer column",
      "nullable": true
    },
    {
      "name": "amount",
      "type": "Decimal(0,0)",
      "comment": "Decimal column",
      "nullable": true
    }]
}
```
It shouldn't be allowed to create the table having this column type

**Comment by FANNG1** [comment]
As `decimal(0, 0)` is not a valid, maybe we should validate it when creating a decimal type in Gravitino.

**Comment by FANNG1** [comment]
@jerryshao @mchades ,  I prefer do a validate for `decimal` since `decimal(0,0)` is meaningless,   WDYT?

**Comment by mchades** [comment]
> @jerryshao @mchades , I prefer do a validate for `decimal` since `decimal(0,0)` is meaningless, WDYT?

Can you describe how `Decima(0,0)` behaves in different engines?

**Comment by FANNG1** [comment]
> > @jerryshao @mchades , I prefer do a validate for `decimal` since `decimal(0,0)` is meaningless, WDYT?
> 
> Can you describe how `Decima(0,0)` behaves in different engines?

Spark doesn't check precision and scale, while Trino checks
```java
    public static DecimalType createDecimalType(int precision, int scale)
    {
        if (precision <= 0 || precision > MAX_PRECISION) {
            throw new TrinoException(INVALID_FUNCTION_ARGUMENT, format("DECIMAL precision must be in range [1, %d]: %s", MAX_PRECISION, precision));
        }

        if (scale < 0 || scale > precision) {
            throw new TrinoException(INVALID_FUNCTION_ARGUMENT, format("DECIMAL scale must be in range [0, precision (%s)]: %s", precision, scale));
        }

        if (precision <= MAX_SHORT_PRECISION) {
            return ShortDecimalType.getInstance(precision, scale);
        }
        return new LongDecimalType(precision, scale);
    }
```
