### ISSUE TITLE
[Bug report] Doc syntax errors: https://datastrato.ai/docs/0.5.1/lakehouse-iceberg-catalog#table-column-types

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#4134]
### Version

main branch

### Describe what's wrong

<img width="470" alt="image" src="https://github.com/apache/gravitino/assets/154112360/1da46d27-637c-4648-bd6c-79daaa7bf666">

### Error message and/or stacktrace

N/A

### How to reproduce

N/A

**Comment by kohantikanath** [comment]
Hi @danhuawang ,

I would love to work on this issue, can you assign me this issue?
