### ISSUE TITLE
[Improvement] Display the correct year on the web page

### ISSUE THREAD

**Issue by WeisonWei** [apache/gravitino#4142]
### What would you like to be improved?

The year is not displaying correctly on the web page
<img width="1467" alt="图片" src="https://github.com/apache/gravitino/assets/22849031/50e0d375-71f6-4e7f-b8ac-ca0fec6ee62b">

### How should we improve?

The web page should show the year according to the present time

**Comment by justinmclean** [comment]
The year should be the year of publication (when it was released), not the current year, and it can also refer to the first year it was pubblished.
