### ISSUE TITLE
[Bug report] Hive catalog: table comment or column comment has garbled Chinese character

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#4147]
### Version

main branch

### Describe what's wrong

<img width="1068" alt="image" src="https://github.com/user-attachments/assets/6cf334a7-ffc1-4085-9c77-b63e4a78d1e4">

<img width="858" alt="image" src="https://github.com/user-attachments/assets/b90a2e8a-1496-42e1-9647-d52214058782">

### Error message and/or stacktrace

N/A

### How to reproduce
1. Create a hive catalog, the properties as following:
<img width="1421" alt="image" src="https://github.com/user-attachments/assets/29329711-22a2-45f5-93b4-99374effbeb0">
db properties:
<img width="1349" alt="image" src="https://github.com/user-attachments/assets/d40b8b08-fb10-42fe-91ad-cb1cac00c93f">

2. Update table comment
request body:
```
{
  "updates": [
    {
      "@type": "updateComment",
      "newComment": "数量"
    }
  ]
}
```
3. Add column comment
request body:
```
{
  "updates": [
    {
      "@type": "addColumn",
      "fieldName": [
        "amount6"
      ],
      "type": "string",
      "comment": "数量",
      "nullable": true
    }
  ]
}
```

**Comment by mchades** [comment]
I have figured it out, this isn't about Gravitino.

It is caused by the MySQL charSet of HMS you are using. you can try to alter the charSet in MySQL by:
```mysql
alter table COLUMNS_V2 modify column COMMENT varchar(256) character set utf8;
alter table TABLE_PARAMS modify column PARAM_VALUE varchar(4000) character set utf8;
alter table PARTITION_PARAMS modify column PARAM_VALUE varchar(4000) character set utf8 ;
alter table PARTITION_KEYS modify column PKEY_COMMENT varchar(4000) character set utf8;
alter table INDEX_PARAMS modify column PARAM_VALUE varchar(4000) character set utf8;
```

**Comment by danhuawang** [comment]
> I have figured it out, this isn't about Gravitino.
> 
> It is caused by the MySQL charSet of HMS you are using. you can try to alter the charSet in MySQL by:
> 
> ```sql
> alter table COLUMNS_V2 modify column COMMENT varchar(256) character set utf8;
> alter table TABLE_PARAMS modify column PARAM_VALUE varchar(4000) character set utf8;
> alter table PARTITION_PARAMS modify column PARAM_VALUE varchar(4000) character set utf8 ;
> alter table PARTITION_KEYS modify column PKEY_COMMENT varchar(4000) character set utf8;
> alter table INDEX_PARAMS modify column PARAM_VALUE varchar(4000) character set utf8;
> ```

But this environment is using Postgres of HMS, do I need to alter the charSet in PG by the same command ?

**Comment by mchades** [comment]
I think so. It depends on the underlying DB's charset setting

**Comment by danhuawang** [comment]
Alter the charSet in MySQL by:
```
ALTER TABLE COLUMNS_V2 CONVERT TO CHARACTER SET utf8;
ALTER TABLE TABLE_PARAMS MODIFY PARAM_KEY varchar(256) CHARACTER SET utf8;
```
Then there's no garbled Chinese character. 
Close this issue.
