### ISSUE TITLE
[Improvement] The hint message for the Kafka catalog should be more readable.

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#4148]
### What would you like to be improved?

The hint message of the kafka catalog is supposed to be better readable
<img width="545" alt="image" src="https://github.com/user-attachments/assets/6e142a1c-0967-447d-95aa-53e10c058917">

### How should we improve?

The Apache Kafka brokers to connect to, allowing for multiple brokers separated by commas.

**Comment by jenish-thapa** [comment]
Hey @danhuawang,

I would like to work on this issue. Can you please assign this to me?
