### ISSUE TITLE
[Bug report] UI: The item Partitioning and SortOrders didn't refresh when request failed and switch tables

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#4153]
### Version

main branch

### Describe what's wrong

https://github.com/user-attachments/assets/ad6629e1-51fe-4e47-b702-4876877498eb

### Error message and/or stacktrace

N/A

### How to reproduce

Refer to the video

**Comment by jerryshao** [comment]
@LauraXia123 please help to check this.

**Comment by LauraXia123** [comment]
I'll fix this issue.
