### ISSUE TITLE
[Bug report] UI: Click "UPDATE" button, nothing happened if there's empty property widget on catalog edit page

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#4180]
### Version

main branch

### Describe what's wrong

<img width="607" alt="image" src="https://github.com/user-attachments/assets/59d08211-6061-43f9-be78-fd13d6e44359">

### Error message and/or stacktrace

N/A

### How to reproduce

1.  Edit exist catalog
2. Click "ADD PROPERTIES"
3. Click "UPADTE

**Comment by jerryshao** [comment]
@LauraXia123 please help to check this.

**Comment by LauraXia123** [comment]
I'll fix this issue.
