### ISSUE TITLE
[Improvement] Support setting gradle property `skipDockerTests` by environment variant

### ISSUE THREAD

**Issue by yuqi1129** [apache/gravitino#4181]
### What would you like to be improved?

Currently, the value of `skipDockerTests` is true, which means, all docker related tests will not be ran by default if we execute `gradle test`, If we want to run a test that was marked the `Tag` annotation in IDE, then the following error will occur
<img width="1171" alt="image" src="https://github.com/user-attachments/assets/c192cbab-24ad-4091-aaf6-46ba5fe37540">

and we need to modify the runtime configuration, such as adding `-PskipDockerTest=false` or change the value `skipDockerTest` to false in `gradle.properties` every time, it's rather tedious

I suggest we set the value by environment variant, so we can avoid changing `skipDockerTest` every time.

**Comment by FANNG1** [comment]
+1

**Comment by featherchen** [comment]
As the discussion in slack, we keep both `gradle.properties` and enviroment variable to control the test, and the priority of the former should be higher.
