### ISSUE TITLE
[Improvement] FileInputStream is not closed

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#4182]
### What would you like to be improved?

FileInputStream in GravitinoConfig.java is not closed:
```
properties.load(new FileInputStream(configFileName));
```

### How should we improve?

close the FileInputStream

**Comment by pravo23** [comment]
Hi, Can I work on this? Thanks

**Comment by yuqi1129** [comment]
> Hi, Can I work on this? Thanks

Sure, please go ahead
