### ISSUE TITLE
[Improvement] notify may not wake all threads

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#4183]
### What would you like to be improved?

In ClientPoolImpl.java `notify()` is used where probably `notifyAll()` should be used. `notify()` and `notifyAll()` both wake up sleeping threads, but `notify` only wakes one, while `notifyAll` wakes all of them.

### How should we improve?

Use `notifyAll()` instead of `notify()`.

**Comment by ashwin1596** [comment]
Hi,

I'm interested in working on this issue. Could you please provide more details on where this update needs to be implemented?

Thank you!

**Comment by justinmclean** [comment]
It's line 150 of ClientPoolImpl.java
