### ISSUE TITLE
[Improvement] Use of methods marked @VisibleForTesting in production code

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#4185]
### What would you like to be improved?

This occurs in several places:
KerberosClient.java - ` KerberosName.resetDefaultRealm();`
HiveCatalogOperations.java - `KerberosName.resetDefaultRealm();`
KerberosClient.java - `KerberosName.resetDefaultRealm();`
PaimonConfig.java - ' new ConfigBuilder(PaimonCatalogPropertiesMetadata.PAIMON_METASTORE)' and ` new ConfigBuilder(PaimonCatalogPropertiesMetadata.WAREHOUSE)` and ` new ConfigBuilder(PaimonCatalogPropertiesMetadata.URI)`
BaseCatalogPropertiesMetadata.java - `BaseCatalog.CATALOG_OPERATION_IMPL`
IcebergPropertiesConverter.java - with GRAVITINO_ICEBERG_CATALOG_URI, GRAVITINO_ICEBERG_CATALOG_WAREHOUSE, ICEBERG_CATALOG_BACKEND_HIVE and GRAVITINO_ICEBERG_CATALOG_URI
IcebergPropertiesConverter.java -`gravitinoProperties.get(IcebergPropertiesConstants.GRAVITINO_ICEBERG_CATALOG_WAREHOUSE);` and with ICEBERG_CATALOG_TYPE and 

### How should we improve?

Either @VisiubleForTesting should be removed or the code not be called in production code.

**Comment by khmgobe** [comment]
@justinmclean  Hi. Does the fact that it shouldn't be called mean that you want me to remove the corresponding code?

**Comment by justinmclean** [comment]
You'll need to look at each one and see if it does need to be used. In most cases, I'd guess the @VisibleForTesting annotation should be removed as the method is used in non-testing code and the code is needed.

**Comment by khmgobe** [comment]
@justinmclean Do you mind if I try it ?

**Comment by justinmclean** [comment]
@jerryshao What do you think about the removal of KerberosName.resetDefaultRealm()? It's marked @VisibleForTesting so I assume we shouldn't be calling it, but there might be a good reason I'm unaware of.

**Comment by jerryshao** [comment]
I'm not so sure about this, maybe @yuqi1129 can better answer this.

**Comment by justinmclean** [comment]
@yuqi1129 what do you think?

**Comment by yuqi1129** [comment]
I have confirmed that `KerberosName.resetDefaultRealm()` can be removed as it has no impact on the logic in fact. As for other codes, If they are used in production code, I believe we can remove the annotation `VisibleForTesting` to solve the problem.

**Comment by jerryshao** [comment]
@yuqi1129 please review the PR and leave the comments on the PR, thanks.
