### ISSUE TITLE
[Improvement] Fileset don't support to be named like hidden directory, eg .gitconfig,.staging

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#4205]
### What would you like to be improved?

Create fileset , named as hidden type directory name 
eg: .vscode  .gitconfig .bash_profile

**Comment by jerryshao** [comment]
We can support creating fileset with a storageLocation using hidden directory, the behavior is expected. But we cannot create a filset with a name having a dot ".", this is illegal, as we have a restriction that all the entity names in Gravitino cannot have "." in the name. @danhuawang

**Comment by jerryshao** [comment]
This is not an issue, I'm going to close it. Thanks @danhuawang for your reporting.
