### ISSUE TITLE
[Subtask] Add Integration Test of OAuth2TokenProvider of client-python

### ISSUE THREAD

**Issue by noidname01** [apache/gravitino#4208]
### Describe the subtask

* add Integration Test of OAuth2TokenProvider of client-python

### Parent issue

#3755

**Comment by xunliu** [comment]
hi @noidname01 This issue has any update?

**Comment by noidname01** [comment]
@xunliu Sorry for the inactive at this issue. After some survey, this issue involve relatively large code change than others in order to implement the OAuth example in [documentation](https://github.com/apache/gravitino/blob/main/docs/security.md) with Python, so it took me longer time to plan.
