### ISSUE TITLE
[Subtask] Add Metalake Error Handler and related exceptions, test cases in client-python

### ISSUE THREAD

**Issue by noidname01** [apache/gravitino#4226]
### Describe the subtask

Add Metalake Error Handler and related exceptions, test cases in `client-python` based on `client-java`

### Parent issue

#4225

**Comment by jingjia88** [comment]
Hi, I would like to work on this issue. Could you assign it to me ? 
Many thanks!

**Comment by noidname01** [comment]
Hi @jingjia88, thank for your interest in this issue. Free to ask any question if you run into problems.
@jerryshao Can you assign this issue to @jingjia88 ?

**Comment by jerryshao** [comment]
@jingjia88 @noidname01 I saw there're other left issues, will you continue work on them?

**Comment by noidname01** [comment]
@jerryshao Yeah, I plan to do #4173 first and then #4208. I think #4227 and #4228 can be good-first-issue, because they are relatively easy.

**Comment by jerryshao** [comment]
I planned to ship these in 0.6.0 ( in the middle of August), you can add "good first issue" label on that two issues. If there's no one working on that, it would be better that you can help on this. Thanks.
