### ISSUE TITLE
[Subtask] Add Schema Error Handler and related exceptions, test cases in client-python

### ISSUE THREAD

**Issue by noidname01** [apache/gravitino#4228]
### Describe the subtask

Add Schema Error Handler and related exceptions, test cases in `client-python` based on `client-java`

### Parent issue

#4225

**Comment by jerryshao** [comment]
@jingjia88 can you please leave a message here, so I can assign to you.

**Comment by jingjia88** [comment]
@jerryshao coming ʕ •ᴥ•ʔ
