### ISSUE TITLE
[Improvement] Add the out direcotory in the project to the git ignore file

### ISSUE THREAD

**Issue by yuqi1129** [apache/gravitino#4234]
### What would you like to be improved?

After we build Gravitino, there will be some `out` directory under the project folder, please see:
<img width="767" alt="image" src="https://github.com/user-attachments/assets/542f65ca-322b-4b41-80e6-ec833b600c94">

### How should we improve?

Add them to the .gitignore file or avoid generating such files.

**Comment by four1er** [comment]
hello, I want to solve this issue. Please assign it to me, thanks!

**Comment by justinmclean** [comment]
@four1er do you still want to work on this?

**Comment by khmgobe** [comment]
@justinmclean If possible, can I try it?

**Comment by yuqi1129** [comment]
It seems that we can't reproduce the issue in the main branch.

**Comment by justinmclean** [comment]
Closing as we can't reproduce, please ask to reopen if you come across the issue again.
