### ISSUE TITLE
[Improvement] Local cache should be turned off by default

### ISSUE THREAD

**Issue by lw-yang** [apache/gravitino#4246]
### What would you like to be improved?

In production environments, multiple Gravitino instances are typically deployed, which can lead to data inconsistency issues with local caching. 

If data is deleted in one instance and then retrieved from another instance, the cache in the second instance may still contain the data. 

In our scenario, we encountered an inconsistency issue, after deleting a role and then attempting to retrieve it, found the data still exists

Therefore, local caching should be disabled by default, allowing users to evaluate and choose whether to enable it. 

Alternatively, a caching framework can be provided, allowing users to select the caching implementation, such as local caching or distributed caching.

**Comment by shaofengshi** [comment]
For single instance deployment, local cache is still valid; I think the point is, when deploy it into multi-instances, should use external shared cache like a redis, instead of using local cache.

**Comment by lw-yang** [comment]
In production environment, it is impossible to have only single instance deployed. If other companies deploy production 
environments, they will encounter the same issue. 

Given that Gravitino currently does not support configuring external shared cache, local cache should be disabled by default to avoid data inconsistency in production environment.

**Comment by jerryshao** [comment]
We're going to remove this local cache, as the number of roles will be significantly dropped after we refactor to use ownership mechanism.

**Comment by jerqi** [comment]
@lw-yang Do you like to submit a pull request to fix the issue?

**Comment by lw-yang** [comment]
@jerqi Ok, I would like to fix it

**Comment by jerqi** [comment]
> @jerqi Ok, I would like to fix it

Gently ping. Will you continue this work?
