### ISSUE TITLE
[Bug report] Missing description of support type uuid

### ISSUE THREAD

**Issue by LauraXia123** [apache/gravitino#4258]
### Version

main branch

### Describe what's wrong

https://datastrato.ai/docs/0.5.1/manage-relational-metadata-using-gravitino/#gravitino-table-column-type 
Missing description of support type `uuid`

### Error message and/or stacktrace

N/A

### How to reproduce

N/A

**Comment by Vishesh-Paliwal** [comment]
Hi @LauraXia123 and @justinmclean , I would love to work on this . can I get assigned for the same .

**Comment by Vishesh-Paliwal** [comment]
@justinmclean  Made the pr . Kindly review

**Comment by Vishesh-Paliwal** [comment]
hi @justinmclean  , Created a PR . kindly review .

PS : sorry about earlier one , I'm new to open source
