### ISSUE TITLE
[Improvement] In SecureHadoopCatalogOperations.java checkif file is deleted

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#4293]
### What would you like to be improved?

In SecureHadoopCatalogOperations.java in method removeFile check that delete actually works

### How should we improve?

Check the return value of delete and log an error

**Comment by khmgobe** [comment]
Let me take care of it

**Comment by khmgobe** [comment]
@yuqi1129 I hope you have a good day today. Please review it.

**Comment by yuqi1129** [comment]
> @yuqi1129 I hope you have a good day today. Please review it.

Please look at your PR and I'm confused about the actual change you made.

**Comment by khmgobe** [comment]
@yuqi1129 

> @yuqi1129 I hope you have a good day today. Please review it.
> 
>Please look at the promotion and I'm confused about the actual change.

Existing changes have been made 
File = new file (filePath);
    if (file.exists()) {
      file.delete ();
  }
  
  Here 
  
       boolean isDelete = file.delete ();
      Deleted (!) {
        LOG.error ("Failure to delete file: {}", filePath");
      }

It was about adding this code.

However, for code-based consistency, I used Gradle-SpotLess to sort the code according to the rules, so there may be other changes as you checked. Did you understand?

**Comment by yuqi1129** [comment]
<img width="1408" alt="image" src="https://github.com/user-attachments/assets/9ccf44e7-db19-40e6-bb10-880b23fb95f2">

Please take a look at at the code change.

**Comment by khmgobe** [comment]
> <img alt="image" width="1408" src="https://private-user-images.githubusercontent.com/15794564/353289057-9ccf44e7-db19-40e6-bb10-880b23fb95f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDYyNTIsIm5iZiI6MTcyMjMwNTk1MiwicGF0aCI6Ii8xNTc5NDU2NC8zNTMyODkwNTctOWNjZjQ0ZTctZGIxOS00MGU2LWJiMTAtODgwYjIzZmI5NWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDAyMTkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNDQzNjY4NTYwZjAyMzNlZmM5OGVjMzZiYjBjNzcwYzI4MzZjOWQ3N2EzOWZkZDM4MzQxNzE1OTdkODMyNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4lvqGrTMrZQnrke3Xju39iUWo8MbzAdJC_RZLZPQueY">
> Please take a look at at the code change. All you have done is just format the code.

The commit didn't apply properly 

https://github.com/apache/gravitino/pull/4297/files

If you check here, you can see that I fixed the code to suit the issue.

If you look here, I posted PR after fixing the class, and the work I wanted to share and upload went up in one place.

It is correct that the code format has been changed as you saw, because it is a change that occurred because of Gradle-SpotLess.

**Comment by yuqi1129** [comment]
This issue was resolved by #4297 by the way, perhaps the PR can be closed?

**Comment by khmgobe** [comment]
> This issue was resolved by #4297 by the way, perhaps the PR can be closed?

sure ! closed please, Have a Good Time !

**Comment by yuqi1129** [comment]
This issue was resolved in #4297.
