### ISSUE TITLE
[Improvement] Use of nested ternary operation is a little confusing

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#4294]
### What would you like to be improved?

In PaimonSchema.java there a nested ternary operation:
```
      paimonSchema.comment =
          comment == null
              ? (properties == null ? null : properties.get(PaimonSchemaPropertiesMetadata.COMMENT))
              : comment;
```

This can be a little confusing.

### How should we improve?

Improve code clarity.

**Comment by khmgobe** [comment]
I have a question.

1. Modifying to if-else branch statement

2. Use the trinomial operator as is, but modify it

**Comment by justinmclean** [comment]
As long as it more easily understood either is fine.
