### ISSUE TITLE
[Improvement] In CommonMetaService.java getParentEntityIdByNamespace method code can be improved

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#4303]
### What would you like to be improved?

In  CommonMetaService.java getParentEntityIdByNamespace level is checked but case statement, while it works, could be improved as there is no need to loop around each level setting parentEntityId several times

### How should we improve?

Just remove loop and use the level to get parentEntityId?

**Comment by khmgobe** [comment]
I want to improve it

**Comment by khmgobe** [comment]
@justinmclean 

Have a nice day! I have a question. I checked the code base according to the issued issue and found that Topic Metaservice, Table Metaservice, Fileset Metaservice, Schema Metaservice have the same kind of iterative code, is there a reason why they don't modify that code in this class? Please reply to this and we will proceed with the code modification.

**Comment by justinmclean** [comment]
The other methods are OK as they are using a builder and doing with parentEntityId at each level. This code just assigns the parentEntityId and does nothing with it inside the case statements.
