### ISSUE TITLE
[Subtask] Add event listener support for Tag system.

### ISSUE THREAD

**Issue by jerryshao** [apache/gravitino#4309]
This issue tracks the work of achieving event listener for tag system. Like other events, we can also follow the way to add event listener support to the tag system.

**Comment by jerryshao** [comment]
@TEOTEO520 here is the issue, please leave a message here so I can assign this to you.

**Comment by charanbhatia** [comment]
@jerryshao  can you assign this issue to me?

**Comment by jerryshao** [comment]
@charanbhatia I think @TEOTEO520 also want to work on this, if you want to take a shot you can sync with @TEOTEO520 about this.

**Comment by TEOTEO520** [comment]
> @TEOTEO520 here is the issue, please leave a message here so I can assign this to you.
I apologize for not responding to you in a timely manner. I am currently working on the implementation of this issue. If @charanbhatia you could leave this issue to me, I would be very grateful.

**Comment by amazingLychee** [comment]
Hi @jerryshao, can I take this?

**Comment by xunliu** [comment]
hi @amazingLychee Thank you for your interest in this issue.
I already assign it to you. :-)

**Comment by jerryshao** [comment]
> Hi @jerryshao, can I take this?

Please go ahead. Thanks @amazingLychee .

**Comment by amazingLychee** [comment]
Hi @jerryshao @xunliu , I have been busy with final exams recently. If it blocks another task, could you assign me off from this task? Thank you!

**Comment by jerryshao** [comment]
Sure, no problem.

**Comment by TungYuChiang** [comment]
@jerryshao I’m interested in working on this issue. Could I take it?

**Comment by jerryshao** [comment]
Yes, you can go ahead, this task is bit large, it would be better if you can read out how event listener is achieved in Gravitino and draft a design doc about how to do it for Tag system.

**Comment by TungYuChiang** [comment]
@jerryshao I have drafted the design document for the Tag system, and you can find it at the link below
[design document](https://docs.google.com/document/d/11eCkSidlcQMIpBI6gk64BMFjalHZO73g-H9pnX4BkGk/edit?hl=zh-tw&tab=t.0)
If there are any misunderstandings or areas for improvement, please let me know.
