### ISSUE TITLE
[Bug report] python-client module import error

### ISSUE THREAD

**Issue by bknbkn** [apache/gravitino#4322]
### Version

main branch

### Describe what's wrong

Run gravitino python client integration test will occur tests module import error

### Error message and/or stacktrace

```
ImportError: Failed to import test module: test_schema
Traceback (most recent call last):
  File "/builds/no5LrKHc/0/streaming/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/builds/no5LrKHc/0/streaming/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/builds/no5LrKHc/0/streaming/gravitino/clients/client-python/tests/integration/test_schema.py", line 19, in <module>
    from tests.integration.integration_test_env import IntegrationTestEnv
ModuleNotFoundError: No module named 'tests'
```

### How to reproduce

+ Python Integration Test CI succeeds link: https://github.com/apache/gravitino/actions/runs/10154257657/job/28079071746 

+ Python Integration Test CI failed link: https://github.com/apache/gravitino/actions/runs/10182900265/job/28166579701

**Comment by bknbkn** [comment]
@xunliu @jerryshao We ran the integration test this afternoon and these problems suddenly occurred. Could you help verify whether the same problem occurs here? I find some CI here have similar problems.

**Comment by bknbkn** [comment]
like this https://github.com/apache/gravitino/actions/runs/10179602660/job/28155688726

**Comment by jerryshao** [comment]
Yeah, we also encountered this problem, and we're still investigating it, do you know how to fix it?

**Comment by bknbkn** [comment]
I try to rename ```tests``` module  to ```gravitino_tests``` and pass tests, Maybe some package has the same name and a conflict occurred? @jerryshao

**Comment by noidname01** [comment]
@bknbkn Yeah, I think it's possible. It might be the same problem as [this](https://stackoverflow.com/questions/56780892/python-unit-test-module-throws-modulenotfounderror-no-module-named-tests-test).

**Comment by xunliu** [comment]
Maybe GitHub CI container have changed, python lost the environment `PYTHONPATH`.

I seated `PYTHONPATH: ${{ github.workspace }}/clients/client-python` in the python-client CI fixed this issue, let's me pull a request to try fix this issue.

**Comment by noidname01** [comment]
I think maybe it's because the `pip` version change in [`conda-forge`](https://anaconda.org/conda-forge/pip/files). 
They seems to update their `pip` version from `24.0` to `24.1.2`, and that's the time CI has broken.

**Comment by xunliu** [comment]
hi @noidname01 Thank you reply this question.
The Gravitino python client uses https://github.com/piyushroshan/python-gradle-miniforge-plugin, can we set the pip version?

**Comment by bknbkn** [comment]
Maybe we should import by relative name like ```from .integration_test_env import IntegrationTestEnv``` or unique package name like ```gravitino_test``` to avoid this problem, because it will happend in local running too.
