### ISSUE TITLE
[Improvement] unitycatalog plans to replace hms

### ISSUE THREAD

**Issue by melin** [apache/gravitino#4328]
### What would you like to be improved?

unitycatalog plans to replace hms? spark engine reads metadata directly from unitycatalog? 
Compatible with hms client

**Comment by mchades** [comment]
Sorry, I don't get your point.

Are you asking about the Databricks Unity Catalog? Please provide more details about your issue.

**Comment by shaofengshi** [comment]
Hello Melin, I think this question should be raised to unity catalog project, they know that better than us. :)
