### ISSUE TITLE
[Improvement] Possible null pointer in UserContext.java

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#4331]
### What would you like to be improved?

parentContext could be null in this line (note the null checks in other parts of the code).
```
KerberosUserContext kerberosUserContext = ((KerberosUserContext) parentContext).deepCopy();
```

### How should we improve?

Check that parentContext is not null

**Comment by mayank1365** [comment]
@justinmclean please assign this issue to me

**Comment by poojatalele** [comment]
I would like to work on this, kindly assign.

**Comment by lokendra005** [comment]
@justinmclean please assign this to me
