### ISSUE TITLE
[Improvement] UI: Switch catalog properties from immutable to mutable

### ISSUE THREAD

**Issue by yuqi1129** [apache/gravitino#4351]
### What would you like to be improved?

We have modified most catalog properties from immutable to mutable, so the UI should also align with this change, for more,please refer to

<img width="1099" alt="image" src="https://github.com/user-attachments/assets/e33471fc-6c4e-4664-9370-d60e7c8c1ae2">

or
https://docs.google.com/document/d/1y9NOLDE6GZFKMFNGAfbYlOHEsQD9__d0GtuUJ-eigIc/edit

**Comment by yuqi1129** [comment]
@LauraXia123 
Please leave a comment here so I can assign the issue to you.

**Comment by LauraXia123** [comment]
@yuqi1129 I have fixed it on [PR](https://github.com/apache/gravitino/pull/4355)
