### ISSUE TITLE
[FEATURE] Add github logo, stars number and forks number for UI

### ISSUE THREAD

**Issue by LauraXia123** [apache/gravitino#4362]
### Describe the feature

Add github logo, stars number and forks number for UI, click the logo block will link to gravitino [github](https://github.com/apache/gravitino)
<img width="570" alt="image" src="https://github.com/user-attachments/assets/aea3c301-b707-4f97-9624-9a35e755a932">

1. We need to get the stars and forks number need from the GitHub RESTful interface
2. Please notice, when starts and forks number than 1000, We need to show `1.x` K

**Comment by jenish-thapa** [comment]
Hey @LauraXia123, 

I would like to work on this issue. Can you please assign it to me?

**Comment by justinmclean** [comment]
I think people will expect that clicking on the logo will take you to the first page of the application, not the GitHub repo.

**Comment by LauraXia123** [comment]
@justinmclean  yeah, I mean clicking on the clicking on the new logo in the top right corner.

**Comment by jenish-thapa** [comment]
Thank you for clarifying the requirements. I can take care of adding the GitHub logo, star count, and fork count to the top right corner of the UI, with the logo linking to the Gravitino GitHub page as specified.

**Comment by xunliu** [comment]
hi @jenish-thapa Thank you for your interesting this issue.
I updated issue detail information, Please look it.
> 1. We need to get the stars and forks number need from the GitHub RESTful interface
> 2. Please notice that when the starts and forks number than 1000, We need to show `1.x K`

**Comment by LauraXia123** [comment]
hi @jenish-thapa Do you have time for this issue?

**Comment by CodingWithError** [comment]
hey @jenish-thapa if you are not working on this issue can you assign this to me.

**Comment by LauraXia123** [comment]
@CodingWithError Hi, thank you for your interesting this issue. You can submit the pr for this issue, we'll assign to you later.

**Comment by CodingWithError** [comment]
@LauraXia123 i will raise the pr by tomorrow EOD.

**Comment by LauraXia123** [comment]
@CodingWithError hi, have you raise the pr?

**Comment by CodingWithError** [comment]
Hey @LauraXia123 I didn't yet raise my pr. I have searched for this page, but couldn't find it can you please help me with it. Thank you.

**Comment by LauraXia123** [comment]
@CodingWithError you can find it at `https://github.com/apache/gravitino/blob/main/web/web/src/app/rootLayout/AppBar.js`

**Comment by SZL741023** [comment]
Hi @LauraXia123 

I would like to work on this issue. Can you assign it to me?
Thanks

**Comment by xunliu** [comment]
hi @SZL741023 Thank you for your interesting this issue.
I assign this issue to you.
