### ISSUE TITLE
[Improvement] UI: Replace to password input for all jdbc-password value

### ISSUE THREAD

**Issue by LauraXia123** [apache/gravitino#4384]
### What would you like to be improved?

<img width="577" alt="image" src="https://github.com/user-attachments/assets/68316b8b-9e4b-4c44-bb92-e16ebc0cb6aa">

**Comment by jenish-thapa** [comment]
Hey @LauraXia123, @justinmclean 

If I am understanding correctly, you want the value inside the red box to be changed to "password".

Could you please confirm if my understanding is correct?

Once confirmed, can you please assign it to me?

**Comment by justinmclean** [comment]
I think we can use a password input/display rather than a plan text input/display.
