### ISSUE TITLE
[Bug report] spark connector build failed with scala 2.13

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#4386]
### Version

main branch

### Describe what's wrong

spark connector build failed with scala 2.13

### Error message and/or stacktrace

```
/Users/fanng/opensource/gravitino/spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/iceberg/extensions/IcebergExtendedDataSourceV2Strategy.java:66: 错误: IcebergExtendedDataSourceV2Strategy中的apply(LogicalPlan)无法覆盖GenericStrategy中的apply(LogicalPlan)
  public Seq<SparkPlan> apply(LogicalPlan plan) {
                        ^
  返回类型scala.collection.Seq<SparkPlan>与scala.collection.immutable.Seq<SparkPlan>不兼容
  其中, PhysicalPlan是类型变量:
    PhysicalPlan扩展已在类 GenericStrategy中声明的TreeNode<PhysicalPlan>
/Users/fanng/opensource/gravitino/spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/iceberg/extensions/IcebergExtendedDataSourceV2Strategy.java:65: 错误: 方法不会覆盖或实现超类型的方法
  @Override
  ^
```

### How to reproduce

./gradlew clean :spark-connector:spark-runtime-3.4:build -PscalaVersion=2.13 -PjdkVersion=17

**Comment by jerryshao** [comment]
@caican00 please leave a message here, so I can assign this issue to you.

**Comment by caican00** [comment]
> @caican00 please leave a message here, so I can assign this issue to you.

got it.

**Comment by FANNG1** [comment]
> > @caican00 please leave a message here, so I can assign this issue to you.
> 
> @jerryshao please assign it to me, thanks!

done
