### ISSUE TITLE
[EPIC] Support credential vending in Gravitino

### ISSUE THREAD

**Issue by jerryshao** [apache/gravitino#4398]
### Describe the proposal

As a centralized service, Gravitino should provide a mechanism to let third-party applications/service integrate with it to get temporary access to the underlying services, like S3, HDFS, HMS, etc on behalf of their users. the credential vending mechanism is heavily adopted in the cloud service. So Gravitino should provide a similar mehanism.

### Task list

-  [x] #4992 
-  [x] #4993 
-  [x] #4994 
-  [x] #5068 
-  [x] #5619 
-  [x] #5842 
-  [x] #5620
-  [ ] #5621 
-  [x] #5622 
-  [x] #5623 
-  [x] #5624 
-  [x] #5625

**Comment by lw-yang** [comment]
This is the Proposal of the secret management system, which should be related to credentials vending

https://docs.google.com/document/d/1CUUtUXJHU89zbaOUkQRMVTfbAS5qlg_xiz5y6kHd37s/edit

**Comment by FANNG1** [comment]
based on the design of  @lw-yang , proposed a new design https://docs.google.com/document/d/1fovK0ylSmI45ynrCPcnRZqzyPDn7DRNb_ExdbjVPq0k/edit
