### ISSUE TITLE
[Improvement] Calls to code marked @VisibleForTesting in production code

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#4408]
### What would you like to be improved?

In KerberosClient.java this line:
```UserGroupInformation.setLoginUser(kerberosLoginUgi);```

In PaimonCatalogOps.java this line:
```paimonBackendCatalogWrapper = loadCatalogBackend(paimonConfig);```

### How should we improve?

Either not make the call or remove the @VisibleForTesting annotation.

**Comment by Naresh-kumar-Thodupunoori** [comment]
@justinmclean I would like to work on it!

**Comment by Naresh-kumar-Thodupunoori** [comment]
Hey, as when I looked into the code I found @VisibleForTesting only in the loadCatalogBackend method of the PaimonCatalogOps.java file. So I am proposing to remove the annotation only in that file. As the loadCatalogBackend method is necessary for the proper functioning of the PaimonCatalogOps, it needs to be accessible in production code.

**Comment by Naresh-kumar-Thodupunoori** [comment]
Hey @justinmclean can you review my PR

**Comment by Naresh-kumar-Thodupunoori** [comment]
hey @justinmclean I have created a new PR and check for gradle build locally and it is working fine..!

**Comment by justinmclean** [comment]
`setLoginUser` is marked @VisibleForTesting so it would be good to fix that as well.

**Comment by Naresh-kumar-Thodupunoori** [comment]
ok

**Comment by Naresh-kumar-Thodupunoori** [comment]
Hello @justinmclean I have updated the PR with another commit.Please review it!!
