### ISSUE TITLE
[Improvement] TrinoIT should use the latest CI image of Hive

### ISSUE THREAD

**Issue by mchades** [apache/gravitino#4424]
### What would you like to be improved?

The gravitino-ci-hive image was updated to 0.1.13:
https://github.com/apache/gravitino/blob/f3b4c3a405fc9229806bcb520fc9c6bba0ab9440/docs/docker-image-details.md?plain=1#L146

But the TrinoIT still using 0.1.12:
https://github.com/apache/gravitino/blob/f3b4c3a405fc9229806bcb520fc9c6bba0ab9440/integration-test/trino-it/docker-compose.yaml#L24

### How should we improve?

Let's standardize the hive image version usage

**Comment by diqiu50** [comment]
OK
