### ISSUE TITLE
[Bug report] The property URI of Hive catalog should be mutable in frontend page

### ISSUE THREAD

**Issue by yuqi1129** [apache/gravitino#4425]
### Version

main branch

### Describe what's wrong

![image](https://github.com/user-attachments/assets/4ace5cdb-3210-4474-9a3c-eb2364625102)

### Error message and/or stacktrace

Please see above

### How to reproduce

Please see above

**Comment by shaofengshi** [comment]
I think this was by design; It is not a bug, but an enhancement.
