### ISSUE TITLE
[Improvement] the output message of `start.sh` is confused

### ISSUE THREAD

**Issue by mchades** [apache/gravitino#4441]
### What would you like to be improved?

when the iceberg rest service start fails, the output message is confused:

<img width="905" alt="image" src="https://github.com/user-attachments/assets/f36f4d2e-bc8d-4e1a-9eb2-8e80d9bc155d">

### How should we improve?

Improve the accuracy of the output message.

**Comment by mchades** [comment]
@FANNG1 could you plz take a look?

**Comment by FANNG1** [comment]
Iceberg REST service is one component of Gravitino server, so it's ok to show Gravitino server start failed.

**Comment by mchades** [comment]
But the output is `Gravitino Server start success!` @FANNG1
