### ISSUE TITLE
[FEATURE] Publish Docker image to Apache's official DockerHub account

### ISSUE THREAD

**Issue by xunliu** [apache/gravitino#4445]
### Describe the feature

Publish the Docker image to Apache's official DockerHub account.
+ https://hub.docker.com/repository/docker/apache/gravitino

Gravitino support 2 options to publish Docker image.
1. Use GitHub CI to publish Docker image. https://github.com/apache/gravitino/blob/main/docs/publish-docker-images.md

    + Need set publisher user name & password in the GitHub sercerts.
    + But Apache organization cannot set this in the GitHub sercerts, So we only fork Gravitino repo in to owner account and set sercerts to publish DockerHub.

2. Mananly execute https://github.com/apache/gravitino/blob/main/dev/docker/build-docker.sh

    + Need input publisher user name & password in the Docker client

**Comment by justinmclean** [comment]
This need some updates to comply with https://incubator.apache.org/guides/distribution.html#docker

Do you need some help with this?
