### ISSUE TITLE
[Improvement] Support loading custom catalog as backend In Iceberg rest catalog server

### ISSUE THREAD

**Issue by theoryxu** [apache/gravitino#4508]
### What would you like to be improved?

Now Gravitino doesn't support custom catalogs being backend in the Iceberg scenario. Users must choose one among `memory` , ` hive` ,  ` jdbc` , and ` rest` .

We should add some mechanisms so users can load custom catalogs to fit their cases.

### How should we improve?

modify the backend catalog loading process.

**Comment by theoryxu** [comment]
@jerryshao @FANNG1  , WDYT?

**Comment by FANNG1** [comment]
is it a productive requirement?

**Comment by theoryxu** [comment]
> is it a productive requirement?

yeah, we would implement an enhanced catalog based on `jdbc catalog`. In this case, we want to make them work together gracefully, not just modify Gravitino's code in our own fork.

**Comment by theoryxu** [comment]
> That sounds reasonable. Would you like to work on this?

I'd be happy to take this on.
