### ISSUE TITLE
[Improvement] Execution flow of drop a role

### ISSUE THREAD

**Issue by xunliu** [apache/gravitino#4509]
### What would you like to be improved?

Currently, When we call drop role interface API, Gravitino will directly delete the role and grant data in the database,
and call `AuthorizationPlugin::onRoleDeleted()`. 
But didn't call `AuthorizationPlugin::onRevokedRolesFromUser()` and `AuthorizationPlugin::onRevokedRolesFromGroup()` API.

#### Affected systems
+ ...

#### Unaffected systems
+ Apache Ranger

### How should we improve?

From the user's point of view, the execution flow of the use role
1. Create a role
2. Grant this role to user

So, I think when the user drops a role, the first step is to check if this role has already authorized users.
if already authorized users then don't drop this role. must wait for the revoke this role from its user.

**Comment by jerqi** [comment]
We can close this temporaly.
