### ISSUE TITLE
[Bug report] update tag failed

### ISSUE THREAD

**Issue by LauraXia123** [apache/gravitino#4540]
### Version

main branch

### Describe what's wrong

create a new tag without comment property
Then update the tag, it will get an exception

### Error message and/or stacktrace

<img width="942" alt="image" src="https://github.com/user-attachments/assets/fbfbbe71-36a4-434d-92a9-8bbe2031cc31">

### How to reproduce

create a new tag by curl
```
curl -L -X POST 'http://localhost:8090/api/metalakes/:metalake/tags' \
-H 'Content-Type: application/json' \
-H 'Accept: application/vnd.gravitino.v1+json' \
--data-raw '{
  "name": "string",
  "properties": {}
}'
```
then update the tag
```
curl -L -X PUT 'http://localhost:8090/api/metalakes/:metalake/tags/:tag' \
-H 'Content-Type: application/json' \
-H 'Accept: application/vnd.gravitino.v1+json' \
--data-raw '{
  "updates": [
    {
      "@type": "rename",
      "newName": "my_tag_new"
    },
  ]
}'
```

**Comment by jerryshao** [comment]
I will fix it.
