### ISSUE TITLE
[Improvement] support Gravitino-based multi catalog support for Gravitino Iceberg REST server

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#4581]
### What would you like to be improved?

#4273 add conf-based multi-catalog support, we could use Gravitino as a catalog provider to support dynamic catalog management for the Iceberg REST server.

**Comment by theoryxu** [comment]
I can take it; please assign it to me.

**Comment by FANNG1** [comment]
> I can take it; please assign it to me.

Thanks @theoryxu for taking this.
