### ISSUE TITLE
[Bug report] bug about hdfs root catalog

### ISSUE THREAD

**Issue by heziyi399** [apache/gravitino#4586]
### Version

main branch

### Describe what's wrong

now I want to use hadoop catalog,i hava create metalake,catalog,schema,fileset,the localtion is:
<img width="940" alt="企业微信截图_ad928ca7-f6bc-4dc4-b1e2-46f2f6f76b76" src="https://github.com/user-attachments/assets/7d8e0c56-677b-4762-aef4-8b4df02e430b">
<img width="914" alt="企业微信截图_e0c34e7d-52c0-44ab-9026-e2b48c2ea519" src="https://github.com/user-attachments/assets/3ad09329-b99f-4c53-beee-e3541188ffd4">
<img width="859" alt="企业微信截图_e17e9d7b-d447-45d3-8a10-37f32c82377b" src="https://github.com/user-attachments/assets/8e6824f0-39d8-487c-9384-db5fcf4ceb26">
You can see that this location is the root directory。
  I want to get file by using gravitino catalog，so I  obtain files through the command line:
<img width="1133" alt="企业微信截图_0824e5de-0f11-4a7a-b9d9-22a6c94658bf" src="https://github.com/user-attachments/assets/319e21b6-7063-4ebe-8918-4ae94a9d2fe0">
<img width="1125" alt="企业微信截图_d07927fb-587c-41e2-8912-47239ba0bea0" src="https://github.com/user-attachments/assets/5bb1cfb8-bd39-43a5-a5d7-a36b8c71ce21">

You can see that this result comes with a prefix and an error message“does not exist.”.But if I don't use the location of the root directory ,the result is normal：
<img width="1141" alt="企业微信截图_0667e67f-9582-454c-8e0e-91d289b2d941" src="https://github.com/user-attachments/assets/b5610884-326a-432e-b02a-850bbfd40b1e">
<img width="1058" alt="企业微信截图_96c12d23-79e4-43ec-aefc-1546e935c2c6" src="https://github.com/user-attachments/assets/9535f229-5c60-4301-bf78-25cccf6bf502">

### Error message and/or stacktrace

<img width="1125" alt="企业微信截图_d07927fb-587c-41e2-8912-47239ba0bea0" src="https://github.com/user-attachments/assets/bc6672f5-c4d3-4716-a2da-4da36442b157">

### How to reproduce

0.5.1

**Comment by xloya** [comment]
Have reproduced the issue, will fix this tomorrow. @heziyi399 Thanks for reporting this.

**Comment by xloya** [comment]
> @xloya I will now place the modified GravitinVirtualFileSystem code on the server and execute the command '/ gradlew :clients:filesystem-hadoop3-runtime:build -x test’， Afterwards, put the gravitino-firesystem-hadoop3-runtime-0.5.1.jar package into the/share/hadoop/common/lib directory and re request the HDFS command. The bug still exists. Is there anything wrong with this method?

Hi, you'd better confirm whether the relevant logic is really updated in the runtime jar you use. I have tested it in hadoop 2.7.3 and 3.1.0 according to the example in this issue, and I can get normal results in both.
![image](https://github.com/user-attachments/assets/fb41d3c4-d388-4928-bcde-7692a006b432)
![image](https://github.com/user-attachments/assets/be9dad98-d40f-44fc-bae5-718d47be7cac)

**Comment by jerryshao** [comment]
@heziyi399 would you please check again to see if @xloya 's PR really fix your problem? Thanks.

**Comment by heziyi399** [comment]
@jerryshao yes,the problem has been resolved. May I ask another question？I want to know if the file system can be converted to Hadoop's Distributed FileSystem, because when I try the following code:
` conf.set("fs.AbstractFileSystem.gvfs.impl","com.datastrato.gravitino.filesystem.hadoop.Gvfs");
        conf.set("fs.gvfs.impl","com.datastrato.gravitino.filesystem.hadoop.GravitinoVirtualFileSystem");
        conf.set("fs.gravitino.server.uri","http://localhost:8090");
conf.set("fs.gravitino.client.metalake","metalake_demo");
Path filesetPath = new Path("gvfs://fileset/test_catalog/hzySchema/example_fileset/");
        FileSystem fs = filesetPath.getFileSystem(conf);
        DistributedFileSystem dfs = (DistributedFileSystem) fs;`


an error message will appear "com.datastrato.gravitino.filesystem.hadoop.GravitinoVirtualFileSystem cannot be cast to org.apache.hadoop.hdfs.DistributedFileSystem"

**Comment by xloya** [comment]
> @jerryshao yes,the problem has been resolved. May I ask another question？I want to know if the file system can be converted to Hadoop's Distributed FileSystem, because when I try the following code: ` conf.set("fs.AbstractFileSystem.gvfs.impl","com.datastrato.gravitino.filesystem.hadoop.Gvfs"); conf.set("fs.gvfs.impl","com.datastrato.gravitino.filesystem.hadoop.GravitinoVirtualFileSystem"); conf.set("fs.gravitino.server.uri","http://localhost:8090"); conf.set("fs.gravitino.client.metalake","metalake_demo"); Path filesetPath = new Path("gvfs://fileset/test_catalog/hzySchema/example_fileset/"); FileSystem fs = filesetPath.getFileSystem(conf); DistributedFileSystem dfs = (DistributedFileSystem) fs;`
> 
> an error message will appear "com.datastrato.gravitino.filesystem.hadoop.GravitinoVirtualFileSystem cannot be cast to org.apache.hadoop.hdfs.DistributedFileSystem"

@heziyi399 `GravitinoVirtualFileSystem` extends the super abstract class `FileSystem`, so you cannot cast it to the `DistributedFileSystem` which also one of the child class for the `FileSystem`.

**Comment by jerryshao** [comment]
Thanks @xloya for your fix, thanks @heziyi399 for your report, greatly appreciated. This PR will be merged in to main and branch-0.6.
