### ISSUE TITLE
[Improvement] Possble null pointer exception in DorisTableOperations.java

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#4605]
### What would you like to be improved?

In the `appendNecessaryProperties` method, properties is checked for null in line 174 but still could be null in the if statement at line 184:
```
if (!properties.containsKey(REPLICATION_FACTOR)) 
```

### How should we improve?

Change code to avoid possible NPE.

**Comment by developer-rohith** [comment]
if (!properties.containsKey(REPLICATION_FACTOR))   keep this condition in the above else statement. Please find below updated code for reference
if (properties == null) {
      resultMap = new HashMap<>();
    } else {
      resultMap = new HashMap<>(properties);
      if (!properties.containsKey(REPLICATION_FACTOR)) {
      // Try to check the number of backend servers.
      String query = "select count(*) from information_schema.backends where Alive = 'true'";

      try (Connection connection = dataSource.getConnection();
          Statement statement = connection.createStatement();
          ResultSet resultSet = statement.executeQuery(query)) {
        while (resultSet.next()) {
          int backendCount = resultSet.getInt(1);
          if (backendCount < DEFAULT_REPLICATION_FACTOR_IN_SERVER_SIDE) {
            resultMap.put(
                REPLICATION_FACTOR,
                DORIS_TABLE_PROPERTIES_META
                    .propertyEntries()
                    .get(REPLICATION_FACTOR)
                    .getDefaultValue()
                    .toString());
          }
        }
      } catch (Exception e) {
        throw new RuntimeException("Failed to get the number of backend servers", e);
      }
    }
    }

NPE issue can be resolved by doing this.

**Comment by justinmclean** [comment]
@developer-rohith Please submit a PR if you want to fix this.

**Comment by developer-rohith** [comment]
@justinmclean Submitted PR. Please review it

**Comment by itsaviu** [comment]
Hi @justinmclean , seems the issue is been inactive for sometime. I have picked up and raise PR against, can you please review this. Thanks

**Comment by itsaviu** [comment]
@justinmclean , The changes has been merged to master we can close this issue, Thanks
cc: @yuqi1129
