### ISSUE TITLE
[Bug report] UI: scroll bar on the catalog detail page is no longer needed

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#4641]
### Version

main branch

### Describe what's wrong

<img width="405" alt="image" src="https://github.com/user-attachments/assets/c1ae5198-9bff-4eaa-be4a-e98184ad4b08">

### Error message and/or stacktrace

N/A

### How to reproduce

1. create a catalog
2. check detail page

**Comment by danhuawang** [comment]
@LauraXia123  how to handle the  scroll bar on the catalog detail page since long text is hidden ?

**Comment by LauraXia123** [comment]
The substring of value is 22 for now, we can set the length of substring smaller. But the scroll bar still work when open with sm screen. 
IMO, we can label the issue 'first good issue'

**Comment by LauraXia123** [comment]
<img width="514" alt="image" src="https://github.com/user-attachments/assets/95977243-d260-43fa-8e11-0a382dc245b5">
