### ISSUE TITLE
[Improvement] Trino connector binary package shouldn't contain trino-jdbc jar

### ISSUE THREAD

**Issue by jerqi** [apache/gravitino#4660]
### What would you like to be improved?

Trino connector binary package shouldn't contain trino-jdbc jar. We would better use the framework jar of Trino.

### How should we improve?

Make the dependency provided.

**Comment by LindaSummer** [comment]
Hi @jerqi ,

I want to work on this issue.
Could this task be assigned to me?

Best Regards,
Edward

**Comment by yuqi1129** [comment]
@LindaSummer 
Nice, I will assign it to you.

**Comment by LindaSummer** [comment]
Hi @jerqi ,

I apologize for the interruption.

After updating the `trino-jdbc` dependency in the `trino-connector` to be used only during the compile and test phases, I encountered the following exception when launching Trino 435.
`java.lang.NoClassDefFoundError: io/trino/jdbc/TrinoDriver`.

Upon investigating, I noticed that the dependencies for `TrinoServer` are defined within the [`trino-main`](https://github.com/trinodb/trino/blob/435/core/trino-main/pom.xml) module, but the `trino-jdbc` dependency is not listed there.

I may be misunderstanding this issue. Could you please provide some guidance or suggestion on this issue? 😊

Best Regards,
Edward

**Comment by jerqi** [comment]
> Hi @jerqi ,
> 
> I apologize for the interruption.
> 
> After updating the `trino-jdbc` dependency in the `trino-connector` to be used only during the compile and test phases, I encountered the following exception when launching Trino 435. `java.lang.NoClassDefFoundError: io/trino/jdbc/TrinoDriver`.
> 
> Upon investigating, I noticed that the dependencies for `TrinoServer` are defined within the [`trino-main`](https://github.com/trinodb/trino/blob/435/core/trino-main/pom.xml) module, but the `trino-jdbc` dependency is not listed there.
> 
> I may be misunderstanding this issue. Could you please provide some guidance or suggestion on this issue? 😊
> 
> Best Regards, Edward

Sorry. It won't be fixed. It's my fault. I ever thought the Trino has included this dependency. We can close this issue directly. Thanks for your efforet.
