### ISSUE TITLE
[Improvement] The release jar  should contains LICENSE and NOTICE

### ISSUE THREAD

**Issue by jerqi** [apache/gravitino#4661]
### What would you like to be improved?

The release jar  should contains LICENSE and NOTICE
Our jar is as below:
![12981724412057_ pic](https://github.com/user-attachments/assets/28718ef5-5bf3-41e3-8549-231cf0b0e11e)

Other project jar is as below:
![13001724412084_ pic](https://github.com/user-attachments/assets/a0352a90-e5c9-4a96-9006-2264c189d26f)

### How should we improve?

The release jar  should contains LICENSE and NOTICE

**Comment by yaoderek** [comment]
Hi @jerqi 

I want to work on this issue.
Could this task be assigned to me?

Derek

**Comment by jerqi** [comment]
> Hi @jerqi
> 
> I want to work on this issue. Could this task be assigned to me?
> 
> Derek

Thanks for your work.
