### ISSUE TITLE
[Bug report] React inline style - style prop expects a mapping from style properties to values, not a string

### ISSUE THREAD

**Issue by LauraXia123** [apache/gravitino#4685]
### Version

main branch

### Describe what's wrong

Setting inline styles in my React application. In this case, for a img
`<img src="https://analytics.apache.org/matomo.php?idsite=62&rec=1&bots=1&action_name=Overview" style="border:0;" alt="" />`

React tells me:
> Uncaught Invariant Violation: The style prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX. This DOM node was rendered by `SentenceView

### Error message and/or stacktrace

<img width="1804" alt="image" src="https://github.com/user-attachments/assets/1e5b1a09-483b-41d3-84b0-468b7982ea69">

### How to reproduce

N/A

**Comment by justinmclean** [comment]
The changes have broken the tracking and the raw HTML is display on the GitHub pages.

**Comment by justinmclean** [comment]
Removing the style tag may fix both?

**Comment by jerryshao** [comment]
@LauraXia123 can you please check this?

**Comment by LauraXia123** [comment]
@justinmclean  No styles are removed, and a different kind of support is syntactic sugar
<img width="1506" alt="image" src="https://github.com/user-attachments/assets/2a74ad9e-d190-486c-8fc0-a1a47e041d5c">
