### ISSUE TITLE
[Improvement] There are no LICENSE files in python and trino packages

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#4706]
### What would you like to be improved?

The released `apache_gravitino-0.6.0.tar.gz` and `gravitino-trino-connector-0.6.0-incubating.tar.gz` lack LICENSE files, is it a problem?

**Comment by FANNG1** [comment]
cc @justinmclean

**Comment by justinmclean** [comment]
Yes they do need a LICENSE, NOTICE and DISCLAIMER files.
