### ISSUE TITLE
[Improvement] Rename a metalake to an existing metalake

### ISSUE THREAD

**Issue by jerqi** [apache/gravitino#4735]
### What would you like to be improved?

![16611724845436_ pic](https://github.com/user-attachments/assets/587459ae-b15c-48ce-867a-5fb302028ed0)

### How should we improve?

We shouldn't throw SQL exception to front end. We should wrap to MetalakeAlreadyExistException.

**Comment by xloya** [comment]
Actually the duplicated key `SQLException` has been converted to `EntityAlreadyExistsException`, so I think it's best to optimize the exception information thrown here. I will check and change the exception information thrown here.
