### ISSUE TITLE
[Improvement]  Web should support to create Paimon Catalog

### ISSUE THREAD

**Issue by jerqi** [apache/gravitino#4736]
### What would you like to be improved?

![16581724845225_ pic](https://github.com/user-attachments/assets/8a868b04-b3e6-4ed9-a4cd-2771d88e4dff)

### How should we improve?

Web should support to create Paimon Catalog

**Comment by FANNG1** [comment]
Is it duplicated with #4742 ?

**Comment by jerqi** [comment]
> Is it duplicated with #4742 ?

Yes, but I open it earlier.

**Comment by YuanG0319tt** [comment]
I like to work with is task. could you assign me in?

**Comment by FANNG1** [comment]
> I like to work with is task. could you assign me in?

@YuanG0319tt  thanks for your interest, this is resolved by #4931
