### ISSUE TITLE
[Bug report] (UI) Create catalog success but the web page show error

### ISSUE THREAD

**Issue by yuqi1129** [apache/gravitino#4738]
### Version

0.6.0

### Describe what's wrong

<img width="1921" alt="image" src="https://github.com/user-attachments/assets/58d025df-26ba-4f38-8ea1-a343db1fb80b">

### Error message and/or stacktrace

Please see above

### How to reproduce

Please see above

**Comment by jerryshao** [comment]
@LauraXia123 can you please take a look at this issue?

**Comment by yuqi1129** [comment]
It can't be reproduced locally, so close it temporarily.
