### ISSUE TITLE
[Improvement] The ui does not support creating paimon catalog

### ISSUE THREAD

**Issue by caican00** [apache/gravitino#4742]
### What would you like to be improved?

The ui does not support creating paimon catalog
![image](https://github.com/user-attachments/assets/f11b9e22-5cf3-4ffd-9326-b87e0fe6cee0)

**Comment by FANNG1** [comment]
@LauraXia123 , you could refer to the latest Paimon catalog document for the catalog properties. like `catalog-backend`, `warehouse`. And the provider is `lakehouse-paimon`

**Comment by LauraXia123** [comment]
The ui will support paimon next version.
