### ISSUE TITLE
[FEATURE] trino connector support more Iceberg partitions

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#4757]
### Describe the feature

trino connector support more Iceberg partitions

### Motivation

For a table created with non identify partition, trino failed to query the data.
```
create table abcd(a int, b int) partitioned by (bucket(2,a))  TBLPROPERTIES ('format-version'='2', 'write.merge.mode'='merge-on-read', 'write.delete.mode'='merge-on-read');
```

Query 20240829_032202_00093_fk3q7 failed: class org.apache.gravitino.rel.expressions.transforms.Transforms$BucketTransform cannot be cast to class org.apache.gravitino.rel.expressions.transforms.Transform$SingleFieldTransform (org.apache.gravitino.rel.expressions.transforms.Transforms$BucketTransform and org.apache.gravitino.rel.expressions.transforms.Transform$SingleFieldTransform are in unnamed module of loader io.trino.server.PluginClassLoader @366fd3cb)

**Comment by diqiu50** [comment]
Trino only support the partitioning like this patten `partitioning = ARRAY['c1', 'c2']`

**Comment by diqiu50** [comment]
@mchades @yuqi1129 How can we solve the problem of the `Transform expression parser`

**Comment by diqiu50** [comment]
At least, we need to fix the query issues.

**Comment by mchades** [comment]
> @mchades @yuqi1129 How can we solve the problem of the `Transform expression parser` to handle the string `bucket(a, 2)` and Transform

Trino Iceberg connector supports this, I think you can reference its codes.
Here is the doc: https://trino.io/docs/current/connector/iceberg.html#partitioned-tables
