### ISSUE TITLE
[Improvement] how to specify Iceberg table location 

### ISSUE THREAD

**Issue by mchades** [apache/gravitino#4758]
### What would you like to be improved?

For Iceberg table location, here are three different treatment:

 - For [Trino Iceberg connector](https://trino.io/docs/current/connector/iceberg.html#table-properties): supports specifying `location` when creating an Iceberg table.
 - For Trino Gravitino connector: does not support specify the `location` for creating an Iceberg table
 - For [Gravitino Iceberg catalog](https://datastrato.ai/docs/latest/lakehouse-iceberg-catalog#table-properties): the property is reserved and cannot be passed

### How should we improve?

We should clarify the usage of `location` for Iceberg table and unify it.

**Comment by mchades** [comment]
@FANNG1 @diqiu50 cc

**Comment by diqiu50** [comment]
@mchades The Gravitino Trino connector supports  specify the `location` for creating an Iceberg table.

**Comment by mchades** [comment]
> @mchades The Gravitino Trino connector supports specify the `location` for creating an Iceberg table.

I cannot find it in the document.

**Comment by FANNG1** [comment]
`location` is not a reserved property in Iceberg, it's a mistake.
