### ISSUE TITLE
[Bug report] Unexpected information about build directory for python document

### ISSUE THREAD

**Issue by yuqi1129** [apache/gravitino#4766]
### Version

0.6.0

### Describe what's wrong

<img width="1351" alt="image" src="https://github.com/user-attachments/assets/1d798012-aa07-486a-ad19-ee140e15e8ab">

### Error message and/or stacktrace

Please see above. 

### How to reproduce

Please see above.

**Comment by jerryshao** [comment]
This is already fixed.
