### ISSUE TITLE
[Improvement] rest api doc: "METALAKE" in metadataObjectType  possible values doesn't make sense (associate-tags, list-object-tags rest api page)

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#4809]
### Version

main branch

### Describe what's wrong

 in associate-tags, list-object-tags, get-object-tag rest api page
http://52.195.42.58:3003/docs/latest/api/rest/associate-tags
http://52.195.42.58:3003/docs/latest/api/rest/list-object-tags
http://52.195.42.58:3003/docs/latest/api/rest/get-object-tag

<img width="691" alt="image" src="https://github.com/user-attachments/assets/062228cc-ae93-4003-b514-1ac555475ca5">

As METALAKE is unsupported metadata object type when I call the api, suggest remove METALAKE from possible values

### Error message and/or stacktrace

N/A

### How to reproduce

N/A

**Comment by danhuawang** [comment]
@jerryshao  Can you help confirm if this is a doc problem ?

**Comment by jerryshao** [comment]
Yes, this "METALAKE" is added by @jerqi , it's just a doc problem, I will figure out how to well address this problem.

**Comment by jerryshao** [comment]
I will add more docs to clearly describe it.
