### ISSUE TITLE
[Improvement] Response code from Gravitino server will make frontend page 404

### ISSUE THREAD

**Issue by yuqi1129** [apache/gravitino#4831]
### What would you like to be improved?

Some API of the Gravitino server will return a 404 if entities are not found, it's not so proper to return 404 since 404 means web pages are NOT found. 

### How should we improve?

Improving the response code for some REST API.

**Comment by yuqi1129** [comment]
@jerqi 
This is the issue. We can work together to make this improvement.

**Comment by jerqi** [comment]
For access control API, I will change some 404 code to 400. More details you can see https://github.com/apache/gravitino/issues/5105

**Comment by yuqi1129** [comment]
Close it as it has been fixed.
