### ISSUE TITLE
[Subtask] Propose a draft design to add OceanBase JDBC Catalog Support

### ISSUE THREAD

**Issue by yuanoOo** [apache/gravitino#4849]
### Describe the subtask

This issue tracks the design work for the OceanBase JDBC catalog.

### Parent issue

#4848

**Comment by yuanoOo** [comment]
Here is the design document. Please feel free to leave your comments.

https://docs.google.com/document/d/19IQNeh-tXmgOIbDuy8yMSoqDpl-jp26HjvlR5ByeQLY/edit?usp=sharing

**Comment by mchades** [comment]
The design looks fine overall. I'm going to close this issue, thanks @yuanoOo for bringing it up
