### ISSUE TITLE
[Bug report] doc: Datatype in some catalog doc should be correct

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#4956]
### Version

main branch

### Describe what's wrong

Gravitino support column type is listed in this page: https://gravitino.apache.org/docs/0.6.0-incubating/manage-relational-metadata-using-gravitino#apache-gravitino-table-column-type
In this column type table, there's only 'List' Datatype ,but in gravitino support catalog doc, some appear as 'Array',some appear as 'List'. It should be consistent.
<img width="941" alt="image" src="https://github.com/user-attachments/assets/da7ba4c2-dbb5-4927-a748-261b179c6a2d">

In catalog page:
https://gravitino.apache.org/docs/0.6.0-incubating/lakehouse-iceberg-catalog/#table-column-types
<img width="460" alt="image" src="https://github.com/user-attachments/assets/49da0380-8bd5-46b3-b0bd-61478d8d694f">

https://gravitino.apache.org/docs/0.6.0-incubating/apache-hive-catalog/#table-column-types
<img width="503" alt="image" src="https://github.com/user-attachments/assets/da163325-3d45-4a2a-80cd-2402065a2ab5">

<img width="512" alt="image" src="https://github.com/user-attachments/assets/d2f173f5-1521-4040-86d6-07a5a3e0aa86">

https://gravitino.apache.org/docs/0.6.0-incubating/lakehouse-paimon-catalog/#table-column-types
<img width="644" alt="image" src="https://github.com/user-attachments/assets/1ac60678-ffcd-479e-82f4-501b3c67b7e5">

### Error message and/or stacktrace

N/A

### How to reproduce

N/A

**Comment by jerryshao** [comment]
@mchades would you please help to check this?

**Comment by lsyulong** [comment]
Hello, can I come and take a look at this question? I will communicate with you if there are any further questions

**Comment by jerryshao** [comment]
Sure, please go ahead, if you have further question, you can leave message here, or ping @mchades .

**Comment by lsyulong** [comment]
> Sure, please go ahead, if you have further question, you can leave message here, or ping @mchades .

Hello, I have modified the corresponding data type mapping in the document. Please check if there are any issues on your end
