### ISSUE TITLE
[Improvement] Unify the modification behavior of the comment field.

### ISSUE THREAD

**Issue by mchades** [apache/gravitino#4968]
### What would you like to be improved?

Currently, only the fileset supports the `removeComment` change; other entities like catalog and table only support `updateComment` changes. Additionally, `newComment` cannot be null or an empty string. We should unify this behavior.

### How should we improve?

Unify the modification behavior of the comment field：
 - deprecated the `removeComment` change
 - the new comment of `updateComment` supports null and empty string

**Comment by koonchen** [comment]
@mchades i want to have a try.

**Comment by mchades** [comment]
@koonchen No problem! Please go ahead and feel free to ping me if you have any questions

**Comment by AbhiSharmaNIT** [comment]
Deprecate the removeComment change across all entities.
Reasoning: With the new behavior of updateComment (detailed below), removal of comments can be handled using this existing operation instead of a separate change type.

**Comment by AbhiSharmaNIT** [comment]
Allow null or empty string as valid values for newComment in updateComment.
If newComment is null or an empty string, it should be interpreted as removing the comment.

**Comment by mchades** [comment]
@AbhiSharmaNIT Yeah, you summed it up correctly!

I have not seen @koonchen  submit the relevant PR so far, so I think if you are interested in this issue, you can also submit a PR.

**Comment by koonchen** [comment]
@mchades this week is a national holiday, and you didn't assign me

**Comment by mchades** [comment]
> @mchades this week is a national holiday, and you didn't assign me

assign is not a required step, you can start at any time.

**Comment by koonchen** [comment]
@mchades I don't think so. You need to let others know the urgency and responsibility of the matter.

**Comment by mchades** [comment]
> @mchades I don't think so. You need to let others know the urgency and responsibility of the matter.

I think the comments on the issue are sufficient. If you care about this, it has been assigned to you now, so please start as soon as possible. 

Others can also submit at any time before relevant PRs are submitted.
