### ISSUE TITLE
[Improvement] Make property `cloud.name` and `cloud.region-code` mutable

### ISSUE THREAD

**Issue by mchades** [apache/gravitino#4999]
### What would you like to be improved?

Because there is a possibility that the creation was filled in incorrectly, or that the region changed as the URL of the catalog changed, we should allow modification of these two properties

### How should we improve?

Make property `cloud.name` and `cloud.region-code` mutable

**Comment by LindaSummer** [comment]
Hi @mchades ,

I want to follow up this issue.

Can it be assigned to me?

Best Regards,
Edward

**Comment by mchades** [comment]
Sure, assigned. @LindaSummer

**Comment by LindaSummer** [comment]
Hi @mchades ,

Sorry to bother you.

I'm not sure related test case should be put in which test class.

Could you give me some advice?

Best Regards,
Edward

**Comment by mchades** [comment]
You can modify the tests:
https://github.com/apache/gravitino/blob/a89fe92506221d2d2f7a90c2c8681befdca074e7/catalogs/catalog-hive/src/test/java/org/apache/gravitino/catalog/hive/TestHiveCatalogOperations.java#L105-L106

and add integration tests to here:
https://github.com/apache/gravitino/blob/a89fe92506221d2d2f7a90c2c8681befdca074e7/clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/CatalogIT.java#L45
