### ISSUE TITLE
[Improvement][catalog-lakehouse-paimon] make some table properties from reserved to immutable

### ISSUE THREAD

**Issue by caican00** [apache/gravitino#5094]
### What would you like to be improved?

make some table properties from reserved to immutable.

```
bucket-key
merge-engine
sequence.field
rowkind.field
primary-key
partition
```

**Comment by mchades** [comment]
For which catalog?

**Comment by FANNG1** [comment]
why remove the properties from reserved? such as  `primary-key` and `bucket-key` should be set using `index` and `distribution` interfaces not by using properties.

**Comment by FANNG1** [comment]
IMO,  we could make `merge-engine` , `sequence.field`, `rowkind.field` to immutable, @caican00 WDYT?

**Comment by caican00** [comment]
> For which catalog?

paimon

**Comment by caican00** [comment]
> IMO, we could make `merge-engine` , `sequence.field`, `rowkind.field` to immutable, @caican00 WDYT?

yes, it is resonable. i will update the related pr.

**Comment by caican00** [comment]
> > IMO, we could make `merge-engine` , `sequence.field`, `rowkind.field` to immutable, @caican00 WDYT?
> 
> yes, it is resonable. i will update the related pr.

@FANNG1 please review again
