### ISSUE TITLE
[Improvement] README.md should refer the link to our doc website but not doc's source directory

### ISSUE THREAD

**Issue by JunpingDu** [apache/gravitino#5109]
### What would you like to be improved?

README.md is the front page for an open source project, and most users try to locate the related documents they need.
Usually it should link to a document website (if project has), such as spark, ray, etc. which is more convenient for users to read - comparing with our source doc in markdown format.

### How should we improve?

Replace the link that point to doc source with link to doc site (latest version).

**Comment by SeanAverS** [comment]
Hi, 

I'm interested on working on this. Could I please be assigned? Thanks.

**Comment by yuqi1129** [comment]
> Hi, 
> 
> 
> 
> I'm interested on working on this. Could I please be assigned? Thanks. 

Sure,please go ahead.

**Comment by JunpingDu** [comment]
Thanks for the patch, @SeanAverS ! I have some review comments in your PR, would you take a look? thx!

**Comment by JunpingDu** [comment]
Thanks for your contribution, @SeanAverS .
Also, Congratulations on the first gravitino patch! :)
