### ISSUE TITLE
Add Tag support to Gravitino CLI

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5131]
Add the ability to use tags:
- List, create, delete, and rename tags.
- Add/remove tag properties.
- Update a tag's comment.
- Associate and disassociate tags on objects.

**Comment by Saintyang** [comment]
maybe we could add tag group to manage similar tags?

**Comment by justinmclean** [comment]
Thanks for teh suggestion. The CLI just uses the Java API, which doesn't have a concept of tag groups. If that feature was added to the CLI, it could be supported by the CLI.

**Comment by Saintyang** [comment]
> Thanks for the suggestion. The CLI just uses the Java API, which doesn't have a concept of tag groups. If that feature was added to the Java API, it could be supported by the CLI.

Got it,what I mean exactly is we can add tag group to manage tag. I will open a new issue to discuss this. thanks for reply!

**Comment by justinmclean** [comment]
Fixed and merged in #5161
