### ISSUE TITLE
[Bug report] Display users Java API on playground fails

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5132]
### Version

main branch

### Describe what's wrong

Try to display roles and this error occurs:
Unable to process: Error code: 405, error message: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0], json string: 

### Error message and/or stacktrace

see above

### How to reproduce

Start the playground and list role via the Java API and call the `listUserNames` method in GravitinoClient.

### Additional context

I assume this is because no users exist? If so the API should handle this situation.

Note that other calls to create or delete users give this error below, so while the playground doesn't support users, that error should probably not occur.
```You should set 'gravitino.authorization.enable' to true in the server side `gravitino.conf` to enable the authorization of the system, otherwise these interfaces can't work.```

**Comment by jerqi** [comment]
What's your Gravitino client version?

**Comment by jerqi** [comment]
Playground uses 0.6.0. We supports `list roles` in 0.6.1 and 0.7.0. It's expected behaviour.
