### ISSUE TITLE
[Bug report] OB catalog UTs failed on Mac

### ISSUE THREAD

**Issue by mchades** [apache/gravitino#5152]
### Version

main branch

### Describe what's wrong

OB catalog UTs failed on Mac

### Error message and/or stacktrace

The OB Docker log can be found:

> [ERROR] OBD-1007: (192.168.215.2) The value of the ulimit parameter "max user processes" must not be less than 120000 (Current value: 56081), Please execute `echo -e "* soft nproc 120000\n* hard nproc 120000" >> /etc/security/limits.d/nproc.conf` as root in 192.168.215.2. if it dosen't work, please check whether UsePAM is yes in /etc/ssh/sshd_config.

### How to reproduce

pull the main branch and run `./gradlew :catalogs:catalog-jdbc-oceanbase:test -PskipDockerTests=false` on MacOS

### Additional context

modify code below of `org.apache.gravitino.integration.test.container.BaseContainer` can fix.
```java
this.container =
        new GenericContainer<>(requireNonNull(image, "image is null"))
            .withCreateContainerCmdModifier(
                cmd ->
                    cmd.getHostConfig()
                        .withSysctls(
                            Collections.singletonMap("net.ipv4.ip_local_port_range", "20000 40000"))
                        .withUlimits(new Ulimit[] {new Ulimit("nproc", 120000L, 120000L)}));
```

**Comment by unfixa1** [comment]
This can be fixed by modifying the code in org.apache.gravitino.integration.test.container.BaseContainer :
this.container =
    new GenericContainer<>(requireNonNull(image, "image is null"))
        .withCreateContainerCmdModifier(
            cmd ->
                cmd.getHostConfig()
                    .withSysctls(
                        Collections.singletonMap("net.ipv4.ip_local_port_range", "20000 40000"))
                    .withUlimits(new Ulimit[] {new Ulimit("nproc", 120000L, 120000L)}));


In addition, you should use [Servbay](servbay.com) to check your development environment, which is more useful than Docker on Mac.

**Comment by mchades** [comment]
> In addition, you should use [Servbay](servbay.com) to check your development environment, which is more useful than Docker on Mac.

Hi @unfixa1 , can you explain more? The link to Servbay seems broken

**Comment by mchades** [comment]
@featherchen 
Could you please leave a message here so that I can assign this issue to you?
