### ISSUE TITLE
[Bug report] Iceberg catalog audit user is not correct

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#5172]
### Version

main branch

### Describe what's wrong

It's not correct to use `currentUser` in `IcebergCatalogOperations.java`, should use `PrincipalUtils.getCurrentUserName()` instread
```java
              .withAuditInfo(
                  AuditInfo.builder()
                      .withCreator(currentUser())
                      .withCreateTime(Instant.now())
                      .build())
              .build();

  private static String currentUser() {
    return System.getProperty("user.name");
  }
```

### Error message and/or stacktrace

no

### How to reproduce

no

**Comment by lsyulong** [comment]
![image](https://github.com/user-attachments/assets/4a85282f-f9c4-4351-aa1f-4121c3c9ddb1)
This way of writing cannot solve this problem

**Comment by yuqi1129** [comment]
> ![image](https://private-user-images.githubusercontent.com/39983196/378043921-4a85282f-f9c4-4351-aa1f-4121c3c9ddb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMTM4NjQsIm5iZiI6MTcyOTMxMzU2NCwicGF0aCI6Ii8zOTk4MzE5Ni8zNzgwNDM5MjEtNGE4NTI4MmYtZjljNC00MzUxLWFhMWYtNDEyMWMzYzlkZGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDA0NTI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiOWUxNGQyMDUxMDdkMjliMTI2NTkxNTZkNDk2ZjM1NGY2Yjg2YjY2NjIyNjQ0YjY4YzY5YTQ3MDE0ZDg4ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mnev--IciHys_Zfg1EPMhEwcwNiXbH41b89o7Gwv4AE) This way of writing cannot solve this problem

You can boost a PR if you like.

**Comment by lsyulong** [comment]
> > <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/39983196/378043921-4a85282f-f9c4-4351-aa1f-4121c3c9ddb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMTM4NjQsIm5iZiI6MTcyOTMxMzU2NCwicGF0aCI6Ii8zOTk4MzE5Ni8zNzgwNDM5MjEtNGE4NTI4MmYtZjljNC00MzUxLWFhMWYtNDEyMWMzYzlkZGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDA0NTI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiOWUxNGQyMDUxMDdkMjliMTI2NTkxNTZkNDk2ZjM1NGY2Yjg2YjY2NjIyNjQ0YjY4YzY5YTQ3MDE0ZDg4ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mnev--IciHys_Zfg1EPMhEwcwNiXbH41b89o7Gwv4AE"> This way of writing cannot solve this problem <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/39983196/378043921-4a85282f-f9c4-4351-aa1f-4121c3c9ddb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMTM4NjQsIm5iZiI6MTcyOTMxMzU2NCwicGF0aCI6Ii8zOTk4MzE5Ni8zNzgwNDM5MjEtNGE4NTI4MmYtZjljNC00MzUxLWFhMWYtNDEyMWMzYzlkZGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDA0NTI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiOWUxNGQyMDUxMDdkMjliMTI2NTkxNTZkNDk2ZjM1NGY2Yjg2YjY2NjIyNjQ0YjY4YzY5YTQ3MDE0ZDg4ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mnev--IciHys_Zfg1EPMhEwcwNiXbH41b89o7Gwv4AE"> 这种写法不能解决这个问题
> 
> You can boost a PR if you like.如果您愿意，您可以提高 PR。

ok
