### ISSUE TITLE
[Improvement] Add the link to gravitino-playgound into README

### ISSUE THREAD

**Issue by shaofengshi** [apache/gravitino#5175]
### What would you like to be improved?

Some users suggest us to add the playgound link to Gravitino homepage as well as code repository, so that a new user can quickly know there is such a quick way to evaluate Gravitino.

### How should we improve?

Add the link to README, such like what it introduces in https://gravitino.apache.org/docs/0.6.0-incubating/

**Comment by Brijeshthummar02** [comment]
@shaofengshi i can work on it, assign me the task.

**Comment by Brijeshthummar02** [comment]
@shaofengshi can you provide me link and also suggest at where i should place it at end of quickstart guide or start of it.

**Comment by shaofengshi** [comment]
Hello @Brijeshthummar02 , I created a PR for this issue yesterday (the github wasn't able to link with this automatically: https://github.com/apache/gravitino/pull/5184 ).

Here has another issue which still doesn't have assignee; would you like to work on it? The link is https://github.com/apache/gravitino-site/issues/28

**Comment by Brijeshthummar02** [comment]
@shaofengshi Sure I'll be going through the issue once get the time, also can you provide relative path and other useful info for the issue #28 would be very helpful to kick start it.
