### ISSUE TITLE
[FEATURE] support paimon JDBC and hive backend in WEB UI

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#5185]
### Describe the feature

Support paimon JDBC and hive backend in WEB UI.
For JDBC backend, it's required to add `jdbc-user` and `jdbc-password` options.
For Hive backend, no extra configuration is needed.

**Comment by LauraXia123** [comment]
@FANNG1 For JDBC backend, dose it need `jdbc-driver` option?

**Comment by LauraXia123** [comment]
<img width="614" alt="image" src="https://github.com/user-attachments/assets/3635e702-3b4e-4178-9724-614a92663c1c">
<img width="598" alt="image" src="https://github.com/user-attachments/assets/38f75ee1-38b6-43a7-800d-1d9c2985a30f">
<img width="619" alt="image" src="https://github.com/user-attachments/assets/3c673719-9b66-47ad-960b-c2b1aa3bb508">
@FANNG1  please help to have a check?

**Comment by FANNG1** [comment]
> @FANNG1 For JDBC backend, dose it need `jdbc-driver` option?

not need it currently
