### ISSUE TITLE
[Improvement] OceanBase Test requied large memory to start the container

### ISSUE THREAD

**Issue by featherchen** [apache/gravitino#5189]
### What would you like to be improved?

The default memory requiement is 6G, which often cause OBD2000 ERROR in some local machines. 

### How should we improve?

Based on the related part of https://en.oceanbase.com/docs/community-obd-en-10000000001177834, we can reduce the memory limit of the container.

**Comment by featherchen** [comment]
From the official tutorial (https://en.oceanbase.com/docs/community-obd-en-10000000001177834), the memory limit of our currently version OB can not be lower than 6G, which is aligned with the result when I tried to reduce the memory limit when starting a test container. 

Seems that this question can not be solved under current test structure, @mchades what do you think?

**Comment by mchades** [comment]
@yuanoOo could you plz help to take a look?

**Comment by yuanoOo** [comment]
@featherchen I consulted and found that this problem cannot be solved for the time being. The memory needs to be at least 6G, and the disk can be smaller. Also, slim mode will only start faster.

**Comment by mchades** [comment]
So it's the hard limit of the OBD, I suggest disabling OB docker tests by default and the developers can enable them manually if needed
WDYT? @yuanoOo @featherchen

**Comment by featherchen** [comment]
@mchades @yuanoOo  I agreed with the disabling by default. Btw,  Do we need also to create macOS runner in CI of backend integration? If so, we might not need to test such changes (e.g. #5152) locally.

**Comment by yuanoOo** [comment]
@mchades @featherchen If ob is disabled by default on github ci, ob-catalog may be easily introduce some bugs because they are not tested. This is probably not a good choice.

**Comment by featherchen** [comment]
@yuanoOo Maybe we can use env variable to customize CI setting if needed, however this might also increase the complexity there

**Comment by mchades** [comment]
As the OB tests have `@Tag("gravitino-docker-test")`, they will be disabled by default.

The memory requirement is a hard limitation of the OceanBase Docker, and currently, there is no action we can take. Therefore, I will close the issue. Please feel free to reopen it if necessary.
