### ISSUE TITLE
[Subtask] Support Colume data type

### ISSUE THREAD

**Issue by unknowntpo** [apache/gravitino#5200]
### Describe the subtask

Support Column data type
[docs](https://gravitino.apache.org/docs/0.6.1-incubating/manage-relational-metadata-using-gravitino#apache-gravitino-table-column-type)
related java issue: https://github.com/apache/gravitino/issues/599 https://github.com/apache/gravitino/issues/3427

### Parent issue

#5198

**Comment by mchades** [comment]
@SophieTech88  Could you kindly leave a message here so that I can assign the issue to you?

**Comment by SophieTech88** [comment]
> @SophieTech88 Could you kindly leave a message here so that I can assign the issue to you?

Thanks for your reminder.
Can I work on this issue?
