### ISSUE TITLE
[Subtask] Support Expression system

### ISSUE THREAD

**Issue by unknowntpo** [apache/gravitino#5201]
### Describe the subtask

Support Expression system
[docs](https://gravitino.apache.org/docs/0.6.1-incubating/expression)
related java issue: https://github.com/apache/gravitino/issues/600

### Parent issue

#5198

**Comment by SophieTech88** [comment]
Can I work on this issue?

**Comment by SophieTech88** [comment]
I noticed that the file [expressions/Literal.java](https://github.com/SophieTech88/gravitino/blob/main/api/src/main/java/org/apache/gravitino/rel/expressions/Literal.java#L31 ) includes the comment: `@deprecated This interface will be removed`. Additionally, there’s a folder `expressions/literals/` containing two files: `Literal.java` and `Literals.java`. 

For the Python client, which of these files should I implement? Should I focus on the new implementation in expressions/literals/, or is there a need to maintain compatibility with the deprecated interface?

**Comment by SophieTech88** [comment]
Another question: under the expressions folder, there are several subfolders like `distributions`, `sorts`, `transforms`, and `literals`, as well as files such as `Expression.java`, `FunctionExpression.java`, `Literal.java`, `NamedReference.java`, and `UnparsedExpression.java`. 

Could you confirm if all of these need to be converted into Python client interfaces, or are there specific ones I should focus on?
