### ISSUE TITLE
[Improvement] Opt out of Next.js usage telemetry

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5212]
### What would you like to be improved?

It seems Next.js  now tracks usage:
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

### How should we improve?

Opt out of using usage telemetry as this is not in line with the ASF privacy policy.

**Comment by jerryshao** [comment]
@LauraXia123 can you please take a look at this?
