### ISSUE TITLE
[Improvement] Fix the flaky test

### ISSUE THREAD

**Issue by jerryshao** [apache/gravitino#5213]
### What would you like to be improved?

The UT here is quite flaky, the socket timeout issue will be met several times, we should either increase the timeout or add the retry time.

https://github.com/apache/gravitino/actions/runs/11454056850/job/31867546330

**Comment by jerryshao** [comment]
@featherchen can you please leave a comment here, so I can assign this issue to you.

**Comment by featherchen** [comment]
Sure, Thanks for the review

**Comment by jerryshao** [comment]
Reopen this issue, since the test is still quite flaky.
