### ISSUE TITLE
[Improvement] add jdbc-driver to Paimon JDBC catalog backend configuration

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#5214]
### What would you like to be improved?

Add jdbc-driver to Paimon JDBC catalog backend configuration like Iceberg JDBC catalog backend.  Because the default JDBC service loader will load just initialized once in Gravitino, this may leading load just one Jdbc driver in a specific catalog, will not load the other JDBC driver in other catalogs, we should invoke  class.forName(driverClass) explictly.

**Comment by FANNG1** [comment]
cc @caican00  please help to check this when you have time, thanks

**Comment by caican00** [comment]
> cc @caican00 please help to check this when you have time, thanks

@FANNG1 ok, thanks for pointing out this issue

**Comment by caican00** [comment]
> Hi @caican00 will you do this in 0.7 release?

Hi @jerryshao i will finish it today or tomorrow.

**Comment by FANNG1** [comment]
@LauraXia123 , please add `jdbc-driver` properties for Paimon JDBC catalog backend  in WEB like Iceberg, thanks
