### ISSUE TITLE
[FEATURE] How to use Gravitino to manage metadata for individual files instead of metadata for file sets.

### ISSUE THREAD

**Issue by DreamFlyCBX** [apache/gravitino#5229]
### Describe the feature

I have now implemented the integration of Gravitino and Hadoop, but I found that it can only create directories and not files. I would like to ask how to use Gravitino to manage file metadata.

**Comment by xloya** [comment]
@DreamFlyCBX You can refer the GVFS client document to create files under Fileset: https://gravitino.apache.org/docs/0.6.1-incubating/how-to-use-gvfs.

**Comment by DreamFlyCBX** [comment]
![1729676999889](https://github.com/user-attachments/assets/36ed1b1e-3321-4c85-b140-c270260fc8e5)
Thank you for your reply. For example, in the image, "test" is a directory, not a file. Therefore, I would like to know how to create a file.

**Comment by DreamFlyCBX** [comment]
> @DreamFlyCBX You can refer the GVFS client document to create files under Fileset: https://gravitino.apache.org/docs/0.6.1-incubating/how-to-use-gvfs.

Thank you for your reply. For example, in the image, "test" is a directory, not a file. Therefore, I would like to know how to create a file.

**Comment by xloya** [comment]
@DreamFlyCBX The server open api only supports to manage the fileset's metadata, like the table's metadata. if you want to create files under the fileset, you should use the Java GVFS client / Python GVFS client in the document which I show you above.

**Comment by DreamFlyCBX** [comment]
@xloya Thank you very much for your reply. I have many questions regarding usage. Is there a way to get in touch for further assistance?

**Comment by xloya** [comment]
> @xloya Thank you very much for your reply. I have many questions regarding usage. Is there a way to get in touch for further assistance?

You could join the slack channel, there will be a chat room for the community, see: https://gravitino.apache.org/community.

**Comment by DreamFlyCBX** [comment]
@xloya Thank you very much .
