### ISSUE TITLE
[Improvement] Display audit information on Metalakes in the Gravitino CLI

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5276]
### What would you like to be improved?

Have a command to display audit information for Metalakes.

### How should we improve?

This can be done by:
- Adding a new CLI command to display audit information (creator, create time, modifier and modified time) by calling `auditInfo` on the Metalake object.
- Adding a new command option `--audit`
- Adding the command to `GravitinoCommandLine`
- Updating user documentation

**Comment by lsyulong** [comment]
I want to try it, but I don't know how to modify it. Can you help me

**Comment by justinmclean** [comment]
Thanks for offering to help, it may be best if you try one thing first then help out with others.

**Comment by orenccl** [comment]
@justinmclean 
I would like to take over this issue and start working on it. Please let me know if I can proceed. Thank you!

**Comment by justinmclean** [comment]
Hi @orenccl thanks for offering to help.

To get started on this, have a look at the commands in `clients/cli/src/main/java/org/apache/gravitino/cli/commands/`, `MetalakeDetails.java` would be a good one to copy, create a new command called something like `MetalakeAuditInfo.java`. In that command call the `auditInfo()` method and print out the creator, create time, last modifier and last modified time (see `Audit.java` and `Auditable.java`).

Next, add an index option --audit to GravitinnoOptions.java and modify handleTableCommand in GravitionoCommandLine.java to create the new command when passed the new option and the details command. 

I would expect the command to be something like this:
gcli metalake details --metalake metalake_demo --audit

Finally, update the documentation in docs/cli.md adding the command to it.

**Comment by orenccl** [comment]
Thank you for your kind help.

I actually noticed earlier that you wrote an instruction on [[Improvement] Display index infromation for tables in the Gravitino CLI](https://github.com/apache/gravitino/issues/5277).

It's very clear and helpful!

I will keep you updated if I make any progress.
