### ISSUE TITLE
[Improvement] Display index infromation for tables in the Gravitino CLI

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5277]
### What would you like to be improved?

Have a command to display index information for Tables.

### How should we improve?

This can be done by:
- Adding a new CLI command to display index information by calling `index` on the Table object.
- Adding a new command option `--index`
- Adding the command to `GravitinoCommandLine`
- Updating user documentation

**Comment by lsyulong** [comment]
I want to try it, but I don't know how to modify it. Can you help me

**Comment by justinmclean** [comment]
Thanks for offering to help.

To get started on this, have a look at the commands in `clients/cli/src/main/java/org/apache/gravitino/cli/commands/`, `ListColumns.java` would be a good one to copy, create a new command called say`ListIndexes.java`. It would call the `index()` method from `loadTable()` to get information about the table's indexes, and print out the name and type of each index.
Next, add an index option to `GravitinnoOptions.java` and modify `handleTableCommand` in `GravitionoCommandLine.java` to create the new command when passed the new option and the details command. Compile and test the command with the Gravitino playground. I would expect the command to be like this:
`gcli table details --metalake metalake_demo --name catalog_postgres.hr.salaries --index`
Finally, update the documentation in `docs/cli.md` adding the command to it.

**Comment by justinmclean** [comment]
@lsyulong do you want to work on this?

**Comment by justinmclean** [comment]
@lsyulong Do you need any further help on this or should I assign it to someone else?

**Comment by justinmclean** [comment]
@lsyulong I've had no response from you, so I'm leaving this open for someone else to work on. If you want to work on it as some point in the future, please comment here.

**Comment by lsyulong** [comment]
Sorry, I've been busy with work lately and haven't replied

**Comment by orenccl** [comment]
I believe updating the documentation in docs/cli.md would be an improvement, as there is currently no section that lists all the commands. I can update them all; please let me know if you'd prefer that I open a separate improvement issue, or if it’s fine to include this update as part of this issue.

**Comment by justinmclean** [comment]
The CLI currently has multiple outstanding PR, and the cli.md has been updated in each one, just add teh usage underneath the Table command section at the end of the document.
