### ISSUE TITLE
[Improvement] Display partition information for Tables in the Gravitino CLI

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5278]
### What would you like to be improved?

Have a command to display partition information for Tables.

### How should we improve?

This can be done by:
- Adding a new CLI command to display partition information by calling `partitioning` on the Table object.
- Adding a new command option `--partition`
- Adding the command to `GravitinoCommandLine`
- Updating user documentation

**Comment by justinmclean** [comment]
Thanks for offering to help, it may be best if you try one thing first then help out with others.

**Comment by justinmclean** [comment]
Thanks for offering to help, it may be best if you try one thing first then help out with others.

**Comment by TungYuChiang** [comment]
Hi @justinmclean  , I have finished issue #5280, and this issue looks quite similar. May I take it on next?

**Comment by justinmclean** [comment]
Sure give it a go, if you need any help just ask.
