### ISSUE TITLE
[Improvement] Display sort order for tables in the Gravitino CLI

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5279]
### What would you like to be improved?

Have a command to display sort order information for Tables.

### How should we improve?

This can be done by:
- Adding a new CLI command to display sort order information by calling `sortOrder` on the Table object.
- Adding a new command option `--sortorder`
- Adding the command to `GravitinoCommandLine`
- Updating user documentation

**Comment by lsyulong** [comment]
I want to try it, but I don't know how to modify it. Can you help me

**Comment by justinmclean** [comment]
Thanks for offering to help, it may be best if you try one thing first then help out with others.

**Comment by TungYuChiang** [comment]
Hi @justinmclean , May I take it on next ? 
Thank you

**Comment by justinmclean** [comment]
Thanks for offering to help. If you need any assistance or have any questions, just ask.

**Comment by justinmclean** [comment]
@TungYuChiang how are you going with this?

**Comment by TungYuChiang** [comment]
I'll submit my PR tonight. Thank you for following up!
