### ISSUE TITLE
[Improvement] Display distribution / bucketing information for Tables in the Gravitino CLI

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5280]
### What would you like to be improved?

Have a command to display distribution / bucketing information for Tables.

### How should we improve?

This can be done by:
- Adding a new CLI command to distribution information by calling `distribution` on the Table object.
- Adding a new command option `--distribution`
- Adding the command to `GravitinoCommandLine`
- Updating user documentation

**Comment by lsyulong** [comment]
I want to try it, but I don't know how to modify it. Can you help me

**Comment by justinmclean** [comment]
Thanks for offering to help, it may be best if you try one thing first then help out with others.

**Comment by TungYuChiang** [comment]
Hi,  I'd like to contribute by working on this issue if it's available. Please let me know if I can take it on.

**Comment by TungYuChiang** [comment]
I've been addressing some issues with the Gravitino-playground over the past two days and will start working on the assignment today.
