### ISSUE TITLE
[Improvement] Some JDBC catalog properties should be defined as required

### ISSUE THREAD

**Issue by mchades** [apache/gravitino#5306]
### What would you like to be improved?

The following JDBC should be required not optional:
https://github.com/apache/gravitino/blob/955d527a741169d9d3502599c2a8027e61d5af56/catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/JdbcCatalogPropertiesMetadata.java#L64-L81

### How should we improve?

make them required

**Comment by lsyulong** [comment]
I want to try it, but I don't know how to modify it. Can you help me

**Comment by lsyulong** [comment]
> For example, change the code of `JDBC_DRIVER` to:
> 
> ```java
> stringPropertyEntry(
>                 JdbcConfig.JDBC_DRIVER.getKey(),
>                 JdbcConfig.JDBC_DRIVER.getDoc(),
>                 true /* required */,
>                 false /* immutable */,
>                 null /* defaultValue */,
>                 false /* hidden */,
>                 false /* reserved */)
> ```

ok,thanks

**Comment by lsyulong** [comment]
stringPropertyEntry(
                JdbcConfig.JDBC_DRIVER.getKey(),
                JdbcConfig.JDBC_DRIVER.getDoc(),
                true /* required */,
                false /* immutable */,
                null /* defaultValue */,
                false /* hidden */,
                false /* reserved */),
                stringPropertyEntry(
                JdbcConfig.USERNAME.getKey(),
                JdbcConfig.USERNAME.getDoc(),
                true /* required */,
                false /* immutable */,
                null /* defaultValue */,
                false /* hidden */,
                false /* reserved */),
                stringPropertyEntry(
                JdbcConfig.PASSWORD.getKey(),
                JdbcConfig.PASSWORD.getDoc(),
                true /* required */,
                false /* immutable */,
                null /* defaultValue */,
                false /* hidden */,
                false /* reserved */)

**Comment by lsyulong** [comment]
> ```
>             stringPropertyEntry(
>             JdbcConfig.JDBC_DRIVER.getKey(),
>             JdbcConfig.JDBC_DRIVER.getDoc(),
>             true /* required */,
>             false /* immutable */,
>             null /* defaultValue */,
>             false /* hidden */,
>             false /* reserved */),
>             stringPropertyEntry(
>             JdbcConfig.USERNAME.getKey(),
>             JdbcConfig.USERNAME.getDoc(),
>             true /* required */,
>             false /* immutable */,
>             null /* defaultValue */,
>             false /* hidden */,
>             false /* reserved */),
>             stringPropertyEntry(
>             JdbcConfig.PASSWORD.getKey(),
>             JdbcConfig.PASSWORD.getDoc(),
>             true /* required */,
>             false /* immutable */,
>             null /* defaultValue */,
>             false /* hidden */,
>             false /* reserved */)
> ```

Do you think there's a problem with this

**Comment by mchades** [comment]
> Do you think there's a problem with this

looks good
