### ISSUE TITLE
[Bug report] Open paimon catalog edit page,"jdbc-user","jdbc-password" are not filled, details page either.

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#5355]
### Version

main branch

### Describe what's wrong

<img width="293" alt="image" src="https://github.com/user-attachments/assets/6d83db86-fdbb-4912-9fc1-19bcea8a1f55">
<img width="394" alt="image" src="https://github.com/user-attachments/assets/359064bd-704c-45f9-a13e-a602f130d4f8">

### Error message and/or stacktrace

N/A

### How to reproduce

1. Create a paimon catalog with jdbc backend 
2. Open edit page
3. Open details page

**Comment by danhuawang** [comment]
@LauraXia123 Can you check this issue ?

**Comment by LauraXia123** [comment]
<img width="845" alt="image" src="https://github.com/user-attachments/assets/c095e175-4660-46b6-b348-cebf908c3f78">
request send the `jdbc-user` and `jdbc-password`
<img width="668" alt="image" src="https://github.com/user-attachments/assets/f7b260ca-2b35-44a9-ac7d-0e58974db636">
response miss the two properties

**Comment by danhuawang** [comment]
@FANNG1 Can you help check this issue ?

**Comment by FANNG1** [comment]
It's not proper we export the password and AKSK in catalog properties

**Comment by FANNG1** [comment]
Should Gravitino export the security information though catalog properties in the short term?  @jerryshao @yuqi1129 @jerqi @mchades @diqiu50 WDYT?

**Comment by mchades** [comment]
> Should Gravitino export the security information though catalog properties in the short term? 

It must be, otherwise Trino connector can not work
