### ISSUE TITLE
[Subtask] add schema event for Iceberg REST server

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#5437]
### Describe the subtask

Please refer to https://github.com/apache/gravitino/issues/4958 and https://github.com/apache/gravitino/issues/5205 about how to support table event. You may need to implement a `IcebergSchemaOperationDispatcher` `IcebergSchemaEventDispatcher`  like `IcebergTableOperationDispatcher` `IcebergTableEventDispatcher`

### Parent issue

#5204

**Comment by orenccl** [comment]
I’ll work on this within a few days.

**Comment by FANNG1** [comment]
thanks @orenccl
