### ISSUE TITLE
[FEATURE] Support web ui for creating topic

### ISSUE THREAD

**Issue by LauraXia123** [apache/gravitino#5447]
### Describe the feature

Operation flow:
1. Creating a catalog with type: `messaging` and provider: `Apache Kafka`
2. Clicking the `default` schema of kafka catalog
3. Need a btn `CREATE TOPIC` with plus icon

<img width="1417" alt="image" src="https://github.com/user-attachments/assets/de397d2a-231d-4877-a71b-cd49568e0776">
<img width="217" alt="image" src="https://github.com/user-attachments/assets/591d8835-04eb-4726-86d0-06c65b5b83b9">
And need a dialog for creating topic
<img width="599" alt="image" src="https://github.com/user-attachments/assets/b9d0e7b2-1a72-4af9-aae7-667c6a0affdd">

You can find the open api doc here: https://gravitino.apache.org/docs/0.6.1-incubating/api/rest/create-topic

**Comment by orenccl** [comment]
I would like to take this task

**Comment by alan910127** [comment]
I'd like to implement this feature, please assign the issue to me. Thanks!

**Comment by xunliu** [comment]
hi @alan910127 Thank you for your interest this is an issue, I assigned to you.

**Comment by alan910127** [comment]
After a bit of investigation, I've found that the dialogs for creating different resources are quite similar. I'd like to refactor them into a more generic version to make the code cleaner. Should I make these changes in the same PR, or would it be better to create a separate one specifically for refactoring?

**Comment by LauraXia123** [comment]
Separate one specifically for refactoring is better. WDYT?

**Comment by alan910127** [comment]
I’m good with either approach 😊, but I agree a separate PR might be better.

**Comment by alan910127** [comment]
I’m curious about the decision to route the pages for metalakes, catalogs, and schemas using search parameters. Is there a specific reason for this approach? It might be cleaner if we used the Next.js file-based routing instead imo.

**Comment by LauraXia123** [comment]
@alan910127 output mode is `export` when build, can't use the Next.js file-based routing without node server.

**Comment by alan910127** [comment]
@LauraXia123 Got it, thanks for the clarification. However, I thought Next.js can generate an SPA using the Next.js router without requiring a Node server. In our case, would it be possible to remove the `export` setting in the Next.js config?

**Comment by LauraXia123** [comment]
@liuchunhao hi, do you have time for this? If not, I'll take over.
