### ISSUE TITLE
[EPIC] Support web ui for creating table

### ISSUE THREAD

**Issue by LauraXia123** [apache/gravitino#5449]
### Describe the proposal

<img width="514" alt="image" src="https://github.com/user-attachments/assets/56b331a3-c0e2-42ef-8879-908742c2aca1">

### Task list

- [x] #5450
- [x] #5453
- [x] #5454
- [x] #5455

**Comment by orenccl** [comment]
I would like to work on this issue. I'll start by tackling subtask #5450to make progress step-by-step.

If anyone is interested in collaborating on the following subtasks, please feel free to join in!

**Comment by orenccl** [comment]
Added new subtask #5708
