### ISSUE TITLE
[Subtask] Support web ui for creating table (basic column type)

### ISSUE THREAD

**Issue by LauraXia123** [apache/gravitino#5450]
### Describe the subtask

Creating a catalog with type: `relational`
Clicking the schema of catalog
Need a btn `CREATE TABLE` with plus icon
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/89253c7c-12ed-4b70-9ddd-a4c4e4f0e1b1">
<img width="514" alt="image" src="https://github.com/user-attachments/assets/56b331a3-c0e2-42ef-8879-908742c2aca1">

You can find the open api doc here: https://gravitino.apache.org/docs/0.6.1-incubating/api/rest/create-table
You can fine the gravitino table column types here: https://gravitino.apache.org/docs/0.6.1-incubating/manage-relational-metadata-using-gravitino#apache-gravitino-table-column-type

Only support the following column types for this issue:
`[
  'boolean',
  'byte',
  'short',
  'integer',
  'long',
  'float',
  'double',
  'date',
  'time',
  'timestamp',
  'timestamp_tz',
  'string',
  'interval_day',
  'interval_year',
  'uuid',
  'binary',
]`

### Parent issue

#5449

**Comment by orenccl** [comment]
Could you please assign this task to me?

**Comment by orenccl** [comment]
ould you please assign this task to me?

**Comment by xunliu** [comment]
hi, @orenccl Thank you for your interest in this issue, I assigned to you.
