### ISSUE TITLE
[Subtask] Different data table column types are supported depending on the provider

### ISSUE THREAD

**Issue by LauraXia123** [apache/gravitino#5454]
### Describe the subtask

You can find the docs here: https://gravitino.apache.org/docs/0.6.1-incubating/lakehouse-iceberg-catalog#table-column-types

### Parent issue

https://github.com/apache/gravitino/issues/5449

**Comment by orenccl** [comment]
Working on this!

**Comment by orenccl** [comment]
So, aside from Iceberg, do others (MySQL, PostgreSQL, etc...) use the Gravino type?

And previously, the two issues didn't support Struct, Map, or List. Do I need to handle these three types?

**Comment by LauraXia123** [comment]
> So, aside from Iceberg, do others (MySQL, PostgreSQL, etc...) use the Gravino type?
 You can find the docs about other provider table 
<img width="938" alt="image" src="https://github.com/user-attachments/assets/2f2c568e-cbca-4b73-9516-4ee50592d516">

> And previously, the two subtask didn't support Struct, Map, or List. Do I need to handle these three types?
These complex types involve nesting, so if you have the time to implement them, you can start a new subtask and prioritize it last

**Comment by orenccl** [comment]
Sorry, I didn't see that part. 🙇‍♂️ 

> These complex types involve nesting, so if you have the time to implement them, you can start a new subtask and prioritize it last

Sure, I'll open an issue for it later.
