### ISSUE TITLE
[Subtask] Disable to update the reserved fields of table properties

### ISSUE THREAD

**Issue by LauraXia123** [apache/gravitino#5455]
### Describe the subtask

You can pass table properties to Gravitino when creating an table.

The Gravitino server doesn't allow passing the following reserved fields: https://gravitino.apache.org/docs/0.6.1-incubating/lakehouse-iceberg-catalog#table-properties

should disable to edit.

### Parent issue

https://github.com/apache/gravitino/issues/5449

**Comment by orenccl** [comment]
Working on this!
