### ISSUE TITLE
[Improvement] miss drop managed fileset when drop a Hadoop catalog

### ISSUE THREAD

**Issue by mchades** [apache/gravitino#5465]
### What would you like to be improved?

As the comment described, we should drop the managed fileset:
https://github.com/apache/gravitino/blob/b225271739ba5c671052009396443829e4fd6e36/api/src/main/java/org/apache/gravitino/SupportsCatalogs.java#L113-L121

But current only drop the metadata in Gravitino store.

### How should we improve?

we can fix this, after #4842 finalize the behavior of dropping fileset schema

**Comment by jerryshao** [comment]
@mchades I will fix #4842 , can you please help to fix this issue after #4842 is done?

**Comment by mchades** [comment]
If no one takes over this issue this week, I will move on this.
