### ISSUE TITLE
[Improvement] Display audit information on other entities in the Gravitino CLI

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5477]
### What would you like to be improved?

Now that audit info is displayed on metalakes, display audit info for other entities.

### How should we improve?

See above.

**Comment by justinmclean** [comment]
@orenccl do you want to work on this?

**Comment by orenccl** [comment]
I'd like to take this on. :rocket:

**Comment by justinmclean** [comment]
Thanks, I've assigned it to you.

**Comment by orenccl** [comment]
Hi @justinmclean,

Could I add a function called `csvFormat()` in `Audit.java` and use it like this:
```java
String output = audit.csvFormat();
```

Or, alternatively, something like this:
```java
String output = new CSVFormat(audit).handle();
```

**Comment by justinmclean** [comment]
You could add that function to a base AuditCommand and have all the other Audit commands extend that.
