### ISSUE TITLE
[Improvement] Remove `gravitino-docs-0.7.0-incubating.jar` from Gravitino release files as it's a useless and empty files.

### ISSUE THREAD

**Issue by yuqi1129** [apache/gravitino#5490]
### What would you like to be improved?

Download release jar from [gravitino-0.7.0-incubating-bin.tar.gz](https://dist.apache.org/repos/dist/dev/incubator/gravitino/v0.7.0-incubating-rc3/gravitino-0.7.0-incubating-bin.tar.gz) and extract the files from the tar ball

![image](https://github.com/user-attachments/assets/9042a327-9ef7-4ec7-afb9-0c061839a3b0)

**Comment by hdygxsj** [comment]
Please assgn this to me.
