### ISSUE TITLE
[FEATURE] Add formatted output to Gravitino CLI

### ISSUE THREAD

**Issue by waukin** [apache/gravitino#5506]
### Describe the feature

The current output of the Gravitino CLI is as follows:

![image](https://github.com/user-attachments/assets/2cef8992-a317-4183-bd9b-3b5669768003)

I plan to enhance the Gravitino CLI with formatted output to make it look more readable, e.g.

<img width="323" alt="image" src="https://github.com/user-attachments/assets/78e48033-601e-422f-b5bb-20061536c6b2">

**Comment by justinmclean** [comment]
Thanks for the idea, while that is more readable, that format would be harder to parse via a script. I'd suggest that if you want to do this, then you make it available via a format option. A possible extension would be to add the users default format to the gravitino CLI configuration file.

**Comment by xunliu** [comment]
I think we just need to support standard output format, like MySQL client, The Gravitino already have a lot of configuration, make it difficult for user to understand.

**Comment by justinmclean** [comment]
The Gravitino CLI configuration file currently has 3 properties in it; this would add a fourth - it's not that complex. The MySQL client has multiple forms of output, and the default for batch mode (similar to how the Gravitino CLi would be used) is tab-delimited output, not ACSII table output. It's output format is determined by an option or optional aliases.

**Comment by jerryshao** [comment]
Fixed by #5714 .
