### ISSUE TITLE
[Bug report] CLI module doesn't trigger and run any CI pipeline

### ISSUE THREAD

**Issue by jerryshao** [apache/gravitino#5513]
### Version

main branch

### Describe what's wrong

The current CLI module doesn't add itself into the CI checklist, so after the check it will not trigger any real CI pipeline, we should fix it to make CI really work.

### Error message and/or stacktrace

Please see the CI result here in the PR (https://github.com/apache/gravitino/pull/5133).

### How to reproduce

N/A

**Comment by jerryshao** [comment]
Hi @justinmclean can you please check and fix this problem? Thanks.

**Comment by justinmclean** [comment]
@jerryshao where is the CI checklist specified?

**Comment by jerryshao** [comment]
You can check out our github CI yaml to know the details.
