### ISSUE TITLE
[Improvement] Display audit information for roles, users and groups in Gravitino CLI

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5527]
### What would you like to be improved?

Similar to #5477 display audit information for users and groups.

### How should we improve?

See above.

**Comment by Pjaygit** [comment]
@justinmclean can I try working on this?

**Comment by justinmclean** [comment]
Sure, if you need any help just ask.

**Comment by justinmclean** [comment]
@pjaygit how are you going with this?

**Comment by justinmclean** [comment]
@Pjaygit I going to assume from the lack of response you are no longer working on this. If anyone else want to work on this just ask.
