### ISSUE TITLE
[Improvement] Add and delete multiple tags at once in the Gravitino CLI. 

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5528]
### What would you like to be improved?

Add the ability to add and delete multiple tags and to add and delete multiple tags to an entity.

### How should we improve?

See above.

**Comment by sunxiaojian** [comment]
Hey @justinmclean  I'd love to take a stab at this

**Comment by justinmclean** [comment]
Thanks for the help. If you need more details on how to approach this, just ask.
