### ISSUE TITLE
[Improvement] Remove all tags from an entity in the Gravitino CLI.

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5529]
### What would you like to be improved?

Add a command to remove all tags from an entity in the Gravitino CLI.

### How should we improve?

see above.

**Comment by suvaidkhan** [comment]
Hey @justinmclean I'd love to take a stab at this

**Comment by justinmclean** [comment]
Thanks for the offer of help. If you get stuck or need guidance on how to do this, please just ask.

**Comment by justinmclean** [comment]
@suvaidkhan how are you going with this?

**Comment by suvaidkhan** [comment]
@justinmclean hey sorry couldn't get the time to look into this.

I'll start working on this from this weekend.

**Comment by suvaidkhan** [comment]
@justinmclean The changes in this PR seems to be kinda similar to what I'm supposed to do - https://github.com/apache/gravitino/pull/5509

Am I on the right track with this?

**Comment by justinmclean** [comment]
There would be some similarities, but the command would go something different.  In the command, you would need to get the list of tags and then remove them. Look at the other tag commands to see how to do this.

**Comment by suvaidkhan** [comment]
Hey @justinmclean, if my understanding is correct, I have to add a new option in the GravitinoOptions class for deleting all tags, is there any convention we are following in regards to naming this option?

**Comment by justinmclean** [comment]
You would just need to check if teh tag option exists, if it doesn't, then delete all tags.

**Comment by suvaidkhan** [comment]
> You would just need to check if the tag option exists, if it doesn't, then delete all tags.


Got it. Thanks
Just need to test my changes, will raise a PR in a day or two.

**Comment by suvaidkhan** [comment]
@justinmclean hey sorry ran into a few more problems... 

So I'm basically using the ListEntityTags, followed by DeleteTag for this, but I'm getting the error - 
"tagsToAdd and tagsToRemove cannot both be null"

Not sure why this error is popping up. Could there be a problem in the existing delete tag flow? 

The steps to validate were as follows -

Built the gcli and started the playground
Created a hudi catalog using the cli
Added two tags - tagA & tagB using the cli
Then tried to delete it, using the new command

**Comment by justinmclean** [comment]
DeleteTag deletes a tag from the system not removing it from an entity. You'll need to call ListEntityTags then UntagEntity.

**Comment by justinmclean** [comment]
The steps to test would be:
1. create a catalog
2. create some tags
3. tag an entity with multiple tags
4. delete all tags on that entity

**Comment by suvaidkhan** [comment]
> DeleteTag deletes a tag from the system not removing it from an entity. You'll need to call ListEntityTags then UntagEntity.

Still getting the same error - 
"tagsToAdd and tagsToRemove cannot both be null"

used the listTags() to list all tags for that entity and then send that to the associateTags() function for untagging

here's the code snippet - 


```
else if (name.hasCatalogName()) {
        String catalog = name.getCatalogName();
        Catalog gCatalog = client.loadCatalog(catalog);
        tags = gCatalog.supportsTags().listTags();
        gCatalog.supportsTags().associateTags(null, tags);
      }
```

**Comment by justinmclean** [comment]
That code looks correct to me. I just tried this out, and it works fine for me. I think you may be creating the tags but not tagging the catalog? so in your code tags would be null or empty, have you tried debugging it to see what the value is?

Here's what I go after I modified my remove command:
```
gcli tag create --metalake metalake_demo --tag tagA tagB tagC -i
Tags tagA,tagB,tagC created
gcli tag set --metalake metalake_demo --name catalog_postgres --tag tagA tagB tagC -i
catalog_postgres now tagged with tagA,tagB,tagC
gcli tag list --metalake metalake_demo --name catalog_postgres -i
tagA,tagB,tagC
gcli tag remove --metalake metalake_demo --name catalog_postgres -i
catalog_postgres removed tags tagA,tagB,tagC now tagged with nothing
gcli tag list --metalake metalake_demo --name catalog_postgres -i

```
