### ISSUE TITLE
[Bug report] gravitino poms say to expect gradle modules but they are not published

### ISSUE THREAD

**Issue by pjfanning** [apache/gravitino#5535]
### Version

main branch

### Describe what's wrong

Spotted in 0.7.0 (RC) and in 0.6.1.

https://repository.apache.org/content/groups/staging/org/apache/gravitino/meta/0.6.1-incubating/meta-0.6.1-incubating.pom

Says:
```
<!--  This module was also published with a richer model, Gradle metadata,   -->
<!--  which should be used instead. Do not delete the following line which   -->
<!--  is to indicate to Gradle or any Gradle module metadata file consumer   -->
<!--  that they should prefer consuming it instead.  -->
<!--  do_not_remove: published-with-gradle-metadata  -->
```

But the `.module` file is not published. This willl surely confuse Gradle builds that see this comment in the pom but then can't find the module file published alongside it.

https://docs.gradle.org/current/userguide/publishing_gradle_module_metadata.html

### Error message and/or stacktrace

n/a

### How to reproduce

Gradle build

**Comment by jerryshao** [comment]
Let me fix this issue.
