### ISSUE TITLE
[Subtask] support schema pre event for Gravitino server

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#5547]
### Describe the subtask

1. add corresponding `SchemaPreEvent`
2. generate pre-event in `SchemaEventDispatcher`
3. add test in `TestSchemaEvent`
4. add document in `gravitino-server-config.md`

Please refer to the implemetation of table pre event in #5539 

### Parent issue

#5317

**Comment by orenccl** [comment]
It has a reference. I think I’ll be able to take this one. Please assign it to me, and I’ll work on it within a few days.

**Comment by orenccl** [comment]
Hi @FANNG1,

I noticed that in `AlterTableEvent`, `this.tableChanges` is set to `tableChanges.clone()`, 
while in `AlterTablePreEvent`, `this.tableChanges` is assigned directly as `tableChanges`. 
Should it also be `tableChanges.clone()` in `AlterTablePreEvent`?

**Comment by FANNG1** [comment]
Good catch, @orenccl ! I commented related issues in the PR.
