### ISSUE TITLE
[Subtask] add fileset pre event to Gravitino server

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#5548]
### Describe the subtask

1. add corresponding `FilesetPreEvent`
2. generate pre-event in `FilesetEventDispatcher`
3. add test in `TestFilesetEvent`
4. add document in `gravitino-server-config.md`

Please refer to the implemetation of table pre-event in #5539 

### Parent issue

#5317

**Comment by TungYuChiang** [comment]
@xunliu,  I'm interested in working on this issue. Please assign it to me

**Comment by FANNG1** [comment]
@TungYuChiang , done, thanks

**Comment by FANNG1** [comment]
@TungYuChiang is there any process?

**Comment by TungYuChiang** [comment]
Hi @FANNG1 ,

I’m sorry for the delay. I’ve been quite busy this week, but I will make sure to complete it by this weekend. Thank you for your understanding!

**Comment by FANNG1** [comment]
@TungYuChiang  this is just a notice ping,  please take your time
