### ISSUE TITLE
[Subtask] support catalog pre event for Gravitino server

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#5549]
### Describe the subtask

1. add corresponding `CatalogPreEvent`
2. generate pre-event in `CatalogEventDispatcher`
3. add test in `TestCatalogEvent`
4. add document in `gravitino-server-config.md`

Please refer to the implemetation of table pre event in #5539 

### Parent issue

#5317

**Comment by sunxiaojian** [comment]
Can be assigned to me.

**Comment by FANNG1** [comment]
@sunxiaojian , done, thanks
