### ISSUE TITLE
[Subtask] add topic pre event for Gravitino server

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#5551]
### Describe the subtask

1. add corresponding `TopicPreEvent`
2. generate pre-event in `TopicEventDispatcher`
3. add test in `TestTopicEvent`
4. add document in `gravitino-server-config.md`

Please refer to the implemetation of table pre event in #5539 

### Parent issue

#5317

**Comment by LindaSummer** [comment]
Hi @FANNG1 ,

I want to follow up on this issue.

Could it be assigned to me?😄

Best Regards,
Edward
