### ISSUE TITLE
[Subtask] add metalake pre event for Gravitino server

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#5552]
### Describe the subtask

1. add corresponding `MetalakePreEvent`
2. generate pre-event in `MetalakeEventDispatcher`
3. add test in `TestMetalakeEvent`
4. add document in `gravitino-server-config.md`

Please refer to the implemetation of table pre event in #5539 

### Parent issue

#5317

**Comment by LiuQhahah** [comment]
Hi @FANNG1 

Please assign the task to me. 

Thanks
Qiang

**Comment by FANNG1** [comment]
@LiuQhahah , done, thanks
