### ISSUE TITLE
[Improvement] Improve help system and provide extra help and examples in Gravitino CLI

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5568]
### What would you like to be improved?

Add a help command to provide help and examples on each entity including:
- [x] #5603
- [x] catalogs
- [x] schema
- [x] users
- [x] groups
- [x] roles
- [x] tags
- [x] tables
- [x] columns
- [x] filesets
- [x] topics

The command would take the form `cli <entity> help` e.g. `cli metalake help`.

### How should we improve?

For each entity provide more detailed help and provide examples of use - the existing examples in `cli.md` can be used.

**Comment by justinmclean** [comment]
The Gravitino CLI - you can see the PR for metalakes [here](https://github.com/apache/gravitino/pull/5604). Currently, you could do catalogs, schema, users, groups, roles, or tags, the rest are waiting of PRs to be merged.

**Comment by chenyuan99** [comment]
I see. Thanks Justin.
