### ISSUE TITLE
[Improvement] Add ability to grant or revoke multiple roles or groups at once in the Gravitino CLI

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5569]
### What would you like to be improved?

Add the ability to grant or revoke multiple roles or groups at once in the Gravitino CLI

### How should we improve?

see above

**Comment by Abyss-lord** [comment]
Can we use commas to separate values in the command? For example:
`gcli role delete --role admin,role1,role2`

**Comment by Abyss-lord** [comment]
Can we use commas to separate values in the command? For example
`gcli user grant -r rol1,role2,role3 -m demo_metalake --user anonymous`

**Comment by justinmclean** [comment]
By default the CLi library accepts spaces, so this will work if role flag was changed to accept multiple arguments.
`gcli user grant -r rol1 role2 role3 -m demo_metalake --user anonymous`

**Comment by Abyss-lord** [comment]
Could you assign this task to me? I prefer the command style like:
`gcli user grant -r role1 -r role2 -r role3 -m demo_metalake --user anonymous`

**Comment by Abyss-lord** [comment]
> By default the CLI library accepts spaces, so this will work if role flag was changed to accept multiple arguments. `gcli user grant -r rol1 role2 role3 -m demo_metalake --user anonymous`
> 
> as would: `gcli user grant -r rol1 -r role2 -r role3 -m demo_metalake --user anonymous`

Could you assign this task to me? I prefer the command style like:
gcli user grant -r role1 -r role2 -r role3 -m demo_metalake --user anonymous

**Comment by justinmclean** [comment]
While you might prefer that that's not how the other multiple argument command examples are documented, and it's best it be consistent here. While the CLI supports both at the same time, a conscious choice was made not to use single-letter options and not use repeated options in examples. It was thought it would be confusing to the user.

**Comment by justinmclean** [comment]
It would be best to look at how the tag command supports multiple options.

**Comment by Abyss-lord** [comment]
> While you might prefer that that's not how the other multiple argument command examples are documented, and it's best it be consistent here. While the CLI supports both at the same time, a conscious choice was made not to use single-letter options and not use repeated options in examples. It was thought it would be confusing to the user.

Thank you,  I understand the importance of consistency in documentation and avoiding confusion for users. I'll take a closer look at how the tag command supports multiple options and adjust accordingly.

**Comment by justinmclean** [comment]
it is very easy, you add the option with `createArgsOption` rather than `createArgOption` and the CLI library does the rest for you.
