### ISSUE TITLE
[Improvement] support schema exists interface for Iceberg REST server

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#5611]
### What would you like to be improved?

> I checked IcebergNamespaceOperations and Iceberg's catalogHandlers, but didn't find anything like namespaceExists. It seems there isn't an existing function for that.  https://github.com/apache/gravitino/pull/5594#issuecomment-2480547001

As mentioned by @orenccl , we doesn't implement namespace exists interface in Iceberg REST server. We could add the interface like table exists in https://github.com/apache/gravitino/blob/main/iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergTableOperations.java#L237-L256, leveraging `loadNamepace` in `CatalogHandlers` to check whether namespace exists or not.

**Comment by orenccl** [comment]
Please assgn this to me!

**Comment by FANNG1** [comment]
Thanks @orenccl for taking it.

**Comment by orenccl** [comment]
I was exploring and discovered that the `SupportsNamespaces` interface has an `namespaceExists` function.  
You can find it here: [SupportsNamespaces Javadoc](https://iceberg.apache.org/javadoc/1.5.2/org/apache/iceberg/catalog/SupportsNamespaces.html).

**Comment by orenccl** [comment]
I was exploring and discovered that the `SupportsNamespaces` interface has an `exists` function.  
You can find it here: [SupportsNamespaces Javadoc](https://iceberg.apache.org/javadoc/1.5.2/org/apache/iceberg/catalog/SupportsNamespaces.html).

**Comment by FANNG1** [comment]
> I was exploring and discovered that the `SupportsNamespaces` interface has an `namespaceExists` function. You can find it here: [SupportsNamespaces Javadoc](https://iceberg.apache.org/javadoc/1.5.2/org/apache/iceberg/catalog/SupportsNamespaces.html).

yes, this is a better way!
