### ISSUE TITLE
[Subtask] support Aliyun oss credential provider

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#5625]
### Describe the subtask

Besides S3, GCS, we should support credentials from Aliyun oss 

### Parent issue

#4398

**Comment by sunxiaojian** [comment]
@FANNG1 Can assigned  it to me

**Comment by FANNG1** [comment]
> @FANNG1 Can assign it to me

This feature is scheduled to be included in version 0.8, which is set to be released by the end of December. Would this timeline work for you?

**Comment by FANNG1** [comment]
> > This feature is scheduled to be included in version 0.8, which is set to be released by the end of December. Would this timeline work for you?
> 
> OK，no problem , a month should be enough

Thanks,  you could refer to `S3TokenProvider` and `IcebergRESTS3IT`
