### ISSUE TITLE
[Improvement] Remove TestFetchFileUtils test to reduce test failures

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#5642]
### What would you like to be improved?

TestFetchFileUtils may failure for network problems, I suggest to  remove `TestFetchFileUtils` test to reduce test failures, because the test is not too useful.

**Comment by yuqi1129** [comment]
Does the test still fail after the fix https://github.com/apache/gravitino/pull/5613?

**Comment by FANNG1** [comment]
yes
