### ISSUE TITLE
[Improvement] Update the jar name to add gravitino prefix

### ISSUE THREAD

**Issue by jerryshao** [apache/gravitino#5647]
### What would you like to be improved?

Currently, the Gravitino published jars don't have the "gravitino-" prefix, which makes users hard to know if it is from Gravitino or not.

You can check from the maven repo https://repository.apache.org/content/repositories/public/org/apache/gravitino/.

For other projects like Iceberg, they have the project name in your jar (https://repository.apache.org/content/repositories/public/org/apache/iceberg/).

#### Reproduction
1. Execute Gradle command
```
./gradlew publishToMavenLocal -x test
```
2. Chech in your Maven local path
```
~/{maven-path}/org/apache/gravitino/xxxx
```

### How should we improve?

So we should add the "gravitino-" prefix to the jar name.

**Comment by orenccl** [comment]
Hi, I’d like to work on this issue. Please assign it to me.
