### ISSUE TITLE
[Improvement] Web UI create catalog page minor issues

### ISSUE THREAD

**Issue by shaofengshi** [apache/gravitino#5650]
### What would you like to be improved?

1. the "Type" filed, the displayed values, the first character should be capitalized, for example, "relational" change to "Relational".
2. the provider list, should be sorted in alphabet
<img width="610" alt="image" src="https://github.com/user-attachments/assets/dae01037-fbb1-492e-a3a2-09110b3a6216">

**Comment by orenccl** [comment]
Hi, I’d like to work on this issue. Please assign it to me.
