### ISSUE TITLE
[Improvement] Remove `gravitino-web` jar from release package

### ISSUE THREAD

**Issue by yuqi1129** [apache/gravitino#5683]
### What would you like to be improved?

After execute `./gradlew compileDistribution -x test -x :docs:lintOpenAPI`, some unexpected jars like `gravitino-web-xxx.jar` in the release package.

![image](https://github.com/user-attachments/assets/6a0eb133-b37f-499d-859d-786fab956767)
 

This a mirror issue of https://github.com/apache/gravitino/issues/5490, please refer to it to solve the problem

**Comment by TungYuChiang** [comment]
I'm interested in working on this issue. Please assign it to me

**Comment by yuqi1129** [comment]
> I'm interested in working on this issue. Please assign it to me

Sounds good, I will assign it to you.

**Comment by TungYuChiang** [comment]
@yuqi1129 I try `./gradlew compileDistribution -x test -x :docs:lintOpenAPI ` in my Mac and get results like following picture
<img width="883" alt="Screenshot 2024-11-29 at 8 41 48 PM" src="https://github.com/user-attachments/assets/3a7267e5-b861-4b5c-91c6-570ae084e127">
May I ask if this issue occurs randomly?

**Comment by yuqi1129** [comment]
> `ew compileDistribution -x test -x :docs:lintOpenAPI ` in my Mac and get results li

Let me check it again

**Comment by yuqi1129** [comment]
@TungYuChiang 
I have used the latest code (f135a036b7add21ce03bc612342d1c97fac825a9) and got the following

![image](https://github.com/user-attachments/assets/7a5ab0db-86ba-4eb6-84b6-558f3f2168dd)

**Comment by yuqi1129** [comment]
Close it as it's not an issue in the main branch.
