### ISSUE TITLE
[Bug report] UI: edit some table would encounter the error: TypeError: e.type.match is not a function

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#5707]
### Version

main branch

### Describe what's wrong

<img width="1493" alt="image" src="https://github.com/user-attachments/assets/dfb67223-5eca-432a-a946-7f17edbe03a6">

data type as following: 
<img width="1061" alt="image" src="https://github.com/user-attachments/assets/12228012-baf9-4134-8d91-7e0103a9fd58">

<img width="528" alt="image" src="https://github.com/user-attachments/assets/5e27440d-1a88-4e59-8b5a-b2bba89b1f12">

### Error message and/or stacktrace

see above picture

### How to reproduce

1. Create a paimon table with the following sql
```
CREATE TABLE g_tb03 (
    col_boolean BOOLEAN,
    col_int INT,
    col_long BIGINT,
    col_float FLOAT,
    col_double DOUBLE,
    col_decimal DECIMAL(10, 2),
    col_date DATE,
    col_timestamp TIMESTAMP,
    col_timestamptz TIMESTAMP_LTZ,
    col_string STRING,
    col_uuid STRING,
    col_binary BINARY,
    col_struct STRUCT<
        nested_int: INT,
        nested_string: STRING,
        nested_list: ARRAY<STRING>
    >,
    col_list ARRAY<STRING>,
    col_map MAP<STRING, INT>
)
USING paimon
PARTITIONED BY (col_date)
TBLPROPERTIES (
    'write.format.default'='parquet',
    'format-version'='2'
);
```
2. Click the table details button on UI
<img width="1062" alt="image" src="https://github.com/user-attachments/assets/c115c25f-f24d-4ac4-bfdd-26641e665d97">

**Comment by orenccl** [comment]
And, do I need to open another issue to track the implementation of this feature?

**Comment by LauraXia123** [comment]
@orenccl hi, let's simply show only the type name so that the page doesn't crash. 
Support nested table column types is an another issue.

**Comment by orenccl** [comment]
Sure, I will handle this simple solution.
