### ISSUE TITLE
[Improvement] Fix rewrite_config.py with the correct shebang line

### ISSUE THREAD

**Issue by liuchunhao** [apache/gravitino#5754]
### What would you like to be improved?

The script dev/docker/iceberg-rest-server/rewrite_config.py begins with an incorrect shebang line
```bash
#!/usr/bin/env
```
The command `env` should be assigned at least one interpreter.

### How should we improve?

Correct the shebang line to specify the correct shell `bash`

**Comment by FANNG1** [comment]
Good catch! would you like to fix it?

**Comment by liuchunhao** [comment]
Sure! I'd be happy to handle it.
