### ISSUE TITLE
[Improvement] Fixed the alignment problem of formatted output when the output has Chinese

### ISSUE THREAD

**Issue by Abyss-lord** [apache/gravitino#5768]
### What would you like to be improved?

This is a small improvement 
I want to Enhanced gravino CLI formatted output, bounding boxes are not properly aligned when the output has Chinese characters
![image](https://github.com/user-attachments/assets/ef4f685e-1c1b-4d89-9ad1-0ad172768f51)

### How should we improve?

Bounding box length calculation should be calculated using the character display width, not the number of characters，The correct output should look like this
![image](https://github.com/user-attachments/assets/cbb6d813-bff3-40ff-8fa4-bb683c9653f1)

**Comment by Abyss-lord** [comment]
@xunliu can assign it to me

**Comment by Abyss-lord** [comment]
@waukin I’ve made some changes to the code you previously implemented as part of this issue, It's a small improvement,Please let me know if you have any concerns or suggestions regarding the updates. Your feedback would be highly appreciated. Thank you!

**Comment by waukin** [comment]
Hi @Abyss-lord, I didn’t notice this issue while implementing formatted output. I have no concerns—feel free to address it.
