### ISSUE TITLE
[Subtask] support OSS secret key credential

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#5778]
### Describe the subtask

#5625 add dynamic oss token credential,  we'd better support OSS static credential like `S3SecretKeyCredential`, works todo:
1. create `OSSSecretKeyProvider` to generate OSS secret credential
2. create `OSSSecretKeyCredential` to represent oss secret credential information

### Parent issue

#4398

**Comment by sunxiaojian** [comment]
@FANNG1 please assign it to me
