### ISSUE TITLE
[Improvement] Add extended help for schema in Gravitino CLI

### ISSUE THREAD

**Issue by chenyuan99** [apache/gravitino#5782]
### What would you like to be improved?

Add extended help for schema in Gravitino CLI  per #5568 

### How should we improve?

Add extended help for schema in Gravitino CLI per https://github.com/apache/gravitino/issues/5568

**Comment by suvaidkhan** [comment]
hey @chenyuan99 i'd like to take a stab at this

**Comment by chenyuan99** [comment]
> hey @chenyuan99 i'd like to take a stab at this  

go ahead
