### ISSUE TITLE
[Improvement] Modify the ColumnSize/Scale of JdbcTypeBean to be of type int.

### ISSUE THREAD

**Issue by sunxiaojian** [apache/gravitino#5784]
### What would you like to be improved?

Modify the ColumnSize/Scale of JdbcTypeBean to be of type int.

### How should we improve?

Modify the ColumnSize/Scale of JdbcTypeBean to be of type int.

**Comment by mchades** [comment]
may I assign this issue to you? @sunxiaojian

**Comment by sunxiaojian** [comment]
> may I assign this issue to you? @sunxiaojian

@mchades ok， please assign it to me
