### ISSUE TITLE
[Improvement] The Gravitino CLI shoudl show help if no arguments are passed

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5807]
### What would you like to be improved?

If no argument are passed help should be shown to the user.

### How should we improve?

As above.

**Comment by Abyss-lord** [comment]
Hi Justin, Could you please assign this issue to me? I would like to work on it.

**Comment by Abyss-lord** [comment]
@justinmclean Hi justin, I currently have two approaches in mind for implementing this functionality:
- **Directly checking the number of arguments**: If `args` has no elements, call the `GravitinoCommandLine.displayHelp`  to show the help information.
- **Manually adding the --help option**: If no arguments are passed, explicitly set args to `new String[]{"--help"}` and let the existing logic handle it.
In your opinion, which approach would be more appropriate? I would appreciate your feedback on this.

**Comment by justinmclean** [comment]
I'd go with the first one

**Comment by Abyss-lord** [comment]
> I'd go with the first one

Thank you Justin, I have submitted a PR，Could you please take a look when you have time? #5821
