### ISSUE TITLE
[Improvement] In the Gravitino CLI have "gcli metalake --help" and "gcli metalake help" produce the help output

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5822]
### What would you like to be improved?

Provide entity help with the --help option.

### How should we improve?

Do this for all entities not just metalakes.

**Comment by Abyss-lord** [comment]
I would like to work on it.but I found a similar command `gcli metalake help`, `gcli catalog help` and `gcli schema help`, Should I override this feature？
<img width="768" alt="image" src="https://github.com/user-attachments/assets/c349f043-5597-4a11-9f5e-f2620fe9318c">

**Comment by justinmclean** [comment]
We want `gcli entity --help` to work as well as `gcli entity help`, which already works. We want both to work.
