### ISSUE TITLE
[Improvement] Dropping a metalake via the Gravitino CLI gives an "in use" exception.

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5826]
### What would you like to be improved?

Looks like there has been some code changes around metalake being in use that make it difficult to drop a metalake. If you create a metalake called `my_metalake` and run this command `gcli metalake delete --metalake my_metalake` you get an exception.

The exection info is misleading `Failed to operate metalake(s) [my_metalake] operation [DROP], reason [Metalake my_metalake is in use, please disable it first or use force option]`

`gcli metalake delete --metalake my_metalake --force` gives the same error.

### How should we improve?

Look into code changes and come up with a way to fix this, and also possibly fix the misleading exception text.

**Comment by justinmclean** [comment]
A similar error occurs when deleting catalogs

**Comment by Abyss-lord** [comment]
I would like to work on it.
