### ISSUE TITLE
[Improvement] Slightly missleading error message when user is not specified in Gravitino CLI

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5828]
### What would you like to be improved?

When running this command `gcli user create --metalake metalake_demo` you get the error `"name" field is required and cannot be empty`, but it the user field that is missing.

### How should we improve?

Tell the user the correct missing field.

**Comment by justinmclean** [comment]
Note that `gcli user details --metalake metalake_demo` missing `--user` gives `Invalid string to encode: null` as does `user delete --metalake metalake_demo`. These could be fixed at the same time.

**Comment by justinmclean** [comment]
Note the error is saying that the name of the of the user is empty so it not incorrect it's just not user-friendly.

**Comment by Abyss-lord** [comment]
I would like to work on it.
