### ISSUE TITLE
[Improvement] Slightly missing leading error message when group is not specified in Gravitino CLI 

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5829]
### What would you like to be improved?

When running `gcli group create --metalake metalake_demo` you get `"name" field is required and cannot be empty`.

### How should we improve?

Display the correct missing field.

**Comment by justinmclean** [comment]
`group details --metalake metalake_demo -i` and `gcli group delete --metalake metalake_demo` give `Invalid string to encode: null` and should also be fixed.

**Comment by justinmclean** [comment]
Note the error is saying that the name of the of the group is empty so it not incorrect it's just not user-friendly.

**Comment by Abyss-lord** [comment]
I would like to work on it.
