### ISSUE TITLE
[Improvement] Missing tag name in creating Gravitino CLI command gives an exception.

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5830]
### What would you like to be improved?

Running the command `gcli tag create --metalake metalake_demo` gives an exception. The same happens for `gcli tag details --metalake metalake_demo` and `gcli tag delete --metalake metalake_demo`

### How should we improve?

A friendly error message should be displayed.

**Comment by LindaSummer** [comment]
Hi @justinmclean ,

I want to follow up on this issue. 😊

Could this be assigned to me?

Best Regards,
Edward

**Comment by justinmclean** [comment]
Sure, if you need any help on how to do this, just ask.
