### ISSUE TITLE
[Improvement] Setting a tag property in the Gravitino CLi gives unexpected output

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5831]
### What would you like to be improved?

Running the command `gcli tag set --metalake metalake_demo` or `gcli tag remove --metalake metalake_demo` gives unexpected output.

### How should we improve?

While nothing is done and no exception occurs, the output could be more user-friendly.

**Comment by Abyss-lord** [comment]
I would like to work on it.
