### ISSUE TITLE
[Improvement]  Improve error message for missing role name in the "gcli role create" command.

### ISSUE THREAD

**Issue by Gurleen12star** [apache/gravitino#5834]
### What would you like to be improved?

Currently, when the gcli role create command is run without specifying a role name, the error message shown is vague and does not directly indicate the missing field. This can cause confusion and difficulty in troubleshooting for users.

### How should we improve?

The error message should be more descriptive and directly point out that the role name is missing. An example of the improved error message could be:
Error: The role name is required and cannot be empty. Please use the '--role-name <name>' argument to specify the role name.
This will help users easily identify what is missing and how to resolve the issue without needing to look up documentation or guess what went wrong.

**Comment by justinmclean** [comment]
Closing as this is a duplicate of #5832 and clearly generated by AI.
