### ISSUE TITLE
[Improvement] Make the entity and arguments case-insensitive

### ISSUE THREAD

**Issue by Abyss-lord** [apache/gravitino#5853]
### What would you like to be improved?

At present, the requirement for entities to be entered in lowercase is not user-friendly. For instance, when I input "Metalake," the system returns an "Unknown entity" error. The intended purpose of this error message appears to be informing the user that the input is not a valid entity, such as a partition. i think both entity names and command arguments should be case-insensitive.
<img width="256" alt="image" src="https://github.com/user-attachments/assets/821fba94-c474-48f6-a483-d91dd99639ce" />
<img width="262" alt="image" src="https://github.com/user-attachments/assets/04914da0-474d-4f66-998c-df7704d96da1" />

### How should we improve?

Modify the validation logic for the entity and command parameters to make them case-insensitive.

**Comment by Abyss-lord** [comment]
@justinmclean I would like to work on it.

**Comment by justinmclean** [comment]
In general CLI commands are all lower case see https://clig.dev/#naming see "Use only lowercase letters,..."

**Comment by Abyss-lord** [comment]
> In general CLI commands are all lower case see https://clig.dev/#naming see "Use only lowercase letters,..."

@justinmclean Should we provide some assistance information when the user inputs a command that is not in lowercase?

**Comment by justinmclean** [comment]
I really don't think a user would use mixed case, or if they did, it would be very very rare. If you want, feel free to convert the command and entity passed in to lowercase.

**Comment by Abyss-lord** [comment]
II would like to work on it.
