### ISSUE TITLE
[Bug report] Doc: "COLUMN" doesn't have owner, please remove it from metadataObjectType possible values in set-owner/get-owner api doc

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#5911]
### Version

main branch

### Describe what's wrong

https://gravitino.apache.org/docs/0.7.0-incubating/api/rest/set-owner
https://gravitino.apache.org/docs/0.7.0-incubating/api/rest/get-owner
<img width="1006" alt="image" src="https://github.com/user-attachments/assets/1293b167-7df5-4f31-ab0e-4466d7a14d94" />

### Error message and/or stacktrace

N/A

### How to reproduce

N/A

**Comment by cool9850311** [comment]
Working on this
