### ISSUE TITLE
[Improvement]  add gc related opts when start gravitino server

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#592]
### What would you like to be improved?

it'll be useful to troubleshoot problems with gc info。

**Comment by RamonJales** [comment]
I would like to work on this. Please tell me what to do exactly !

**Comment by FANNG1** [comment]
thanks, @RamonJales , you could refer some famous java projects, like trino, Hadoop, kafka

**Comment by FANNG1** [comment]
close it as not a strong requirement.
