### ISSUE TITLE
[Improvement] When no schema exist Gravitino CLI command outputs nothing.

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5924]
### What would you like to be improved?

Using the playground and runing this `gcli schema list --metalake metalake_demo --name catalog_iceberg -i` gives no output.

### How should we improve?

While this is correct, it could be confusing to the user perhaps output "No schemas exist."? We should always have a metalake so I don't think it is needed there, and tables should have columns, so again not needed there, (same with filesets and topics), but it would also be possible for a schema to have no tables.

**Comment by Abyss-lord** [comment]
I would like to work on it.
