### ISSUE TITLE
[Improvement] Missleading error message in Gravitino CLI when missing schema name

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5926]
### What would you like to be improved?

Running this command with the playground `gcli schema details --metalake metalake_demo --name catalog_postgres -i`  gives this output:
```
Malformed entity name.
Invalid string to encode: null
```

### How should we improve?

The output should be something like:
```
Malformed entity name.
Unknown schema name.
```

**Comment by Abyss-lord** [comment]
I would like to work on it.
