### ISSUE TITLE
[Improvement] In the Gravitino CLI you can get multiple "Malformed entity name." messages

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5927]
### What would you like to be improved?

With a command like this and the playground running:
```
gcli column list --metalake metalake_demo --name catalog_postgres.hr.departments -i
```

You get multiple

### How should we improve?

Change `getNamePart` so that it only outputs `Malformed entity name.` once.

**Comment by Abyss-lord** [comment]
I would like to work no it.
