### ISSUE TITLE
[Improvement] In the Gravitino CLI a user details command can produce no output

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5929]
### What would you like to be improved?

If a user has no roles then no output is produced from this command `gcli user details --metalake metalake_demo --user new_user -i`

### How should we improve?

Output "User has no roles." or similar.

**Comment by justinmclean** [comment]
Same issue exists with `gcli group details --metalake metalake_demo --group new_group -i`, so it would be best if this is fixed  at the same time.

**Comment by Abyss-lord** [comment]
I would like to  work on it.
