### ISSUE TITLE
[Improvement] In the Gravitino CLI add an unknown tags give no error

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#5930]
### What would you like to be improved?

Adding a tag that doesn;t exist will give no error and no tag is added. Example command and output:
```
gcli tag set --metalake metalake_demo --name catalog_postgres --tag unknown -i
catalog_postgres now tagged with 
```

### How should we improve?

The output could be improved e.g. "catalog_postgres now tagged with nothing". However, this seems more like a Java API issue in that NoSuchTag exception or similar should have been thrown.

**Comment by mchades** [comment]
This is an intentional behavior, for non-existent tags, its behavior is on-op. I think we just need to improve the documentation. WDYT? @jerryshao

**Comment by jerryshao** [comment]
Yes, it is by design, otherwise it will be a high-cost operation to check the validity of tags. I can improve the docs if required.

**Comment by justinmclean** [comment]
Other tag commands do check if the tag exists e.g. setting a property on a tag

**Comment by Abyss-lord** [comment]
I would like to work on it.
