### ISSUE TITLE
[Bug report] The owner of the catalog is incorrect when using Basic Auth and Password is empty

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#5968]
### Version

main branch

### Describe what's wrong

Create catalog, use Basic Auth, and Password is empty, the creator is anonymous 
actually the creator is expected to be the user: manager-a

<img width="932" alt="image" src="https://github.com/user-attachments/assets/ed78c428-faa7-4848-acf9-b38a32e60f11" />

### Error message and/or stacktrace

N/A

### How to reproduce

1. Add user manager-a to metalake
2. In the metalake created in step1, create a catalog use manager-a in Basic Auth, and set the password is empty
3. The owner of the catalog in step2 isn't the manager-a which is expected.

**Comment by danhuawang** [comment]
@jerqi Can you help check this issue?

**Comment by jerqi** [comment]
https://stackoverflow.com/questions/14247637/can-the-password-in-http-basic-be-optional

The password and user can be optional. But it's necessary for our current implement.  We should correct it.

**Comment by frankvicky** [comment]
May I take over this issue ?

**Comment by jerqi** [comment]
> May I take over this issue ?

Assigned. Thanks.
