### ISSUE TITLE
[Bug report] MySQL table's audit info is empty after user Alice rename the table

### ISSUE THREAD

**Issue by danhuawang** [apache/gravitino#5986]
### Version

main branch

### Describe what's wrong

<img width="959" alt="image" src="https://github.com/user-attachments/assets/5c285c55-3c4c-4e05-ae46-7a701b8d5e68" />

### Error message and/or stacktrace

N/A

### How to reproduce

1. Configure gravitino, gravitino.authorization.enable
2. Add user Alice to mysql metalake
3. Create MySQL catalog and load the mysql table in the MySQL instance
4. Rename one MySQL table by Gravitino, "audit" info is still empty ,it's not expected.

**Comment by danhuawang** [comment]
@jerqi Can you help check this issue ?

**Comment by jerqi** [comment]
The behaviour is expected now. So I will close this.
