### ISSUE TITLE
[Bug report] Gravitino CLI get wrong catalogName when set metalake name by  --name option

### ISSUE THREAD

**Issue by luoshipeng** [apache/gravitino#6027]
### Version

main branch

### Describe what's wrong

when i use gcli command, if i set `--name` option value to `lsp_test.mysql_test.test_db`, it uses part[0] as both the metalakeName and the catalogName.

Reason
1. when i not set `--metalake`, and no `GRAVITINO_METALAKE`, no configFile. it will extract part[0] of `--name` option as metalakeName in `org.apache.gravitino.cli.FullName#getMetalakeName`.
2. it always extract part[0] of `--name` option as catalogName in `org.apache.gravitino.cli.FullName#getCatalogName`。

### Error message and/or stacktrace

![image](https://github.com/user-attachments/assets/4f3e46d0-356f-49b7-8088-a853e61c3d9c)

### How to reproduce

specific FullName by --name option only. No --metalake, no metalakeEnv, and no config file.
``` gcli -u http://xxx:8090 table list --name lsp_test.mysql_test.test_db ```

**Comment by luoshipeng** [comment]
sorry, i forgot paste server log
![image](https://github.com/user-attachments/assets/1a7cea7f-4879-4513-b10b-7b0c1e63fb45)

**Comment by Abyss-lord** [comment]
@justinmclean , I would like to work on it.

**Comment by justinmclean** [comment]
This is the correct behaviour as you should always set the metalake in one of the 3 ways describe in the documentation. We should print out an error message if the metlake name is not defined. Orginally the code did use metlake as the first part of the name name, which is why it's behaviour is a little incosistant.
