### ISSUE TITLE
[Improvement] Improve GitHub token permissions

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#727]
### What would you like to be improved?

Scorecard reports an issue with token permissions "detected GitHub workflow tokens with excessive permissions".

Note that ASF's Github is likely to have more restrictions than what we have set up and we're likely to have to change our workflows at some point.

See:
https://github.com/ossf/scorecard/blob/49c0eed3a423f00c872b5c3c9f1bbca9e8aae799/docs/checks.md#token-permissions 

### How should we improve?

Consider changing permission to be less excessive.

**Comment by jerryshao** [comment]
As a ASF project, we cannot manage the token anymore, so this is not valid anymore, I'm going to close this issue.
