### ISSUE TITLE
[Improvement] Compile fails when using JDK21

### ISSUE THREAD

**Issue by justinmclean** [apache/gravitino#906]
### What would you like to be improved?

Compile fails when using JDK21 with this error:
Build gravitino FAILURE reason:                                
    Execution failed for task ':api:compileJava':
        java.lang.RuntimeException: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid'

### How should we improve?

Be able to compile when using JDK21

**Comment by zuotingbing** [comment]
> > Also fails using JDK11 BTW
> 
> JDK11 should be worked, I verified several times, I guess you doesn't test in a clean environment, you still have Gradle deamon running when you switching to JDK11.
> 
> I see this problem only exists in JDK21.

What is the current status or roadmap for JDK 21 compilation support?
